### ISSUE TITLE
Problem with searching when on second page of results

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#104]
It has been identified that if you browse to the second page of apps, and then do a search, you have to navigate back to the previous page to see the results.

Original comment here:

https://twitter.com/scottisafool/status/434082950037393408

**Comment by vertigo220** [comment]
It looks like this was fixed a few years ago, but I'm still noticing the same behavior. If you perform a search, then navigate to another page, then do another search, it will put you on the results page for the new search that you were on before the search. For example, if you search for "browser" and go to page x, then search for "firefox," you'll get page x of the results for the firefox search. It should always start you off with the first page.
