### ISSUE TITLE
Ability to hide installed items in "chocolatey" tab

### ISSUE THREAD

**Issue by eyalroz** [chocolatey/ChocolateyGUI#1049]
### Is Your Feature Request Related To A Problem? Please describe.

I want to filter my search results so that they don't include what I've already installed.

<sub>Actually, I would have liked to filter out everything that is kind-sorta-like what I've installed (other version, portable vs install variant etc.) but let's start with the simpler feature.</sub>

### Describe The Solution. Why is it needed?

A toggle for hiding items I've already installed, in the "chocolatey" tab (as opposed to the "This PC" tab), would be nice

**Comment by gep13** [comment]
Just to confirm, is what you are asking for already covered by this feature toggle?

https://docs.chocolatey.org/en-us/chocolatey-gui/setup/configuration/features/exclude-installed-packages

**Comment by eyalroz** [comment]
Yes, that's it.
