### ISSUE TITLE
Loading package icons is slow

### ISSUE THREAD

**Issue by Mugane** [chocolatey/ChocolateyGUI#1060]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

The problem is that the GUI loads so slowly that it is practically unusable

### Describe The Solution. Why is it needed?

Cache app icon images

### Additional Context

Retrieving app icon images on each load from up to hundreds of sources is simply not a practical solution. These should be cached.

**Comment by pauby** [comment]
Duplicate of #595
