### ISSUE TITLE
Problem with opening Sources setting page

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#124]
When you open the Settings flyout, clicking anywhere else of the application results in that flyout going away.

However, when you click on the Sources link within the flyout, clicking anywhere on the application don't result in it going away.  Instead, you have to click the back button to take you back to the Settings flyout, and then you can click anywhere to close.

Is this by design?

**Comment by gep13** [comment]
I am going to push this to the next release, since it will be part of the overall re-thinking of the application, with the change in style, etc.

**Comment by RichiCoder1** [comment]
:+1:

**Comment by pascalberger** [comment]
@RichiCoder1 Can't this be closed with the recent commits?

**Comment by RichiCoder1** [comment]
Ahh yes, thanks for reminding me.
