### ISSUE TITLE
Chocolatey GUI with proxy server

### ISSUE THREAD

**Issue by FROSADO** [chocolatey/ChocolateyGUI#128]
I'm not sure if the problem is related with the proxy server, but appear that is the reason. 

I open the ChocolateyGUI and i can't get information about the installed packages 
```
Could not download package information from 
'http://chocolatey.org/api/v2/Packages?$filter=IsLatestVersion eq true and Id eq '7zip.install'') 
```

Open the _available_packages_ tab cause that the application crash. 

I think that the problem is related with the proxy configuration.

**Comment by gep13** [comment]
Looking at the code that was submitting, it is clear that this was related to the older 0.11 branch of ChocolateyGUI.  In the soon to be released 0.12 version of ChocolateyGUI this is handled in a different way.

I am going to close this issue for now, in the hope that the new version will work correctly.  If it doesn't, please feel free to re-open this issue.  Thanks!

**Comment by braindumped** [comment]
I'm using 0.12.3 and I'm sitting behind a proxy and CholoateyGUI crashes when I click on "Chocolatey" below "This PC"

**Comment by gep13** [comment]
@braindumped  Can you confirm what version of Chocolatey you have installed?  Would it be possible to include a screen shot of the error that you are seeing?

**Comment by braindumped** [comment]
![2015-03-12_11h45_30](https://cloud.githubusercontent.com/assets/710556/6616376/a6eb791a-c8ad-11e4-93ff-e98edc6a1a8b.png)
![2015-03-12_11h48_48](https://cloud.githubusercontent.com/assets/710556/6616390/c00af20e-c8ad-11e4-89a9-38ea2d839647.png)

the message is comming from the proxy (we need authentication to use the proxy)

**Comment by gep13** [comment]
Ah, ok, so you are using the latest Chocolatey.  Currently ChocolateyGUI does not support the latest Chocolatey.  Please follow this issue https://github.com/chocolatey/ChocolateyGUI/issues/230 for more information.

**Comment by braindumped** [comment]
uups. ok, thx

**Comment by gep13** [comment]
I am hoping to have this corrected soon, so that it will work with the latest Chocolatey, I have had to tidy up a few other things on the project before I can look at this though.  If you follow that issue, you will see updates about how things are going.
