### ISSUE TITLE
Investigate the use of UpperCut

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#162]
Based on Rob's suggestion, take a look at UpperCut for controlling the build pipeline of ChocolateyGUI

**Comment by ferventcoder** [comment]
Use Cake instead. 👍 

And let's get UppercuT using Cake.

**Comment by RichiCoder1** [comment]
Yup yup. At least for now, the build scripts work, and work well (thanks @gep13!) so I'm not going to touch them. But cake will def be preference to move to in the future.

**Comment by gep13** [comment]
@ferventcoder @RichiCoder1 Cake would get my vote too.

**Comment by devlead** [comment]
I'm biased to I'll just :+1:  :wink:
