### ISSUE TITLE
Globalisation/Localisation

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#170]
Do we want to handle this?

If so, turn back on CA1303

**Comment by RichiCoder1** [comment]
Which should at least put everything in place. I think we're actually pretty good about using the resx.

**Comment by gep13** [comment]
@mwallner this is the issue that I think you might want to look at.  Thanks!

**Comment by mwallner** [comment]
Jup, thx - working on it :-) - I'm splitting the dev up into two issues - first one moves English strings to resx - second one adds my German translation. (can assign me if you want) - just a busy week and new StyleCop !#@arrrgh

**Comment by gep13** [comment]
@mwallner are there any rules in particular that you are finding jarring? We can discuss turning other rules off.

**Comment by gep13** [comment]
Thanks to @mwallner this has been taken care of 😄
