### ISSUE TITLE
A feature under the menu strip to be able to refresh package lists.

### ISSUE THREAD

**Issue by deavmi** [chocolatey/ChocolateyGUI#177]
A feature under the menu strip to be able to refresh package lists. As I couldn't uninstall WinRAR from ChocolateyGUI and had to us the Windows Programs and Features to uninstall it. And ChocolateyGUI didn't update the lists as the uninstall didn't take place from the ChocolateyGUI itself.

*Contributor Edit:*
To sum, add button to refresh local package information. (RS)

**Comment by gep13** [comment]
Added a couple new buttons to provide the requested functionality:

![image](https://cloud.githubusercontent.com/assets/1271146/6137346/064c41a0-b170-11e4-8148-f69983c4f374.png)

![image](https://cloud.githubusercontent.com/assets/1271146/6137354/0e355b72-b170-11e4-93e2-a5769fe9dd62.png)

**Comment by deavmi** [comment]
@gep13 Yay! :D
