### ISSUE TITLE
Windows 7 - app crash on its' every startup

### ISSUE THREAD

**Issue by esamo** [chocolatey/ChocolateyGUI#194]
Pasting the crash signature info below.

Maybe some requirements are not met, like precise version of .NET or MS Visual?

What soft should I have installed?

I've tried run as admin and WinXp SP3 compatibility so far.

---

Podpis problemu:
  Nazwa zdarzenia problemu:	CLR20r3
  Podpis problemu: 01:	chocolateygui.exe
  Podpis problemu: 02:	0.11.4.2
  Podpis problemu: 03:	5418969a
  Podpis problemu: 04:	Anonymously Hosted DynamicMethods Assembly
  Podpis problemu: 05:	0.0.0.0
  Podpis problemu: 06:	0
  Podpis problemu: 07:	0
  Podpis problemu: 08:	ffffffff
  Podpis problemu: 09:	StructureMap.StructureMap
  Wersja systemu operacyjnego:	6.1.7601.2.1.0.256.1
  Identyfikator ustawień regionalnych:	1045
  Dodatkowe informacje 1:	0a9e
  Dodatkowe informacje 2:	0a9e372d3b4ad19135b953a78882e789
  Dodatkowe informacje 3:	0a9e
  Dodatkowe informacje 4:	0a9e372d3b4ad19135b953a78882e789

---

Regards & respect

**Comment by esamo** [comment]
Thanks.

'Run as admin' - no difference.

But installing `ChocolateyGUI v0.12.0-unstable0125` fixed the problem, that one works fine.

---

1. Where should I report package name completely replaced by other one?

2. How can I read package's description via `choco` command?

---

Regards & respect

**Comment by gep13** [comment]
@esamo 

With regard to this:

> Where should I report package name completely replaced by other one?

I am not sure what you mean, can you elaborate?

And for:

> How can I read package's description via choco command?

As documented here, you can use the ```-verbose``` flag on the ```choco list``` command.

**Comment by esamo** [comment]
Thanks. I mean phrase `teamspeak` popping out during `fraps` installation. Confusing at least.
Here is part of the log:

`20141230-21:42:31 [CHOCO] Downloading teamspeak 64 bit
from 'http://www.fraps.com/free/setup.exe'`

-> [Full log here](http://textuploader.com/657h)

---

Regards & respect

**Comment by gep13** [comment]
@esamo in this particular example, this is a bug with the Chocolatey Package itself, not with Chocolatey.  If you look at the source files for the package with Nuget Package Explorer, you will see the following:

![image](https://cloud.githubusercontent.com/assets/1271146/5599086/02b24fec-92b9-11e4-869a-0fee30471111.png)

The packageName has been set as ```teamspeak```.  Chocolatey uses the value of this variable in various log statements, as you have seen, which is causing the confusion.

Can I get you to reach out to the package maintainers directly, which you can do by clicking on the Contact Maintainers link on this page:

https://chocolatey.org/packages/fraps

And ask them to correct this?

Thanks

**Comment by esamo** [comment]
Yeah, done.
