### ISSUE TITLE
Support for SVG package icons

### ISSUE THREAD

**Issue by TomOne** [chocolatey/ChocolateyGUI#202]
This is a follow-up of https://github.com/chocolatey/chocolatey-coreteampackages/commit/67e9632516c20d96fa043cf251cd5b9bad6a289b#commitcomment-9096648.

It would be great if ChocolateyGUI would support SVG as package icons too, just like all relevant browsers out there.

SVG is definitely a format that is worth to support. It has often much less file size than its raster counterpart (especially when gzipped) and looks crystal clear on every device, even on HiDPI screens.

Examples of Choco packages which use SVG icons:
- https://chocolatey.org/packages/javaruntime
- https://chocolatey.org/packages/GoogleChrome
- https://chocolatey.org/packages/python
- https://chocolatey.org/packages/blender

**Comment by RichiCoder1** [comment]
Closed by #348.
