### ISSUE TITLE
Unable to add source

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#204]
In order to answer a question on Gitter chat, I created the following wiki article:

https://github.com/chocolatey/ChocolateyGUI/wiki/How-to-add-a-new-custom-source

Typing as I was following along in ChocolateyGUI.  When I tried to add the following:

![image](https://cloud.githubusercontent.com/assets/1271146/5636915/8aa9085e-95ee-11e4-9f80-2b6aff6507fa.png)

Which I believe to be a valid Nuget Feed, I was met with the following:

![image](https://cloud.githubusercontent.com/assets/1271146/5636955/cbf201e4-95ee-11e4-9c63-2917602e06f4.png)

On debugging, I got the following:

![image](https://cloud.githubusercontent.com/assets/1271146/5636940/b923deca-95ee-11e4-8cd3-1817bf48b598.png)

@RichiCoder1 any thoughts on what is going on here?

Thanks!

**Comment by gep13** [comment]
The text from the exception is:

```
The property 'NormalizedVersion' does not exist on type 'ChocolateyGui.ChocolateyFeedService.V2FeedPackage'. Make sure to only use property names that are defined by the type.
```

**Comment by maartenba** [comment]
MyGet and NuGet have property named NormalizedVersion, while Chocolatey and the OData proxy you generated don't. 

I believe you can set the proxy to ignore missing properties, or you could regenerate it against NuGet.org's feed.

**Comment by gep13** [comment]
@maartenba thanks for getting back to me.

Ok, I will look into those suggestions.

Related question, what is NormalizedVersion, and should we be adding it to the Chocolatey.org feed?  Was it part of some standard change?  Although chocolatey.org was forked from nuget.org, we haven't been pulling in upstream changes, because we have diverged quite a bit from nuget.org, i.e. in terms of package moderation, etc.

**Comment by maartenba** [comment]
In the feed, it can be just == Version for now. I believe it's been introduced to have a fallback for when SemVer 2.0 is introduced, so that one property is compliant with SemVer 1.0 and the other with 2.0 if I recall correctly. Perhaps good to join the Google Group at https://groups.google.com/forum/#!forum/nuget-ecosystem

**Comment by gep13** [comment]
> Perhaps good to join the Google Group at https://groups.google.com/forum/#!forum/nuget-ecosystem

Will do, thanks!

@ferventcoder what are your thoughts on this?

**Comment by ferventcoder** [comment]
NormalizedVersion is something we need.

**Comment by ferventcoder** [comment]
It takes 1.0 and makes it the same as 1.0.0 and 1.0.0.0. That way you only have one package that is 1.0

**Comment by ferventcoder** [comment]
@maartenba UH a google group? Some of the original nuget team was resistant to that when we suggested it originally. My how things have changed since 2010. ;)

**Comment by RichiCoder1** [comment]
I could have sworn I fixed this. I'll look into it.

**Comment by gep13** [comment]
@RichiCoder1 thank you!  Even if you can give me a pointer where to start looking, I can dig into it.

**Comment by RichiCoder1** [comment]
@maartenba is correct in that there should be a setting in the generated OData feed proxy to disable it.

Somewhere around here:
https://github.com/chocolatey/ChocolateyGUI/blob/develop/Source/ChocolateyGui/Services/PackageServices/ODataPackageService.cs#L127

**Comment by gep13** [comment]
Ha ha, you mean this setting:

https://github.com/chocolatey/ChocolateyGUI/blob/develop/Source/ChocolateyGui/Services/PackageServices/ODataPackageService.cs#L129

:smile:

**Comment by RichiCoder1** [comment]
Nope. That lets the feed continue if it's expecting properties that aren't. Our issue is the feed is getting properties it things shouldn't be there.

**Comment by gep13** [comment]
Ah, yeah, you are right :-P

**Comment by RichiCoder1** [comment]
Ahhhhhhhhhh.
But you are right, and I'm derp. TestPath creates it's own FeedContext rather than calling into GetFeed.

**Comment by gep13** [comment]
I have just pushed a fix for this, will be ready on MyGet once it is done cooking on AppVeyor.

**Comment by gep13** [comment]
Just verified this on work machine and it is now working.
