### ISSUE TITLE
ShimGen crash

### ISSUE THREAD

**Issue by Diogny** [chocolatey/ChocolateyGUI#210]
C:\WINDOWS\system32>choco /?

Unhandled Exception: System.ComponentModel.W
   at System.Diagnostics.Process.StartWithCr
   at shim.CommandExecutor.execute(String pr
ait_for_exit, Boolean requires_elevation)
   at shim.ShimProgram.Main(String[] args)

**Comment by gep13** [comment]
@Diogny thanks for reaching out!

Sorry to hear that you are having problems!  Based on what you have mentioned above, I don't think that this is an issue with ChocolateyGUI, but rather a problem with Chocolatey.  Am I right in saying that?  If so, can you re-post your issue in the Chocolatey Repository?  Or better, can you join us in our Gitter Chat Room before posting an issue, and hopefully we can help you there:

https://gitter.im/chocolatey/choco

It would be helpful to know what version of Chocolatey you are using?  And also what Operating System you are running on.

I am going to close this issue, as I don't think it is anything to do with ChocolateyGUI.  Feel free to re-open the issue if I have misunderstood something.
