### ISSUE TITLE
Highlight packages where update is available

### ISSUE THREAD

**Issue by iTob191** [chocolatey/ChocolateyGUI#223]
Some kind of highlighting in the "This PC"-overview for updatable packages would be nice :)

**Comment by gep13** [comment]
Again, I can see how this would make sense.  Just need to decide what sort of highlight makes sense.  Let me think about this one for a while.

**Comment by gep13** [comment]
I have had a think about this one, and I think that rather than highlight a row with an update available, I will add a new filter to the search capabilities.  Something like this:

![image](https://cloud.githubusercontent.com/assets/1271146/6449598/e6e3e854-c119-11e4-9ad2-73e5c0b9202e.png)
