### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by iTob191** [chocolatey/ChocolateyGUI#225]
I'm not really sure if this is possible with chocolatey, but it would be very helpful if the there would be error messages if errors occured during installation/update. At the moment the error message from the console is printed into that box, but the box instantly dissapears after the script finishes..

**Comment by gep13** [comment]
I think there might be something that we can do here, but I will have to confirm with @RichiCoder1.  This might also be something that is best left until we implement Chocolatey vNext, as I suspect that this information will be more available to us, and can be displayed over effectively.

Thanks for the suggestion! :+1:

**Comment by RichiCoder1** [comment]
Hmm. I have no idea if this was fixed.

**Comment by gep13** [comment]
@RichiCoder1 yeah, not sure if it was fixed or not :cry:

**Comment by RichiCoder1** [comment]
I'll investigate.

**Comment by welwood08** [comment]
Just to confirm, errors still do not remain visible in the GUI after the choco commands have finished. The only indication that something went wrong is that the desired state (package installed/updated/etc) has not been reached and the GUI looks exactly as it did before commands were run.

**Comment by RichiCoder1** [comment]
Chocolatey GUI should now be *much* better about this w/ latest develop.
