### ISSUE TITLE
ChocolateyGUI does not work with Chocolatey 0.9.9.x

### ISSUE THREAD

**Issue by JohnEricson** [chocolatey/ChocolateyGUI#230]
I'm testing out One-Get and Chocolatey on Windows 10 TP and tried to install ChocolateyGUI. It installs fine but always crashes on error. The error message is included in this image:

![error](https://cloud.githubusercontent.com/assets/946327/6492457/06a45872-c2b4-11e4-84ff-4913d884884f.png)

Somehow I have two installations of Chocolatey on my computer:

```
C:\ProgramData\chocolatey>choco list -local-only
Chocolatey v0.9.9.1
chocolatey 0.9.9.1
ChocolateyGUI 0.12.3
lockhunter 3.1.1
PowerShell 4.0.20141001
4 packages installed.
```

and:

```
C:\Chocolatey\bin>choco list -local-only
Chocolatey v0.9.9.1
ChocolateyGUI 0.12.3
PowerShell 4.0.20141001
2 packages installed.
```

And One-Get reports this:

```
PS C:\WINDOWS\system32> get-package chocolate

Name                                                                          Version      Status       ProviderName     Source           Summary
----                                                                          -------      ------       ------------     ------           -------
chocolatey                                                                    0.9.9.1      Installed    Chocolatey       C:\Chocolatey... Chocolatey is your machine level NuGet repository. Think apt-get for Wind...
ChocolateyGUI                                                                 0.12.3       Installed    Chocolatey       C:\Chocolatey... A GUI for Chocolatey
ChocolateyGUI 0.12.3.0                                                        0.12.3.0     Installed    msi              C:\Chocolatey...
```

I don't know how to get One-Get to list all installed packaged belonging to provider Chocolatey.

**Comment by gep13** [comment]
@JohnEricson as of right now, ChocolateyGUI does not support Chocolatey 0.9.9.x.  The latest version of Chocolatey that ChocolateyGUI has been tested on is 0.9.8.33.

While we are working on including support for the latest version of Chocolatey, we are not quite there yet.

As to how/why you have two versions of chocolatey installed, off the top of my head, I am not sure.  Any ideas @ferventcoder?

With regard to your last point, it might be worth asking @fearthecowboy or @jaykul.

**Comment by JohnEricson** [comment]
@gep13 Thanks for the quick response, that explains it. I'm new to this but very excited about what it can do, I'm familiar with apt and yum. Just a question, shouldn't ChocolateyGUI have a dependency on <= Chocolatey 0.9.8.33 in this case?

My theory is that one of the Chocolatey versions was installed by One-Get.

**Comment by gep13** [comment]
>@JohnEricson said...
Just a question, shouldn't ChocolateyGUI have a dependency on <= Chocolatey 0.9.8.33 in this case?

Yes, essentially, that is what needs to happen, and hopefully in the next few days, the fix along with a couple other things, will be corrected.

**Comment by gep13** [comment]
@JohnEricson can you confirm at what point this error message was generated for you?  i.e. what operation were you performing?  Thanks!

**Comment by JohnEricson** [comment]
@gep13 It happens direcly when I start ChocolateyGUI. The program shows up for a second with this text:
```
Retrieving installed packages...
Processing chocolatey command...
```
and then I get the error.

**Comment by gep13** [comment]
@JohnEricson Thanks for getting back to me.  I am in the process of doing a few backend changes to the ChocolateyGUI build process, but once that is done, I will be focusing on this issue.

**Comment by gep13** [comment]
Can I get anyone who is following this thread to try out a new version of ChocolateyGUI using the following command:

`choco install chocolateygui -version 0.13
.0-PullRequest0243 -source https://ci.appveyor.com/nuget/chocolateygui-36tajo4x9yei -pre`

This is a new release of ChocolateyGUI which includes the ability to use the latest Chocolatey, i.e. 0.9.9.x, and it should hopefully solve a lot of the problems that have been reported lately.

Please give it a try, and let me know if you are still running into issues.

**Comment by RichiCoder1** [comment]
I just upgraded my local chocolatey to 9.9.2 and installed this, and listing packages looks solid. Haven't touch other commands yet.

**Comment by gep13** [comment]
Good to hear.  Just trying to get a VM up that has an older version of Chocolatey installed as well, to test that side of things, but that will have to wait until tomorrow :smile_cat:
