### ISSUE TITLE
Correct Release Notes

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#231]
Make them consistent, and fill in the blanks for ones that are missing, compared to what is deployed on Chocolatey.org.

**Comment by RichiCoder1** [comment]
Ahh, this explains the tag/release spam :)

**Comment by gep13** [comment]
Ha ha, yip, that would do it.  Just a bit of house-keeping really, getting things in order before carrying on with new "stuff" :-)
