### ISSUE TITLE
Failed to insstal any app

### ISSUE THREAD

**Issue by mbnoimi** [chocolatey/ChocolateyGUI#237]
Using the cmd I can install any app without any problem but using CGUI I can't because it shows an error message (red text) flashing quickly then disappear (PowerShell window).

How can I fix this issue?

PS.
* Your project doesn't explain to users how to report an issue (debugging, logging... etc)
* I'm using: Choco 0.9.9.2 - CGUI 0.12.4 - Windows 8.1 x64
* I can browse the installed apps without any problem

**Comment by gep13** [comment]
>@mbnoimi said....
Your project doesn't explain to users how to report an issue (debugging, logging... etc)

Is the information here:

https://github.com/chocolatey/ChocolateyGUI#submitting-issues

Not enough information?

Currently, ChocolateyGUI does not work with the latest version of Chocolatey.  Please follow this issue for updates on this:

https://github.com/chocolatey/ChocolateyGUI/issues/230

For now, I am going to close this issue, as it is essentially a duplicate.  Let me know if you would like to re-open this.
