### ISSUE TITLE
User's account

### ISSUE THREAD

**Issue by mbnoimi** [chocolatey/ChocolateyGUI#238]
Hi,

I suggest to connect the GUI with user's account in [chocolatey.org](https://chocolatey.org) which is related feature to my feature suggest [on this link](https://github.com/chocolatey/chocolatey.org/issues/168).

**Comment by gep13** [comment]
This is a very interesting idea!  I like it :+1:

**Comment by LinkofHyrule89** [comment]
I really like this idea would be very helpful to restore apps after a full wipe even better then importing a list of packages to install. :)

**Comment by gep13** [comment]
In order for this to happen, some changes would need to be made to chocolatey.org, as well as ChocolateyGUI.

For now, there is an export feature in ChocolateyGUI which creating a packages.config of the current state of your machine as far as Chocolatey is concerned.  This could then be used when creating a new machine.

**Comment by LinkofHyrule89** [comment]
Well don't expect it to happen overnight but hey maybe some day :P Anyways keep up the great work.

**Comment by gep13** [comment]
Ha ha, good stuff.  I definitely think it is a good idea, so will be keeping this on the radar to see how it could be implemented :smile_cat:

**Comment by RichiCoder1** [comment]
@ferventcoder Does chocolatey.org have any sort of OAuth?

**Comment by ferventcoder** [comment]
Not currently. It's a possibility in the future, but for now, it's not high on the priority list.

**Comment by RichiCoder1** [comment]
Noted. I'll just close this for now then.
