### ISSUE TITLE
Allow config editing

### ISSUE THREAD

**Issue by DanAtkinson** [chocolatey/ChocolateyGUI#246]
It's a fairly simple requirement - to allow users to edit the options for Chocolatey inside the UI by providing them with form controls in lieu of XML.

I appreciate that the config schema is subject to change from time to time, and not maintaining parity with the structure in the GUI project could cause problems, so I think a compromise would be to:
- Provide a link in the app to edit the config manually in a text editor (or in the GUI itself).
- Allow any changes to be rolled back to the version that comes with the version of chocolatey that's currently installed.
- Create an XSD which would tell the config editor what values are editable and what value/s they can be.

Thanks!

**Comment by gep13** [comment]
This is something that I had been thinking about as well, great minds think alike! :smile_cat:

**Comment by gep13** [comment]
@RichiCoder1 am I right in saying that this is complete?

**Comment by RichiCoder1** [comment]
Ish. There is a little more work I'd like to do, but it's almost done.

**Comment by mwallner** [comment]
We can say this is done can't we @RichiCoder1

**Comment by RichiCoder1** [comment]
It's not quite done, but it's something I'm going to be reviewing today.

**Comment by gep13** [comment]
@RichiCoder1 this one is now done, right?  Or did you have other ideas about what is still required?

**Comment by RichiCoder1** [comment]
This is essential done, yes.
