### ISSUE TITLE
exception on sorting by installed packages in chocolatey

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/ChocolateyGUI#250]
v0.9.9.2

open ChocolateyGUI -> select Chocolatey -> sort by installed -->

![error](https://cloud.githubusercontent.com/assets/10271770/6846444/c899cdd4-d3be-11e4-8881-5778ad9fb422.PNG)

**Comment by gep13** [comment]
@aronovgj Thanks for the report!

Can you confirm what version of ChocolateyGUI you are using?

**Comment by gep13** [comment]
Nevermind, I can reproduce on 0.13.0.  Will take a look into this, and hopefully get a fix out.

**Comment by RichiCoder1** [comment]
The one downside of my mystical magic reflection methods. Not static verification xD

**Comment by gep13** [comment]
Raygun report https://app.raygun.io/dashboard/5o0yvb/errors/715435799 has more details about the error
