### ISSUE TITLE
Use the global config sources

### ISSUE THREAD

**Issue by bc3tech** [chocolatey/ChocolateyGUI#253]
I've added a source to my chocolatey sources, but when I launch the GUI it doesn't use those sources and I have to add it, yet again, to the app.

The app would be doubly cool if it used the choco global sources - either solely or in conjunction with its own set of sources.

**Comment by gep13** [comment]
@bc3tech thanks for the suggestion!

In all honesty, I thought that this was the way that ChocolateyGUI already worked.  Let me investigate, and I will see what can be done.

**Comment by RichiCoder1** [comment]
Likely done actually.
