### ISSUE TITLE
ChocolateyGui crashes while accessing chocolatey.org

### ISSUE THREAD

**Issue by Ziggizag** [chocolatey/ChocolateyGUI#260]
ChocolateyGui crashes while accessing chocolatey.org in case network connection is lost.

**Comment by gep13** [comment]
Thanks for getting in touch @Ziggizag!

Can you confirm what version of ChocolateyGUI you are using?  Also, would it be possible to get a complete set of steps to reproduce this problem?

Thanks!

**Comment by Ziggizag** [comment]
Hi,

This is v. 0.13.1.0.

To reproduce the isue:

Just open Choco, unplug network cable and switch from "This PC" to "Chocolatey" and "Refresh packages" if there were already cached. The result exception is below:

![choco_exception](https://cloud.githubusercontent.com/assets/2280036/7680794/5a5e9a2c-fd6a-11e4-93df-4f3038b2e0cf.png)

**Comment by gep13** [comment]
Thank you for providing these details.  I will look into this, and hopefully get a fix out there.

**Comment by Ziggizag** [comment]
Please, if feasible - be so kind and drop a line here to pass a message when new version is avalable!\.

Thanks ahead!

**Comment by gep13** [comment]
@Ziggizag I will try to remember to post here when this is resolved.

**Comment by Ziggizag** [comment]
:-)

**Comment by RichiCoder1** [comment]
Let me know if this is resolved with the most recent beta of ChocolateyGUI!
