### ISSUE TITLE
Remove duplicate config in description

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#261]
As reported by @scottisafool:

![image](https://cloud.githubusercontent.com/assets/1271146/7756443/2f65d340-fff3-11e4-8e96-8b832c15a43e.png)

**Comment by RichiCoder1** [comment]
Needs more details and very old.

**Comment by gep13** [comment]
@RichiCoder1 apologies, yes, more information definitely required here.

This is when doing the export of the list of installed packages.  When the save as dialog pops up, asking where to save the file, within the description of the "Save as type" the word config is unnecessarily duplicated.

This was be the offending line here:

https://github.com/chocolatey/ChocolateyGUI/blob/b5b05c42a60634ce29cf3e0b7acc977b2f6b3aa1/Source/ChocolateyGui/ViewModels/Controls/LocalSourceControlViewModel.cs#L209

**Comment by RichiCoder1** [comment]
Hmmm. This needs to be rethought either way. I'm going to leave this closed for now and kill of the export feature.

**Comment by gep13** [comment]
> @RichiCoder1 said...
kill of the export feature.

Hmm, that was an often asked for feature in ChocolateyGUI. I would be hesitant to remove that.

**Comment by RichiCoder1** [comment]
If we're to keep it, would probably like to map out something more official with Choco ( @ferventcoder ) or Boxstarter ( @mwrock )

**Comment by gep13** [comment]
@ferventcoder do you mean have a function within Chocolatey Client/Lib that does the actual export, and then call that from ChocolateyGUI?
