### ISSUE TITLE
Settings flyout showing twice

### ISSUE THREAD

**Issue by ScottIsAFool** [chocolatey/ChocolateyGUI#263]
Repro steps:
1. Launch app
2. Click on settings
3. Click on Sources
4. Click on settings button from 2.

Note a second settings flyout shows.

**Comment by gep13** [comment]
Thanks for reporting this :+1: 

I can confirm that this is a bug.

**Comment by RichiCoder1** [comment]
With the overhaul of the settings page, should no longer be relevent in latest develop.
