### ISSUE TITLE
Cannot search for packages AND only show those with updates

### ISSUE THREAD

**Issue by twpol** [chocolatey/ChocolateyGUI#265]
If I enter a search query _and_ select "Show Only Packages with Updates", I simply get the packages matching the search query. No filtering by available updates is performed. This would simply make sense to do given the UI.

**Comment by gep13** [comment]
@twpol thanks for filing this.  This is a known limitation of the application at the minute.

**Comment by RichiCoder1** [comment]
I'm pretty sure I resolved this issue.
