### ISSUE TITLE
Intergrate with Chocolatey API

### ISSUE THREAD

**Issue by RichiCoder1** [chocolatey/ChocolateyGUI#267]
See:
https://github.com/chocolatey/choco/pull/225

Still in flight PRs:
https://github.com/chocolatey/choco/pull/226

Tasks:
* [x] Install
* [x] Uninstall
* [x] Update
* [ ] Get Latest
* [x] List
* [x] Search
* [ ] Sort List
* [x] Chocolatey-powered sources

**Comment by RichiCoder1** [comment]
Working in progressing PR here: #282

**Comment by RichiCoder1** [comment]
Updated PR. Updated issue with task list.

**Comment by gep13** [comment]
> Updated issue with task list.

Wonder where you got that idea! :stuck_out_tongue:

**Comment by RichiCoder1** [comment]
Done. Polishing now.
