### ISSUE TITLE
missing packages in local list (This PC)

### ISSUE THREAD

**Issue by hg42** [chocolatey/ChocolateyGUI#268]
I have 89 packages installed according to clist -lo, but ChocolateyGUI shows only 87.

The first package is VisualStudio2015Community (pre), which I just installed via ChocolateyGUI.
  clist: VisualStudio2015Community 14.0.22823.20150620-RC
It is missing from the list exported by ChocolateyGUI.

The second package is windbg (probably installed via cinst).
  clist: windbg 8.59.20141003
But this one can be found in the exported list:
  export: package id="windbg" version="8.59.20141003"

**Comment by gep13** [comment]
@hg42 can you confirm which version of ChocolateyGUI you are using?

We had some issues with package names not being found correctly, but that was corrected in v0.13.0: https://github.com/chocolatey/ChocolateyGUI/issues/244

I will try to reproduce your issue just now...

**Comment by gep13** [comment]
I am not able to replicate the issue.  Having installed windbg, I can see it displayed in the list in ChocolateyGUI:

![image](https://cloud.githubusercontent.com/assets/1271146/8618873/23d64bc0-270a-11e5-95ab-e25d3d19a191.png)

I haven't tried Visual Studio, as this is a much larger install, but let me know the version number of ChocolateyGUI that you are using, and we can work from there.

**Comment by hg42** [comment]
I have current version from chocolatey, which is 0.13.1

Both names look rather simple, especially "windbg",
but "VisualStudio2015Community" contains a number (the same for the subtitle "Visual Studio 2015 Community RC").

Because windbg is listed in the exported config file, I think it may be parsed correctly, but it is not shown for some reason. (I updated my description above, because the export line looks like html)

VisualStudio2015Community is ignored completely on "This PC", but it is listed in the remote list "Chocolatey". So there seems to be a difference in processing the entries.

I'll look for them at another PC later, when I get connected to my workplace.
On my laptop I could install "Debugging Tools for Windows (windbg)" and see it in "This PC".

**Comment by gep13** [comment]
So, to be clear, you won't see an entry for just windbg in the "This PC" tab, you will see an entry for the entire title, which in this case is "Debugging Tools for Windows (windbg)".

I will try to install Visual Studio later, and see if I can figure out what is going on.

**Comment by hg42** [comment]
ok, forget windbg, the confusion came from expecting it at the position of "windbg" (between "V" and "X"), where it is when I just started CocolateyGUI. But if you click on the Name column header, you cannot get back to this sort sequence (windbg jumps to "D" then). I think this should be a three state button.

The problem with VisualStudio2015Community exists on my PC at work, too.

Perhaps you can find another package with similar naming, that doesn't show up in the list.
VisualStudio2015Community is *really* large (about 8GB).

**Comment by gep13** [comment]
>But if you click on the Name column header, you cannot get back to this sort sequence (windbg jumps to "D" then). I think this should be a three state button.

Can you raise a separate issue regarding this, with steps to reproduce and expected outcomes? Thanks!

**Comment by hg42** [comment]
vcredist2010 10.0.40219.1
 Microsoft Visual C++ 2010 Redistributable Package
works, but the number is at the end of the short name

**Comment by hg42** [comment]
easy68k v5.15.02.20141110
 Downloading easy68k 32 bit
VS2013Agents 1.5.9
 Agents for Visual Studio 2013 Installer
work, too.
btw. I started to install VS2013Agents and pressed Ctrl-C when the download started (because it was too long), but this was enough to show the package in the list. So you might be able to make your test with VisualStudio2015Community much quicker.

**Comment by hg42** [comment]
because windbg was found in the list there had to be a second difference (as I said, I had 89 items in clist, but 87 in chocogui, which was counted using the exported config).

So here it is:

PowerShell 5.0.10105-April2015Preview
 Windows Management Framework and PowerShell

doesn't show up either.

**Comment by hg42** [comment]
powershell 4.0.* (non pre) works on my laptop.
Unfortunately, I cannot install powershell 5 there (may be because the laptop is 32bit).

On my workstation, I have the pre version, but unfortunately, I see no way to replace it with the standard version.
Commands like
    cinst powershell -force --version=4.0.20141001
do nothing...

also:
c:\ -> cinst powershell -m --version=4.0.20141001
Chocolatey v0.9.9.8
Installing the following packages:
powershell
By installing you accept licenses for the packages.

Chocolatey installed 0/0 package(s). 0 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

So I cannot compare both on the same machine.

**Comment by gep13** [comment]
Hmm, I thought I was onto something there, where in it was filtering out packages that are prerelease, but that doesn't fit either.

I have just ran ```choco install nunit -pre -y``` and it is showing up happily in the list in ChocolateyGUI.

**Comment by gep13** [comment]
Ok, I have tried installing the RC of Visual Studio 2015 twice now, and it has failed each time, and I am not in a position to install the preview of PowerShell 5.  Are these the only two packages that you have seen omitted from the list on "This PC">

**Comment by hg42** [comment]
yes, these two are the only ones. And I don't have any clue, what's so different with these.
I am installing from pre all the time, so I don't think it's a problem.
However I don't see a way to list all packages from pre, so it's difficult to check. Do you?

**Comment by gep13** [comment]
Ok, I am able to reproduce the problem.  I will let you know if I come up with a reason as to why this is happening.

**Comment by gep13** [comment]
@hg42 I know why it isn't working.  We need to further expand the regular expression which is used to identify the package name and version numbers.

**Comment by hg42** [comment]
nice, I would suggest to concentrate on the space, so name=all up to space, to be safe

**Comment by gep13** [comment]
>@hg42 said...
nice, I would suggest to concentrate on the space, so name=all up to space, to be safe

That is already what the regex is doing.  It was the selection of the version number that was causing the problem.

**Comment by hg42** [comment]
I'm not familar with C#, do you simply split into two strings here? or do you use the groups of VersionString?

new Regex(@"^(?<Name>[\w\.\-]*) (?<VersionString>(\d+(\s*\.\s*\d+){0,3})(-[a-z][0-9a-z-]*)?)$");

if splitting into two strings, I would simply use (\S+)  (if those regex is perl compatible)
otherwise I would use
(?<VersionString>(\d+(\s*\.\s*\d+){0,3})(-\S+)?)

because you never know which characters may appear in this field and it's mainly separated by spaces I think.

I think, I would also ommit the "$", because the line could contain more fields or garbage at the end (e.g. a comments).

**Comment by RichiCoder1** [comment]
Let me know if this is still broke in the beta verison of chocolateygui 0.14!
