### ISSUE TITLE
sort sequence of name column

### ISSUE THREAD

**Issue by hg42** [chocolatey/ChocolateyGUI#269]
the packages are sorted according to their short names when ChocolateyGUI is started.
When you click on the "NAME" column header, the sort will use the complete name shown in the column.
When clicking again, it is sorted descending, and again it is sorted accending again.
But you never can get back to the original sort sequence.

I see three solutions:
1. remove the third sort state (short package name)
2. add the third state to the column header
3. move the short name to the start of the column entry (**prefered by me**)
      so instead of: Debugging Tools for Windows (windbg)
      use: windbg - Debugging Tools for Windows

**Comment by gep13** [comment]
This is definitely a bug, thanks for filing it!

**Comment by hg42** [comment]
btw. I would like the variant with prepending the short package name, because I often use the command line, and it's a bit difficult to match these, sometimes.

**Comment by gep13** [comment]
@hg42 yes, I think I am starting to agree with this.  I will see what I can do in this area.

**Comment by gep13** [comment]
@hg42 I believe that this issue has now been corrected.  For now, the package id is not shown on the main list view, however, you can access that information from the package details screen.
