### ISSUE TITLE
Add option to show package id column

### ISSUE THREAD

**Issue by hg42** [chocolatey/ChocolateyGUI#270]
I would like to have additional columns, e.g. the short package name and the prerelease flag.
Apart from more information, I could sort by these.
There may be additional interesting info for additional columns...

origin of this idea is
#269 "sort sequence of name column"
#268 "missing packages in local list (This PC)"

**Comment by gep13** [comment]
@hg42 whether a package version is pre-release or not is really determined by the version number, which is already included in the columns, so I don't think an additional column would serve any benefit.  What are your thoughts?

![image](https://cloud.githubusercontent.com/assets/1271146/8634393/e1d2330c-27ee-11e5-8317-a66f32011e51.png)

**Comment by hg42** [comment]
you mean, every pre package definitely has some code word in it's version, like prevoew, beta, alpha?
and every package with such a code word is definitely pre?
For me it's not clear enough.
e.g. what about this package: ShareX 10.0.0-fix, pre or not?

pre is relevant for me, to quickly see which packages may be questionable for a stable system.
I mainly use pre packages, if I want/need some new feature or a fix.
But I prefer using stable packages at least for important things, so I have a look on them.

The extra column allows sorting by this criteria.
And it's a small column (with"pre" as header)

**Comment by gep13** [comment]
>@hg42 said...
you mean, every pre package definitely has some code word in it's version, like preview, beta, alpha, pre, test,...?

exactly, yes.  That is how nuget, and therefore chocolatey, works.

**Comment by hg42** [comment]
well, that had indeed remained hidden to me 8-O
I'd still prefer a column for sorting.
But it's not so important now (with my new knowledge ;^ ))

**Comment by mikewse** [comment]
I too would like to see a column with the package short name - in some cases it is a lot clearer than the long name :-)
(Release date could also be interesting but that would be another issue I guess)

**Comment by gep13** [comment]
@hg42 this has now been implemented, and it will be released in the next version of Chocolatey GUI, 0.17.0.

**Comment by hg42** [comment]
nice, thanks
