### ISSUE TITLE
GUI installed successfully but nowhere to be found on Win10

### ISSUE THREAD

**Issue by zilexa** [chocolatey/ChocolateyGUI#272]
I have searched Start menu, %programdata%, %appdata%, Program files, Program files (x86) but I cannot find anything that could be ChocolateyGUI. When I run "choco install chocolateygui" it says it is already installed. 

Where should I find it?

**Comment by gep13** [comment]
If it indeed has installed correctly, you should find the dll's and exe in this directory:

```C:\Program Files (x86)\ChocolateyGUI```

If that directory doesn't exist, then the installation didn't work correctly.

*NOTE:* The installation of ChocolateyGUI has not been tested on Windows 10 yet.

**Comment by zilexa** [comment]
It must be related to Win10. I just tried to uninstall it, that gave me errors:
http://pastebin.com/V1HMjCqA

Also I just noticed there are 2 packages related to a Choco GUI: Chocolatey Explorer and a Chocolatey GUI. Will these projects merge into one awesome GUI? :)

**Comment by gep13** [comment]
Where are you seeing ChocolateyExplorer?

**Comment by gep13** [comment]
You are seeing that error message in the uninstallation script because the application never actually got installed :cry:  We will need to tidy that up.

**Comment by gep13** [comment]
Ah, you are referring to this:

https://chocolatey.org/packages/ChocolateyExplorer

Yes, I believe that James has stopped working on that project, and does indeed contribute to this project.

ChocolateyGUI is the official Chocolatey GUI Client, although there are others.

**Comment by zilexa** [comment]
Yes I am sorry for the confusion, in my search for info about GUI I found the Explorer website :)

With Win10 I decided to only install apps via 1 batchfile using Choco. I used to create unattended windows installation disks and this is soo much easier! In some cases it can be difficult to figure out installation arguments to not install specific items, associate file types and get rid of desktop shortcuts but other then that it works fine. Just noticed choco uninstall does not actually uninstall the package (its still installed in Windows). But I suppose thats a work in progress. Keep up the amazing work!

**Comment by gep13** [comment]
>@zilexa said...
Just noticed choco uninstall does not actually uninstall the package (its still installed in Windows). But I suppose thats a work in progress

At the minute, there is a reliance on existence of a chocolateyUninstall.ps1 file to do the uninstallation.  However, there is a beta feature called the autoinstaller, which will remove the application from Windows, even though there is no uninstall script.  You can enable this feature by following the instructions here:

https://github.com/chocolatey/choco/wiki/CommandsFeature
