### ISSUE TITLE
Chocolatey GUI doesn't save user's preferred window position, size and state

### ISSUE THREAD

**Issue by ADTC** [chocolatey/ChocolateyGUI#275]
I'm on Windows 7. ChocolateyGUI does not remember my preferred window position, size or maximized state. The first time I ran ChocolateyGUI, I moved and resized the window to workaround bug #276. However, ChocolateyGUI didn't restore its position and size on second run, and it always reverts to the default behavior on running again.

**Comment by gep13** [comment]
Thanks for the suggestion! :+1:

**Comment by ADTC** [comment]
You're welcome. In addition to the feature request, this is also a bug report for a bug that's affecting a fresh install of ChocolateGUI (in a system where it was never installed, or the previous installation has been wiped completely). Hope you know what I mean :smile: Thanks!

**Comment by gep13** [comment]
Would it be possible you to file the bug separately?  That way we can track them both? Thanks!

**Comment by ADTC** [comment]
Done! I have revised this issue as well to be purely about the feature request.

**Comment by gep13** [comment]
@ADTC I have just pushed a new version to the MyGet feed that should address this feature request.  Please give it a try, and let us know how you get on with it.

**Comment by ADTC** [comment]
@gep13 ah thank you, this has been on for 2 years though. I'm kinda not using it right now. Sorry.

**But really, thank you so much for addressing the request! I appreciate it.** I might just give it a try for old times' sake.

**Comment by TheVakman** [comment]
I appreciate this change! I can confirm it is working for me on 0351.

**Comment by gep13** [comment]
@ADTC I completely understand.  This project has been neglected, but it is definitely making a resurgence 😄 

@TheVakman great, thank you for confirming!
