### ISSUE TITLE
Inform user and update documentation with installation folder

### ISSUE THREAD

**Issue by valentijnscholten** [chocolatey/ChocolateyGUI#277]
Hi,

Could be that I'm just blind today, but after installation, I had to spent 5 minutes googline to find out where the GUI was installed. When the GUI is installed, there was no feedback, not even a succes or failure message, let alone any information about any shortcuts being created or where to find the installation or how to start it.

Would be nice to provide some more feedback to users. It can help new users to get started easily with a smooth experience.

Valentijn

**Comment by gep13** [comment]
Thanks for reaching out!

Is ```C:\Program Files (x86)\ChocolateyGUI``` not a reasonably "normal" installation path?

Also, the ChocolateyGUI installer adds a Start Menu shortcut on installation, so you should be able to hit the Start Button, type ChocolateyGUI and it will be immediately available in the list.

**Comment by valentijnscholten** [comment]
Hmm totally missed that. I guess I saw some earlier reports that there was no start menu entry, so didn't look for it. Oops.

**Comment by gep13** [comment]
I take your point about adding some documentation about this though.

**Comment by valentijnscholten** [comment]
And maybe some kind of message indicating the installation was completed succesfully or something, or did I miss that one as well?

**Comment by gep13** [comment]
Did you use Chocolatey to install ChocolateyGUI?

**Comment by valentijnscholten** [comment]
Yes, so for the GUI it's OK.

**Comment by RichiCoder1** [comment]
Closing this for now.
