### ISSUE TITLE
Blog Post Links on About Page Broken

### ISSUE THREAD

**Issue by Vaquero84** [chocolatey/ChocolateyGUI#279]
The following links on the about page are broken:
- All new ChocolateyGUI (http://blogs.lessthandot.com/index.php/SysAdmins/OS/Windows/all-new-chocolateygui/)
- Making a chocolatey package for ChocolateyGUI (http://blogs.lessthandot.com/index.php/DesktopDev/MSTech/making-a-chocolatey-package/)
- ChocolateyGUI (http://blogs.lessthandot.com/index.php/DesktopDev/MSTech/chocolatey-gui/)

**Comment by gep13** [comment]
This was also just reported here:

https://github.com/chocolatey/ChocolateyGUI/issues/280

I will dig into this, and let you know what I find out.

**Comment by RichiCoder1** [comment]
Looks like all the blog posts have been removed. How do you want to handle this @gep13 ?

**Comment by gep13** [comment]
@RichiCoder1 yeah, I spoke to Chrissie about this.  He didn't go into details, but basically he said that all his content had been removed from their site, and that is wasn't likely to come back.  I think we should just go ahead and remove the links.  They were really there for historical reasons.  Much of the content wasn't really up to date information anyway, so I don't think we are loosing anything.

**Comment by gep13** [comment]
via https://github.com/chocolatey/ChocolateyGUI/commit/abca4c0839f7cb46440c751abcc03a7af1e66436

**Comment by gep13** [comment]
@Vaquero84  forgot to say...  Thanks for pointing this out :+1:

**Comment by pyhedgehog** [comment]
That's exactly when time machine would be useful:
 * http://web.archive.org/web/20150318182314/http://blogs.lessthandot.com/index.php/sysadmins/os/windows/all-new-chocolateygui/
 * http://web.archive.org/web/20150318200849/http://blogs.lessthandot.com/index.php/desktopdev/mstech/making-a-chocolatey-package/
 * http://web.archive.org/web/20150319000941/http://blogs.lessthandot.com/index.php/desktopdev/mstech/chocolatey-gui/

**Comment by gep13** [comment]
@pyhedgehog thanks for the links.  We might want to take the contents and put them somewhere for reference.
