### ISSUE TITLE
About > Making a chocolatey package for ChocolateyGUI > 404 not found

### ISSUE THREAD

**Issue by esamo** [chocolatey/ChocolateyGUI#280]
Hey.

1) We are directed to
http://blogs.lessthandot.com/index.php/DesktopDev/MSTech/making-a-chocolatey-package/

However the page is no longer available.

2) I dunno where to put it - "Smart Defrag" (part of Advanced SystemCare) package could be added do choco by someone.

---

Regards & respect

**Comment by gep13** [comment]
Thanks for the heads up, I will look into this.

**Comment by gep13** [comment]
@esamo forgot to say...  Thanks for pointing this out :+1:
