### ISSUE TITLE
Compilation Warnings

### ISSUE THREAD

**Issue by wjk** [chocolatey/ChocolateyGUI#281]
On my machine, using a stock install of Visual Studio 2015 Community, building ChocolateyGUI finishes with 42 warnings. The warnings are about one of these two causes:

1. `CLSCompliantAttribute`: CS3001, CS3002, CS3009, CS3016. These are all warnings about CLS-compliant code using or inheriting from classes containing non-CLS-compliant code. What is the reasoning of placing `[assembly: CLSCompliant(true)]` in `AssemblyInfo.cs`? Is it OK to remove this?
2. `async` methods: CS4014 is raised wherever an `async` method is called that is not immediately `await`ed. Also, CS1998 is raised wherever there is an `async` method without an `await` statement in it. In my opinion, these are two of the most spurious compiler warnings I have ever seen, as both of these use-cases are valid programming patterns. Is it OK to tell Visual Studio to not emit these warnings?

**Comment by RichiCoder1** [comment]
Pretty much no one cares about CLS compliancy, so yes, it would be safe to remove.

As for the later, I would *not* want to turn those off globally. Maybe on a case by case basis.

**Comment by gep13** [comment]
These are likely a side effect of the the enabling of Code Analysis on the project.  I would need to refresh my memory of these in order to remember what was done, and why.

Like @RichiCoder1 I would want to disable any warning globally.

**Comment by RichiCoder1** [comment]
Note: I killed of most these warning is my choco lib branch.

**Comment by gep13** [comment]
When you say killed, what exactly do you mean?  i.e. have you suppressed the warnings?  Corrected them? Something else? :smile_cat:

**Comment by RichiCoder1** [comment]
I attempted to take the most appropriate action. In the case of CLS I removed it. I fixed one legit warning. And I silenced on a case by case basis the async warnings where we were intentionally doing the behavior it warned against.

**Comment by gep13** [comment]
Coolio, just wanted to check :smile_cat:

**Comment by RichiCoder1** [comment]
I think this was actually done.
