### ISSUE TITLE
Fix AppVeyor Build

### ISSUE THREAD

**Issue by RichiCoder1** [chocolatey/ChocolateyGUI#283]
Appveyor build is currently failing. It looks like the Resharper DupFinder is not compatible with .Net FX 4.6 and fail. I sent an email to jetbrains asking them to bump their CLI tools package version to 9.2, but we have to find an alternative route to retrieve the most recent tool.

**Comment by gep13** [comment]
@RichiCoder1 have you actually changed the target framework version, or is it just that you opened the Solution in VS2015 that is now causing the problem?

How have you reached out to JetBrains by the way?  I have been in contact with the person maintaining the packages, like ReSharper before, so I can reach out again if you want.

The new version can be downloaded here:

https://www.jetbrains.com/resharper/features/command-line.html

So we could always pull that down as part of the build.

**Comment by RichiCoder1** [comment]
It's been a recent issue w/ AppVeyor actually. My machine works perfectly.

See the last line of: https://ci.appveyor.com/project/GaryEwanPark/chocolateygui/build/0.14.0-PullRequest.282+17%20(Build%20337)

> How have you reached out to JetBrains by the way? I have been in contact with the person maintaining the packages, like ReSharper before, so I can reach out again if you want.

I just used the Contact Maintainers feature :). If you can do better, please do!

>https://www.jetbrains.com/resharper/features/command-line.html

>So we could always pull that down as part of the build.

I was thinking that too, but it'd be nice to see if we can get the choco package updated first.

**Comment by gep13** [comment]
Ah, hold on...

In order to build Visual Studio 2015 projects, we need to use a different base image:

http://www.appveyor.com/docs/installed-software#visual-studio-2015

**Comment by RichiCoder1** [comment]
Well, I fixed the CLI install. It's now using 2015. Buuut there was another weird error that got thrown.

That being said, would not be a terrible idea to also set the base image to VS 2015.

**Comment by RichiCoder1** [comment]
Aaand I think I made it worse. *sighs*

**Comment by RichiCoder1** [comment]
Nope. Known issue with inspect code. https://youtrack.jetbrains.com/issue/RSRP-447361

**Comment by gep13** [comment]
According to that issue, this is fixed in version 10 of the CLI tools.  This is available as a pre-release on nuget, so might be worth giving this a try as well:

https://www.nuget.org/packages/JetBrains.ReSharper.CommandLineTools/10.0.20151002.132054-EAP3

**Comment by gep13** [comment]
@RichiCoder1 so what did you do here?  did you update the tools version, and all worked?

**Comment by RichiCoder1** [comment]
To be honest? It just worked.

**Comment by gep13** [comment]
>@RichiCoder1 said...
To be honest? It just worked.

Don't you just love it when that happens :-)
