### ISSUE TITLE
Settings Dialog Visual Bug

### ISSUE THREAD

**Issue by wjk** [chocolatey/ChocolateyGUI#284]
I noticed that the Settings dialog can be opened twice, creating an odd visual glitch. (See attached screenshot.) Here's how to reproduce:

1. Open ChocolateyGUI
2. Click Settings, then Sources
3. Click Settings again.

Note that the Settings button will close the Settings pane if clicked twice, but is apparently not aware of the Sources dialog.

![ChocolateyGUI Bug](https://cloud.githubusercontent.com/assets/1915951/10254719/7bfb3c3e-6913-11e5-94fc-e8287b6924a3.png)

**Comment by wjk** [comment]
Unfortunately, I forgot to check the list of existing issues before filing this one. This is a duplicate of #263. Sorry to waste your time.

**Comment by gep13** [comment]
Not a problem at all, thanks!
