### ISSUE TITLE
Add UI padding

### ISSUE THREAD

**Issue by wjk** [chocolatey/ChocolateyGUI#285]
I noticed that some of the controls in ChocolateyGUI are packed closely against each other, to the point where the edges of the controls are touching. (See attached screenshots for examples.) In my opinion, the UI would look better if there was some padding between the edges of the controls. I can submit a PR if desired.

![ChocolateyGUI Buttons](https://cloud.githubusercontent.com/assets/1915951/10254759/bb64df56-6913-11e5-82d2-dfe628b1fd21.png)
![ChocolateyGUI Buttons](https://cloud.githubusercontent.com/assets/1915951/10254758/bb649afa-6913-11e5-84f6-663d3d6aa5d7.png)

**Comment by gep13** [comment]
@wjk yip, happy to accept a PR on this. Thanks!

**Comment by RichiCoder1** [comment]
You literally have no idea how much both of those you circled have bothered me. Def accepting PRs and, failing that, will probably grab this myself.

**Comment by gep13** [comment]
> You literally have no idea how much both of those you circled have bothered me. Def accepting PRs and, failing that, will probably grab this myself.

Happy to take some responsibility for this. I literally have NO design skills!  Pushing the buttons together seemed like a good idea to me :smile_cat:

**Comment by MikeFoden** [comment]
@wjk did you end up getting this working? If not, I would love to have a try at solving this one.

**Comment by gep13** [comment]
@MikeFoden A PR for this issue has already been submitted, and pulled into the develop branch.  We haven't had a chance to release the next version of ChocolateyGUI, but if you are interested, you should be able to install the latest development version of ChocolateyGUI from our MyGet feed.  The instructions are on the readme.md of this project.

**Comment by MikeFoden** [comment]
@gep13 Ahh I see, I saw commits but couldn't find the pull request sorry!

**Comment by gep13** [comment]
@MikeFoden you are right, there wasn't a link back here from the PR.  I have corrected this now.  This issue will be closed once the next version is released.

**Comment by RichiCoder1** [comment]
I'm being naughty and closing issues before 0.14 is offically released, so I'm going to close this one out for now. I will make sure we're very vocal once it's actually released.

**Comment by gep13** [comment]
>@RichiCoder1 said...
I'm being naughty and closing issues before 0.14 is offically released

Personally, I think that this is ok.  As long as they are assigned to a milestone, and that milestone is still open, then I think this is a valid workflow.
