### ISSUE TITLE
Invalid path on launching ChocolateyGui

### ISSUE THREAD

**Issue by gueland** [chocolatey/ChocolateyGUI#287]
I have recently installed the chocolateygui (from powershell) in Windows 10 Technical Preview 10547 and when I try to launch it it gives me the following error.
![chocolateygui launch error](https://cloud.githubusercontent.com/assets/14985708/10292862/1e1cdc56-6b77-11e5-8912-e9f26a85d89f.jpg)
Can you help?

**Comment by gep13** [comment]
In the .config file for ChocolateyGUI, what is the value of the chocolatyInstall variable?  Does this match with where chocolatey is installed on your system?

**Comment by gueland** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="chocolatey" type="ChocolateyGui.ChocoConfigurationSection, ChocolateyGui"/>
    <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler, log4net"/>
    <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
      <section name="ChocolateyGui.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false"/>
    </sectionGroup>
  </configSections>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-2.6.9.0" newVersion="2.6.9.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-2.6.9.0" newVersion="2.6.9.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Edm" publicKeyToken="31bf3856ad364e35" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-5.6.2.0" newVersion="5.6.2.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Spatial" publicKeyToken="31bf3856ad364e35" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-5.6.2.0" newVersion="5.6.2.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.OData" publicKeyToken="31bf3856ad364e35" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-5.6.2.0" newVersion="5.6.2.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Reactive.Interfaces" publicKeyToken="31bf3856ad364e35" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-2.2.5.0" newVersion="2.2.5.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Reactive.Core" publicKeyToken="31bf3856ad364e35" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-2.2.5.0" newVersion="2.2.5.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Reactive.Linq" publicKeyToken="31bf3856ad364e35" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-2.2.5.0" newVersion="2.2.5.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <log4net>
    <root>
      <level value="DEBUG"/>
      <appender-ref ref="FileAppender"/>
      <appender-ref ref="DebugFileAppender"/>
    </root>

    <appender name="DebugFileAppender" type="log4net.Appender.RollingFileAppender">
      <filter type="log4net.Filter.LevelMatchFilter">
        <levelToMatch value="DEBUG"/>
      </filter>
      <file value="${APPDATA}\\ChocolateyGUI\\Logs\\Chocolatey.gui.debug"/>
      <appendToFile value="true"/>
      <rollingStyle value="Size"/>
      <maxSizeRollBackups value="2"/>
      <maximumFileSize value="10MB"/>
      <staticLogFileName value="true"/>
      <param name="ImmediateFlush" value="true"/>
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date [%thread] %level %logger [%ndc] - %message%newline"/>
      </layout>
    </appender>

    <appender name="FileAppender" type="log4net.Appender.RollingFileAppender">
      <filter type="log4net.Filter.LevelRangeFilter">
        <levelMin value="INFO"/>
        <levelMax value="FATAL"/>
      </filter>
      <file value="${APPDATA}\\ChocolateyGUI\\Logs\\Chocolatey.gui.log"/>
      <appendToFile value="true"/>
      <rollingStyle value="Composite"/>
      <datePattern value="yyyy-MM-dd"/>
      <maximumFileSize value="1MB"/>
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date [%thread] %-5level %logger [%ndc] - %message%newline"/>
      </layout>
    </appender>
  </log4net>
  <userSettings>
    <ChocolateyGui.Properties.Settings>
        <setting name="sources" serializeAs="Xml">
            <value>
                <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                    <string>Chocolatey|https://chocolatey.org/api/v2</string>
                </ArrayOfString>
            </value>
        </setting>
        <setting name="currentSource" serializeAs="String">
            <value>Chocolatey</value>
        </setting>
    </ChocolateyGui.Properties.Settings>
  </userSettings>
<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5"/></startup></configuration>

**Comment by gep13** [comment]
@gueland  Actually, sorry, I sent you on a wild goose chase there...

Can you check for the existence of an environment variable called "chocolateyInstall".  What is it's value, and does that path exist on your machine?

**Comment by gueland** [comment]
No, I don't. The only variable is ChocolatelyPath and the value is C:\Chocolately , which does exist on my machine.

**Comment by gep13** [comment]
@gueland hmm, this is very strange.  How did you install Chocolatey?  This variable should have been created, and is required in order for both Chocolatey and ChocolateyGUI to function correctly.

**Comment by gueland** [comment]
I installed it using the git version of the command line (using powershell) package manager.

**Comment by gep13** [comment]
Sorry, I am really not sure if I follow what you mean.  Can you list out all the steps that you have taken? Thanks!

**Comment by Sekanato** [comment]
I have same issue. Installed through OneGet with Chocolatey as a provider(e.g.: `Install-Package chocolateygui`). Getting exact error on launch.

**Comment by RichiCoder1** [comment]
How did you install chocolatey itself though?

**Comment by Sekanato** [comment]
By adding it as a provider for OneGet.

**Comment by RichiCoder1** [comment]
I honestly don't know if we work with Chocolatey installed via OneGet. @ferventcoder ?

**Comment by ferventcoder** [comment]
You won't need to - Once you have the lib implemented, you have a valid version of a Chocolatey client just as a GUI (I did not read this entire convo).

**Comment by ferventcoder** [comment]
And we will have the official Chocolatey OneGet provider available coming in the next couple of months, until then consider it a CTP and YMMV.

**Comment by ferventcoder** [comment]
Installing the ChocolateyGUI through PowerShell PackageManagement with the Chocolatey provider, ***that*** is a thing and will work when the official provider is released. HTH.

**Comment by RichiCoder1** [comment]
Good to know. Let me know if this is still broke in the beta version of ChocolateyGUI 0.14!
