### ISSUE TITLE
Package Details are not loaded if selected by context-menu->Details

### ISSUE THREAD

**Issue by rob100** [chocolatey/ChocolateyGUI#290]
The package details (like created, last updated etc.) are not loaded if you select an package, right-click on it and select "Details". The behavior works fine if you double-click on the package. I already prepared a small bug fix for this issue for PackageViewModel.cs. If you confirm this, I can open a pull request.

**Comment by gep13** [comment]
@rob100 yes, i have just replicated this issue.  Thanks for reporting it!  If you are happy to work on a PR to correct, we will gladly accept it, thanks!
