### ISSUE TITLE
Scroll to top of packages list when going to a new page

### ISSUE THREAD

**Issue by SarreqTeryx** [chocolatey/ChocolateyGUI#292]
either fix the paginated view so is pops back to the top after ”Next” or "Previous” are pressed, or, even better, move to a continuous list.

**Comment by Sixthhokage1** [comment]
Adding my support for this, preferably the continuous list.

**Comment by gep13** [comment]
@RichiCoder1 what are your thoughts around this one?

**Comment by RichiCoder1** [comment]
Should actually be pretty easy. I just need to do it. Agree that this should be the default behavior.

**Comment by RichiCoder1** [comment]
Resolved in latest develop.
