### ISSUE TITLE
please add a category view

### ISSUE THREAD

**Issue by SarreqTeryx** [chocolatey/ChocolateyGUI#293]
to make it easier to find packages by app type

**Comment by RichiCoder1** [comment]
I'm closing this for now as Chocolatey doesn't have a concept of categories. I'll recommend making an issue in the chocolatey/choco if you'd like this added.

**Comment by pyhedgehog** [comment]
Well I think author referenced "tags" as "categories". At least "chocolatey.org" has such concept.

**Comment by RichiCoder1** [comment]
Tags and categories are quite different things. The form suggests "tags" or metadata, while the latter suggests curation. We do plan to improve tag support, however.
