### ISSUE TITLE
Missing Code Signature

### ISSUE THREAD

**Issue by sebastian-philipp** [chocolatey/ChocolateyGUI#295]
Hi,

![chocoguisigning](https://cloud.githubusercontent.com/assets/2574405/11438011/26f70172-94f2-11e5-86d5-0ccaf3519908.png)

this is especially bad for apps that want to change the system configuration, because I really have no way to tell if someone replaced the executable with something malicious.

**Comment by Daniel15** [comment]
You can get an inexpensive code signing cert for open-source projects from Certum: https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml. It's 14 Euro per year.

**Comment by ferventcoder** [comment]
We'll be doing this for 0.15.0 with our Chocolatey Software authenticode cert.

**Comment by TheVakman** [comment]
@ferventcoder How far out are we from the official 0.15 release with the executable signed?

**Comment by ferventcoder** [comment]
Not that far. Working on this now.

**Comment by ferventcoder** [comment]
This is actually delaying the release now, as the the WixProj wants to rebuild ChocolateyGui.exe after I've signed it.

**Comment by gep13** [comment]
@ferventcoder This should go back to the 0.15.0 milestone, right?

**Comment by ferventcoder** [comment]
Yes, apologies.

**Comment by TheVakman** [comment]
Thanks for the updates and I see that it's closed now too!

**Comment by winnieXY** [comment]
Hey, 
I've problems with excution of ChocolateyGUI right now related to the certificate.

It's stated that the certificate is revoked by the issuer, see screenshot below.

![image](https://user-images.githubusercontent.com/6831918/31861117-6eb8bac4-b727-11e7-8834-cf5cf474b6b9.png)

What's wrong here?

**Comment by ferventcoder** [comment]
This has moved over to #505 (@winnieXY opened).
