### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by TravelingTechGuy** [chocolatey/ChocolateyGUI#297]
Since last week, after some MS update to VS2008 runtime (I assume), I'm getting the attached runtime error when starting the application:
![chocogui-error](https://cloud.githubusercontent.com/assets/492322/11792794/c9a79c98-a25c-11e5-8309-8a35da065982.png)

**Comment by TravelingTechGuy** [comment]
Updated to 0.13.2 - same error.

**Comment by gep13** [comment]
@TravelingTechGuy this was not an issue that was tackled in the 0.13.2 release.  Once it is looked at and corrected, you will see a milestone assigned to the issue.

**Comment by rob100** [comment]
I got this error message too after installing boost with the following command:
`choco install boost-x86-msvc2013`
After uninstalling the package and the installed dependency (boost-x86-msvc2013.install) the error disappears too.

**Comment by RichiCoder1** [comment]
Let me know if this is still broke in the beta version of ChocolateyGUI 0.14!

**Comment by Sixthhokage1** [comment]
Same error happens on launching the beta version.

**Comment by RichiCoder1** [comment]
This exact error? Odd.

**Comment by RichiCoder1** [comment]
I'm about 100% sure this should be solved now in latest.

**Comment by TravelingTechGuy** [comment]
Just installed latest version (0.13.2) and got this:
<img width="695" alt="capture" src="https://cloud.githubusercontent.com/assets/492322/21296100/4a55fea0-c518-11e6-92cb-7d09f0574131.PNG">

Uninstalling...

**Comment by RichiCoder1** [comment]
I should clarify that this is resolved in the latest develop. Official release is still pending.

**Comment by TravelingTechGuy** [comment]
Gotcha. Maybe the issue should be kept open until the new version is officially released?

**Comment by gep13** [comment]
@TravelingTechGuy we typically close an issue once the fix has been merged into the develop branch.  All issues are associated with a milestone, in this case 0.15.0 (https://github.com/chocolatey/ChocolateyGUI/milestone/6) when that is closed, it will be available for installation through normal channels.
