### ISSUE TITLE
Unable to add source using UAC path

### ISSUE THREAD

**Issue by eoyslebo** [chocolatey/ChocolateyGUI#299]
choco source add -n samba -s "\\smbserver\nuget" works in powershell, but the source does not show up in ChocolateyGUI.

Trying to add the source manually in ChocolateyGUI settings, I get the error message "Failed to query source."

**Comment by RichiCoder1** [comment]
Let me know if this is still broke in the beta version of ChocolateyGUI 0.14!

**Comment by episource** [comment]
For me v0.14.0-unstable0002 fails to query a repository located on a network share. I use the GUI to add the source "\\<server>\pub\my-chocolatey\_repo". It fails with error message "Failed to query source." Chocolatey istself has no problem querying this repository.

**Comment by urmel1960** [comment]
Using Version 0.13.2.0 I can not add any UNC path as a source. I have no idea why this issue is closed .. ??

**Comment by mwallner** [comment]
@urmel1960 - as @RichiCoder1 pointed out this should be fixed with the current prerelease version 0.14.x - 0.13.x won't get a fix for that. If you have the possibility to upgrade, please do - you'll find 0.14/0.15.x much more usable/stable than the old version. :-)

**Comment by urmel1960** [comment]
@mwallner - thanks for your comment - can you please advise where to get 0.14/0.15x ?

**Comment by mwallner** [comment]
as pointed out in https://github.com/chocolatey/ChocolateyGUI/blob/develop/README.md - you could go with the myget feed:
`choco install chocolateygui --source https://www.myget.org/F/chocolateygui/ --pre`

**Comment by urmel1960** [comment]
The package is not listed there - even if it is pointed out ... :-(
