### ISSUE TITLE
Erroneous date format

### ISSUE THREAD

**Issue by Akibo95** [chocolatey/ChocolateyGUI#301]
The dates in ChocolateyGUI appear to be displayed with the day and the month the wrong way around. For example, jdk8 was created on 2 September, 2016; obviously, this is in the future. It was last updated on the 2nd day of the 15th month, 2016.

How to replicate: search for jdk8 in ChocolateyGUI. Right-click on "Java SE" and click Details. Observe the dates in the left hand column.

Possible solution: use DateTime.ToString with the local culture which simultaneously fixes the bug and internationalises the program.

**Comment by RichiCoder1** [comment]
:+1:

**Comment by gep13** [comment]
@RichiCoder1 using a non-ambiguous DateTime Format string similar to 02-Jun-2016 would also alleviate this problem.

**Comment by RichiCoder1** [comment]
Should be solved in latest develop. Let me know if that's not the case.
