### ISSUE TITLE
diasymreader.dll

### ISSUE THREAD

**Issue by tom2222** [chocolatey/ChocolateyGUI#304]
Hi, 
when i start chocolateygui I always get the follwing error diasymreader.dll is either not designed to run on Windows or it contains an error , is it because of Windows 10? I tried compatibility mode but doesnt help.   The program does start but does show error all the time, also I run it as administrator.

This is the popup i get
![choco](https://cloud.githubusercontent.com/assets/16387305/14243406/acbc5af0-fa55-11e5-9474-ff570a0c6c90.JPG)

Thanks for the help.

**Comment by RichiCoder1** [comment]
Let me know if this is still broke in the beta version of ChocolateyGUI 0.14!
