### ISSUE TITLE
Installed Packages Not Properly Handled

### ISSUE THREAD

**Issue by wjk** [chocolatey/ChocolateyGUI#307]
I just updated my fork of ChocolateyGUI after ~43 commits to upstream, and built and run the program. When I view the details of a locally installed package, the "Update" (if applicable) and "Remove" buttons are not shown. Instead, I see an "Install" button that does nothing when clicked. (The window dims as if the PowerShell overlay would appear, but it never does and the dimming disappears less than a second later.)

A few weeks ago I installed Chocolatey `0.9.10-beta1-329-g3b447fc3`. I suspect a version incompatibility is the cause of this problem.

**Comment by RichiCoder1** [comment]
Could you pull again and let me know if you're still seeing issues? If so, could you provide screenshots or steps to reproduce? Thanks!

**Comment by wjk** [comment]
After I did a pull and merge (my HEAD is now `e89a9dcc`), the ChocolateyGUI behavior described above does not change. Furthermore, when I actually _click_ the erroneously displayed Install button, the PowerShell overlay appears, displays “Installing Package” and then hangs indefinitely. Screenshots forthcoming.

**Comment by wjk** [comment]
Here are the screenshots:

![Screenshot 1](https://cloud.githubusercontent.com/assets/1915951/15794550/aa8e6d98-29b9-11e6-8ac3-6a58c1c42d86.png)
![Screenshot 2](https://cloud.githubusercontent.com/assets/1915951/15794554/b0506a74-29b9-11e6-9895-2896e66f614e.png)

**Comment by RichiCoder1** [comment]
You don't see it, but it's actually throw an exception. Still bad behavior either way :|. Will look into it.

**Comment by RichiCoder1** [comment]
AutoHotKey is installed already is what you're also saying, yes?

**Comment by wjk** [comment]
Yes, AHK is already installed. It is simply the package I chose as an example.

**Comment by RichiCoder1** [comment]
Could you screenshot the results of `choco list -lo AutoHotkey`?

**Comment by RichiCoder1** [comment]
NVM, I can reproduce. Odd

**Comment by wjk** [comment]
Yes, Update and Reinstall do appear in the right-click menu, but when I click Update, I get the same “Updating package”-and-hang behavior I saw before.

**Comment by RichiCoder1** [comment]
Try the latest develop and let me know if you still have issues. Progress is still a little derpy so it won't do much visibly until it completes the choco operations.

**Comment by wjk** [comment]
Yep, that did it! Works like a charm. Thank you so much!

**Comment by RichiCoder1** [comment]
Awesome! Let me know if you run into any other issues. I want to make sure that 0.14 is a high quality release.
