### ISSUE TITLE
Update Screenshot in README

### ISSUE THREAD

**Issue by wjk** [chocolatey/ChocolateyGUI#315]
The title really says it all. Now that #313 was merged, the screenshot in `README.md` is now out-of-date. Could it please be updated to reflect the new theme? Thanks!

**Comment by gep13** [comment]
@RichiCoder1 just as a note as well, if we are updating screenshots, there is also these here:

https://github.com/chocolatey/ChocolateyGUI/tree/develop/docs/Screenshots

**Comment by gep13** [comment]
@wjk thanks for reporting this!
