### ISSUE TITLE
Unhandled Exception Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '[54].Source', line 1, position 4096.

### ISSUE THREAD

**Issue by Opensourcecommunitydevelopment** [chocolatey/ChocolateyGUI#316]
`---------------------------
Unhandled Exception
---------------------------
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '[54].Source', line 1, position 4096.

   bei Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)

   bei Newtonsoft.Json.JsonTextReader.ParseString(Char quote)

   bei Newtonsoft.Json.JsonTextReader.ParseValue()

   bei Newtonsoft.Json.JsonTextReader.Read()

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType, IDictionary`2& extensionData)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   bei Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

   bei Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)

   bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)

   bei ChocolateyGui.Services.BasePackageService.PackageConfigEntries()

   bei ChocolateyGui.Services.BasePackageService.PopulatePackages(IPackageViewModel packageInfo, ICollection`1 packages)

   bei ChocolateyGui.Services.BasePackageService.<EnumerateLocalPackagesAndSetCache>d__38.MoveNext()

--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---

   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   bei ChocolateyGui.Services.CSharpChocolateyPackageService.<GetInstalledPackages>d__2.MoveNext()

--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---

   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   bei ChocolateyGui.ViewModels.Controls.LocalSourceControlViewModel.<LoadPackages>d__41.MoveNext()

--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---

   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   bei ChocolateyGui.ViewModels.Controls.LocalSourceControlViewModel.<Loaded>d__35.MoveNext()

--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---

   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()

   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   bei System.Windows.Threading.DispatcherOperation.Invoke()

   bei System.Windows.Threading.Dispatcher.ProcessQueue()

   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   bei System.Windows.Application.RunDispatcher(Object ignore)

   bei System.Windows.Application.RunInternal(Window window)

   bei ChocolateyGui.App.Main()
---------------------------
OK   
---------------------------
`

That appears at Start. Tried Force install many times but it is New and fresh. What ist wrong? Config is Default. Only source is choco Default repo

> PS C:\> choco install ChocolateyGUI -source https://www.myget.org/F/chocolateygui/ -pre
Installing the following packages:
ChocolateyGUI
By installing you accept licenses for the packages.
ChocolateyGUI v0.13.2 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

Chocolatey installed 0/1 package(s). 0 package(s) failed.
 1 package(s) had warnings.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Warnings:
 - chocolateygui

**Comment by RichiCoder1** [comment]
@Opensourcecommunitydevelopment Try pulling the latest again. 0.14-unstable0002 is the latest and shouldn't have these issues.

**Comment by Opensourcecommunitydevelopment** [comment]
sadly, the Upgrade did Not help. Same Problem.

2016-07-01 17:54:10,269 [WARN ] - 162 packages installed.
2016-07-01 17:54:10,270 [DEBUG] - --- End of List ---
2016-07-01 17:54:10,271 [DEBUG] - Exiting with 0
C:\>choco upgrade ChocolateyGUI -source https://www.myget.org/F/chocolateygui/ -pre
Upgrading the following packages:
ChocolateyGUI
By upgrading you accept licenses for the packages.
You have ChocolateyGUI v0.13.2 installed. Version 0.14.0-unstable0002 is available based on your source(s).

ChocolateyGUI v0.14.0-unstable0002
 Installing ChocolateyGUI...
 ChocolateyGUI has been installed.
 The upgrade of chocolateygui was successful.

Chocolatey upgraded 2/2 package(s). 0 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
`---------------------------
Unhandled Exception
---------------------------
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '[54].Source', line 1, position 4096.

   bei Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)

   bei Newtonsoft.Json.JsonTextReader.ParseString(Char quote)

   bei Newtonsoft.Json.JsonTextReader.ParseValue()

   bei Newtonsoft.Json.JsonTextReader.Read()

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType, IDictionary`2& extensionData)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   bei Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

   bei Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)

   bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)

   bei ChocolateyGui.Services.BasePackageService.PackageConfigEntries()

   bei ChocolateyGui.Services.BasePackageService.PopulatePackages(IPackageViewModel packageInfo, ICollection`1 packages)

   bei ChocolateyGui.Services.BasePackageService.<EnumerateLocalPackagesAndSetCache>d__34.MoveNext()

--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---

   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   bei ChocolateyGui.Services.CSharpChocolateyPackageService.<GetInstalledPackages>d__8.MoveNext()

--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---

   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   bei ChocolateyGui.ViewModels.Controls.LocalSourceControlViewModel.<LoadPackages>d__22.MoveNext()

--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---

   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   bei ChocolateyGui.ViewModels.Controls.LocalSourceControlViewModel.<Loaded>d__8.MoveNext()

--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---

   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()

   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   bei System.Windows.Threading.DispatcherOperation.Invoke()

   bei System.Windows.Threading.Dispatcher.ProcessQueue()

   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   bei System.Windows.Application.RunDispatcher(Object `ignore)`

   bei System.Windows.Application.RunInternal(Window window)

   bei ChocolateyGui.App.Main()
---------------------------
OK   
---------------------------
`

**Comment by RichiCoder1** [comment]
This is actually fixed in the most recent code, but I don't think it's had a change to release as a beta yet. For the short term fix would be to delete the file at `%LOCALAPPDATA%\ChocolateyGUI\packages.json`.

**Comment by Opensourcecommunitydevelopment** [comment]
removing packages.json worked for me ty
