### ISSUE TITLE
0.9.10 and exit codes

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/ChocolateyGUI#317]
I mentioned this before in April - https://github.com/chocolatey/choco/issues/512. 0.9.10 just released today. This includes the library. As you upgrade, be especially sure to pay attention to this scenario.

Here is the relevant portion of the [ChangeLog](https://github.com/chocolatey/choco/blob/master/CHANGELOG.md#0910-june-17-2016) (under breaking changes):

> - Exit with the same exit code as the software being installed - see [#512](https://github.com/chocolatey/choco/issues/512)
> 
> There are more exit codes from Chocolatey now that indicate success -`0`, `1605`, `1614`, `1641`, and `3010`. You may need to adjust anything you were using that would only check for 0 and nonzero.
> If you need the previous behavior, be sure to disable the feature `usePackageExitCodes` or use the `--ignore-package-exit-codes` switch in your choco commands.

**Comment by ferventcoder** [comment]
cc @gep13 @RichiCoder1 (let me know if I got the tags right).

**Comment by RichiCoder1** [comment]
@ferventcoder We're not checking exit codes to show error messages, so this is very relevant now. Is there a comprehensive lists of "good" codes? If I set `--ignore-package-exit-codes` can I just keep on using zero and non-zero?

**Comment by RichiCoder1** [comment]
Or I could tweak lib and add a super secret switch to just have Choco throw exceptions instead of just logging and error and exit code on failure.

**Comment by ferventcoder** [comment]
You could just use zero or one yes.

**Comment by ferventcoder** [comment]
The default good exit codes should be listed at the original link.

**Comment by RichiCoder1** [comment]
Looks like this was completed a while back. Sadly I screwed up our history with the subprocess changes, so I can't find the commit.
