### ISSUE TITLE
Proposal: Package Categories

### ISSUE THREAD

**Issue by wjk** [chocolatey/ChocolateyGUI#318]
In the conversation on chocolatey/chocolatey.org#223, I brought up the idea of adding package categories to the ChocolateyGUI user interface. @gep13 and I discussed the UI for the Mac App Store, and I [provided screenshots](https://github.com/chocolatey/chocolatey.org/issues/223#issuecomment-142999926). @RichiCoder1 mentioned that the gallery does not provide enough metadata to implement categories well.

I agree that the organization for packages on the community feed is not very well-designed. My opinion as to how to correctly fix this is to institute the standardization of package tags to provide the required metadata, but that is a major change that would take significant time to apply. In lieu of that, I would recommend providing an XML file or similar that contains category metadata and a list of packages that the category contains. Does this sound like a reasonable solution?

I would probably put the XML files into a directory inside AppData and have ChocolateyGUI pick them up from there. This would allow users to supply their own categories through adding their own XML files into this directory. (The XML files would be shipped alongside the app -- or embedded within it, a la [`chocolatey.resources`](https://github.com/chocolatey/choco/tree/master/src/chocolatey.resources) -- and copied upon first run.)

**Comment by RichiCoder1** [comment]
Will I like the idea in theory, you'll understand that I'm not super comfortable with shipping a custom solution, especially one that will require the kind of extensive support this will.

**Comment by RichiCoder1** [comment]
Related https://github.com/chocolatey/choco/issues/1363

**Comment by Computerlabrat** [comment]
This one is likely to be helpful. Browsing the apps is a bit of a pain as they're not sorted by type, but at the same time, there's currently over a hundred pages of programs, so doing this for each one individually can be a pain in the rear.

**Comment by pauby** [comment]
This is an old issue but one that I have come across now.

Package 'categories' isn't supported as part of NuGet v2 or v3 so we would have to use tags. Even if we added a custom field to the `.nuspec` file, this would be a custom solution for CCR only. Other repository manager would not support it. Given the limited number of users who request this and the limited support it would have in other repository managers, balanced with the huge undertaking to categorise packages, this isn't something we are looking to undertake.

The best way of doing this that works everywhere, is to [implement a set of standard tags](https://github.com/chocolatey/docs/issues/343) that could then be used as 'categories' which would be supported everywhere.

I'm going to go ahead and close this just now, but we can always reopen it again if necessary.
