### ISSUE TITLE
Unable to install on Windows 7 build 7600

### ISSUE THREAD

**Issue by superbonaci** [chocolatey/ChocolateyGUI#320]
This is my windows version and this my error:
## Windows 7 starter 32 bit 6.1 build 7600. The device is a Viliv S5 and can't update to Windows 7 SP1 because I loose touch screen function.

choco install chocolateygui

Timeout or your choice of '' is not a valid selection.
You must select an answer
Do you want to run the script?([Y]es/[N]o/[P]rint): Y

WARNING: PowerShell.5.0 not supported on Win7/2008R2.
WARNING: Update to SP1 to install WMF/PowerShell 5
ERROR: The term 'Write-Information' is not recognized as the name of a cmdlet, f
unction, script file, or operable program. Check the spelling of the name, or if
 a path was included, verify that the path is correct and try again.
The install of powershell was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\PowerShell\tools\ChocolateyIn
stall.ps1'.
 See log for details.

ChocolateyGUI v0.13.2 [Approved]
The package ChocolateyGUI wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?([Y]es/[N]o/[P]rint):

**Comment by RichiCoder1** [comment]
ChocolateyGUI has a dependency (currently) on Powershell 5, which is only supported on Windows 7 SP1+. I'd recommend updating and reattempting installation.
```
WARNING: PowerShell.5.0 not supported on Win7/2008R2.
WARNING: Update to SP1 to install WMF/PowerShell 5
```

**Comment by superbonaci** [comment]
The README.md says PowerShell 2.0+.
Tried updating powershell to 5 with Win7-KB3134760-x86.msu but says:
The update is not applicable to your computer.

**Comment by superbonaci** [comment]
Can I install the GUI "manually"?

**Comment by gep13** [comment]
@superbonaci you can find the msi on the GitHub Release here:

https://github.com/chocolatey/ChocolateyGUI/releases

That would allow you to download/install manually.

**Comment by RichiCoder1** [comment]
@superbonaci Currently manually, but I'm planning to re-add a self update feature.
