### ISSUE TITLE
Building chocolatey command...

### ISSUE THREAD

**Issue by superbonaci** [chocolatey/ChocolateyGUI#322]
I've finally installed ChocolateyGUI with the installer, because my computer has Windows 7 without SP1. See:
https://github.com/chocolatey/ChocolateyGUI/issues/320

However when updating foxitreader shows the message "Building chocolatey command..." and stays there forever with high CPU usage. How can I troubleshoot this?

**Comment by superbonaci** [comment]
Ok it took a lot of time probably because it's the first package I update and because the processor is an Intel Atom with graphics Intel GMA 500 and 1GB or ram. It finally finished and then updated opera in a breeze. Very happy with the result.

**Comment by RichiCoder1** [comment]
We're working with the chocolatey team to improve progress messages. Glad it worked for you!
