### ISSUE TITLE
"This PC" list repeated contents

### ISSUE THREAD

**Issue by wjk** [chocolatey/ChocolateyGUI#324]
I just used ChocolateyGUI to uninstall Inkscape from my computer. After the uninstall finished and I returned to the "This PC" package list, I noticed that the scrolling seemed to be off. After a bit of investigation, I realized that the package list was displaying _three_ complete, identical alphabetized package lists one atop the next. Below is a screenshot showing the list, filtered to show only the first package alphabetically.

![ChocolateyGUI Bug](https://cloud.githubusercontent.com/assets/1915951/17080759/d17a6354-5109-11e6-8c29-62b306f9c472.png)

As you can see, the "ACMESharp" entry is listed three times. The actions I took in the app before noticing the bug -- going into Inkscape's package page, returning, going into the package page again, uninstalling the package, and then returning to the This PC list -- seem to indicate that this list is not being cleared properly. I am not entirely certain if this combination of actions caused the bug to manifest or if it was something else, however.

**Comment by johnnyramos** [comment]
Just to be sure, is the package still in `C:\ProgramData\chocolatey\lib` ?

**Comment by wjk** [comment]
@johnnyramos Which package are you referring to? If you’re talking about ACMESharp, then yes it is. If you’re talking about ChocolateyGUI, please note that it is _not_ in the lib directory, because I have built it from source with the intention of sending pull requests.

**Comment by RichiCoder1** [comment]
@wjk Let me know if this is still an issue with the latest bits.
