### ISSUE TITLE
Syntax error when running Build in VS2015 Enterprise

### ISSUE THREAD

**Issue by johnnyramos** [chocolatey/ChocolateyGUI#326]
This is an off and on thing but every time I run a Build (Ctrl+Shift B), I get syntax errors within the code. Not sure why.

First error:

```
Severity    Code    Description Project File    Line    Suppression State
Error       SA0102 : CSharp.CsParser : A syntax error has been discovered in file D:\GitHub\ChocolateyGUI\Source\ChocolateyGui\Controls\Dialogs\ChocolateyDialogController.cs on line 184.  ChocolateyGui   D:\GitHub\ChocolateyGUI\Source\ChocolateyGui\Controls\Dialogs\ChocolateyDialogController.cs 184 
```

Code:

```
this.OnCanceled?.Invoke(this.WrappedDialog);
```

Second Error:

```
Severity    Code    Description Project File    Line    Suppression State
Error       SA0102 : CSharp.CsParser : A syntax error has been discovered in file D:\GitHub\ChocolateyGUI\Source\ChocolateyGui\Services\PackageServices\BasePackageService.cs on line 132.  ChocolateyGui   D:\GitHub\ChocolateyGUI\Source\ChocolateyGui\Services\PackageServices\BasePackageService.cs 132 
```

Code:

```
PackagesUpdated?.Invoke(
```

Not sure if these things need to be whitelisted in StyleCop but I wanted to raise awareness to you. :)

**Comment by gep13** [comment]
@johnnyramos sorry to hear that you are having issues :-(  This is not something that I have seen.  @RichiCoder1 have you seen this happening?

**Comment by gep13** [comment]
Perhaps time to move to the Roslyn based StyleCop Analyzers, if we haven't already.

**Comment by RichiCoder1** [comment]
@gep13 Actually thinking about writing a few analyzers to codify some common patters we use in Gui :)

**Comment by gep13** [comment]
@RichiCoder1 sounds good to me. The more we can catch at compile time the better IMO.
