### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by TheDauthi** [chocolatey/ChocolateyGUI#327]
ChocolateyGUI 0.13.2 crashes when the following is done:
- Start ChocolateyGUI

The app freezes, then throws the following error:

Last performed upgrade last night.

ChocolateyGui crashes during startup with attached exception (.txt added to allow upload to github)
[Chocolatey.gui.log.txt](https://github.com/chocolatey/ChocolateyGUI/files/424957/Chocolatey.gui.log.txt)

Tried with both v0.13.2 and 0.14.0-unstable0002

**Comment by ozwin** [comment]
I have the same problem : https://i.imgur.com/CSY2Yw8.png

Version 0.13.2

**Comment by WimObiwan** [comment]
I have the exact same problem on v0.13.2, but I can assure that it is fixed for me when building from the development branch (currently 6bc0fb8fe291f54885b215b7e9258f3e553729c7).
