### ISSUE TITLE
Can't control main window while actions are in progress

### ISSUE THREAD

**Issue by DaveInCaz** [chocolatey/ChocolateyGUI#329]
If I, say, run an update all in ChocolateyGUI, while it is running all the main window controls are disabled. I tend to run it full screen (maximized) and this means I can't minimize it while its running. Seems like the main window should still be fully operable even though update (or whatever action) is running.

Thanks

**Comment by RichiCoder1** [comment]
Chocolatey isn't very friendly about concurrent operations, but we could support this by forbidding "destructive" or install/uninstall type operations while the update is pending.

**Comment by gep13** [comment]
@RichiCoder1 I have just been looking at this again...

Looks like when the Progress Dialog is being displayed, the UI is blocked, and can't be interacted with.  Other async operations work as expected.

Any ideas on what is going on here?

**Comment by RichiCoder1** [comment]
It's just the nature of the dialog. It's why I'd like to kill and replace it. In theory we could make the background draggable or something.

**Comment by gep13** [comment]
>@RichiCoder1 said...
It's why I'd like to kill and replace it.

What would you see this being replaced by?

**Comment by RichiCoder1** [comment]
That is the question I haven't answered haha. Hence why I haven't yet replaced it.

**Comment by RichiCoder1** [comment]
Dialogs should no longer block window actions. May restrict in the future. 

Closed by 9801a36;
