### ISSUE TITLE
Update all button hard to find

### ISSUE THREAD

**Issue by DaveInCaz** [chocolatey/ChocolateyGUI#330]
I'm a new user to Chocolatey. Took me a while to find out that the update all button only appears when "show only packages with updates" is checked. For a while I couldn't figure out how to update packages at all.

I recommend showing this button all the time. It would make sense to "update all" even if you have lots of packages in the list which do not require updates.

Thanks

**Comment by RichiCoder1** [comment]
Should be resolved w/ 2aa0d05.
