### ISSUE TITLE
Win32Exception upon clicking the "Install GoogleChrome instead" link in "Google Chrome (64-bit only)" detail page

### ISSUE THREAD

**Issue by albertdc** [chocolatey/ChocolateyGUI#332]
![image](https://cloud.githubusercontent.com/assets/1075907/18908272/9518b948-85a1-11e6-861d-8b16471f7e7b.png)

**Comment by mwallner** [comment]
Have you checked %AppData%\ChocolateyGUI\Logs ?
Considering the given stack trace I'd say it couldn't find choco.exe on your system.

**Comment by RichiCoder1** [comment]
Shoooould no longer be relevant w/ develop version.
