### ISSUE TITLE
Handle pinned packages

### ISSUE THREAD

**Issue by Razzeee** [chocolatey/ChocolateyGUI#336]
- We should show an icon for pinned packages
- We should be able to pin/unpin from the contextmenu of a package
- Don't show these pinned packages, when "Show all packages with updates" is selected
- Update all should honour this (might already be the case)

**Comment by RichiCoder1** [comment]
d956e345 should address all of these except pin/unpin functionality once merged.

**Comment by RichiCoder1** [comment]
Merged in develop. Will be available in the next release.
