### ISSUE TITLE
Switch Build Infrastructure to Cake

### ISSUE THREAD

**Issue by RichiCoder1** [chocolatey/ChocolateyGUI#341]
Todo:

- [x] Replace PS Build with cake
- [x] Pull tools like Resharper CLT w/ Nuget

**Comment by gep13** [comment]
Sounds like a plan to me! You want me to handle this, or are you happy to take it?

**Comment by RichiCoder1** [comment]
Honestly? Which ever one of us gets there first haha. Just post here if/when you do it, and I'll do the same if I do.

**Comment by gep13** [comment]
This was actually known with commits labelled #349
