### ISSUE TITLE
NullReferenceException on closing settings

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/ChocolateyGUI#352]
## Steps to reproduce:
* Start ChocolateyGUI
* Go to settings
* Go to About
* Go back to Options
* Click < Button

## Error message
![unbenannt](https://cloud.githubusercontent.com/assets/2190718/21313716/ae829042-c5f3-11e6-9acc-34fad7db7073.png)

## Version
ChocolateyGUI Version: v0.14.0-unstable0144

**Comment by pascalberger** [comment]
In which release should this be fixed? I still get the same exception in `v0.14.0-unstable0147`

**Comment by RichiCoder1** [comment]
Weird. I'l continue to look into it.

**Comment by RichiCoder1** [comment]
I can't reproduce on the latest develop.

**Comment by pascalberger** [comment]
@RichiCoder1 Is there any difference between `v0.14.0-unstable0147` available from `https://www.myget.org/F/packages_develop/api/v2` and develop? Couldn't you also reproduce with `v0.14.0-unstable0147`?

**Comment by pascalberger** [comment]
After uninstalling all ChocolateyGUI instances from Program & Features and running `choco install` again this is fixed.
