### ISSUE TITLE
Errors on console updating package

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/ChocolateyGUI#353]
I tried updating the NodeJs package using ChocolateyGUI Version v0.14.0-unstable0144. While update was successful cn the console several errors are shown:

```
2016-12-19 14:03:14.172 +01:00 [Error] Error when setting configuration for 'chocolatey.licensed.infrastructure.app.builders.ConfigurationBuilder':
 Exception has been thrown by the target of an invocation.
```

[Full log](https://gist.github.com/pascalberger/5077d9f5258332573fed12024da7d4d0)

**Comment by RichiCoder1** [comment]
That's bizarre....the install was indeed fine, but for some reason chocolatey was failing to serialize some odd property. And since you were able to install, it likely wasn't a full on permissions eror. Somehow you have permission to install, but not to write `C:\ProgramData\chocolatey\config\chocolatey.config.update`. /cc @ferventcoder any ideas?

**Comment by pascalberger** [comment]
Just starting ChocolateyGUI also leads to some errors:

```
2016-12-19 14:16:47.733 +01:00 [Information] Starting WAMP Client on port 24606.
2016-12-19 14:16:48.515 +01:00 [Information] Server started at ws://127.0.0.1:24606/ws
2016-12-19 14:16:50.616 +01:00 [Error] Error when setting configuration for 'chocolatey.licensed.infrastructure.app.builders.ConfigurationBuilder':
 Exception has been thrown by the target of an invocation.
2016-12-19 14:16:50.624 +01:00 [Error] Error serializing type chocolatey.infrastructure.app.configuration.ConfigFileSettings:
 Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config.update' is denied.
2016-12-19 14:16:50.693 +01:00 [Error] Error when setting environment for 'chocolatey.licensed.infrastructure.app.configuration.EnvironmentSettings':
 Exception has been thrown by the target of an invocation.
2016-12-19 14:16:51.327 +01:00 [Error] Error when setting configuration for 'chocolatey.licensed.infrastructure.app.builders.ConfigurationBuilder':
 Exception has been thrown by the target of an invocation.
2016-12-19 14:16:51.328 +01:00 [Error] Error serializing type chocolatey.infrastructure.app.configuration.ConfigFileSettings:
 Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config.update' is denied. 
```

Might it be an issue using the professional version (Chocolatey v0.10.3 Professional)?

**Comment by RichiCoder1** [comment]
That's what I'm thinking.

**Comment by RichiCoder1** [comment]
Just realized I never cc'd @ferventcoder on this, as I believe this is an issue with premature serialization attempts.

**Comment by cSharpRookie** [comment]
I'm having this problem with a trial version of chocolatey. Just wondering has this been fixed
![image](https://user-images.githubusercontent.com/11905573/27227854-27af83b8-529d-11e7-80a1-50570a21eb6f.png)

**Comment by RichiCoder1** [comment]
Hmm. I'm not honestly sure. /cc @ferventcoder

**Comment by ferventcoder** [comment]
Hi @cSharpRookie @RichiCoder1 ! 

With Boxstarter, it needs to just get the latest version of the chocolatey.lib and those issues should dissolve. When you mention it to @mwrock, just ask if it is using chocolatey.lib 0.10.7 yet.

**Comment by ferventcoder** [comment]
@RichiCoder1 For this to work properly, we need to get #371 done.

**Comment by ferventcoder** [comment]
In a way, this sort of duplicates #371. The work being done there makes chocolatey.lib work correctly.

**Comment by ferventcoder** [comment]
@cSharpRookie it's a problem with Boxstarter.

**Comment by gep13** [comment]
@pascalberger fairly sure that this has been addressed with the recent round of refactoring.  Can you take the latest package on the MyGet feed for a spin, and report back if you still have issues?

Going to close this for now, please re-open if still a problem.

**Comment by pascalberger** [comment]
I just tried with 0351 and still get the error if I click on a source in the left pane.

@gep13 I don't seem to have permissions to reopen the issue

**Comment by gep13** [comment]
@pascalberger can you confirm that you first uninstalled any existing installation of ChocolateyGUI before installing the latest?  There is an issue where you can actually end up with two copies of Chocolatey GUI.

**Comment by pascalberger** [comment]
@gep13 You're right. Uninstalling both versions and reinstalling fixed the issue

**Comment by gep13** [comment]
Woot! 😄
