### ISSUE TITLE
Link not parsed in Release Notes

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/ChocolateyGUI#355]
ChocolateyGUI doesn't render links in the release notes section as links:

![unbenannt](https://cloud.githubusercontent.com/assets/2190718/21314895/bd3e93f0-c5f9-11e6-85e0-be9239624041.png)

While they are parsed as HTML links on chocolatey.org:

![unbenannt](https://cloud.githubusercontent.com/assets/2190718/21314925/eb2f2504-c5f9-11e6-8f2e-a75550d0d76b.png)

## Versions
Chocolatey: v0.10.3 Professional
ChocolateyGUI: v0.14.0-unstable0145

**Comment by RichiCoder1** [comment]
Hmm. This is a shortcoming of markdown engine. If the package maintainer doesn't use proper markdown syntax to identify URLs, they don't show up as links. Not sure how trivial it'd be to fix this either.

**Comment by gep13** [comment]
@RichiCoder1 I don't think the markdown engine being used on Chocolatey.org does anything special here.

**Comment by RichiCoder1** [comment]
Ahh, I think this might be as simple as flipping a switch indeed.

**Comment by RichiCoder1** [comment]
Fixed by 0f4d253a7a9a71e00c790d3b46b209392111c4d6
