### ISSUE TITLE
Rendering of headings in description 

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/ChocolateyGUI#356]
See the [Visual Studio Code Package](), which follows the [Core Team Packages Guidelines for Description](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines#123-informative-description).

While rendering of the description looks nice on chocolatey.org:

![unbenannt](https://cloud.githubusercontent.com/assets/2190718/21315071/b338efbc-c5fa-11e6-8a2d-abb81be17ef1.png)

It looks quite strange in ChocolateyGUI with the headings inside of the description beeing more 	
accentuatet than the overall headings like "Description":

![unbenannt](https://cloud.githubusercontent.com/assets/2190718/21315104/d4b02a8e-c5fa-11e6-8398-512a9e06dde5.png)

## Versions
Chocolatey: v0.10.3 Professional
ChocolateyGUI: v0.14.0-unstable0145

**Comment by RichiCoder1** [comment]
Agreed. Now that we have a proper markdown engine, I'm thinking on how to restyle that whole central section. Any feedback in regards to that is welcome.

**Comment by gep13** [comment]
@pascalberger based on the changes that @punker76 has recently made to the details page, can you comment on whether you would still like to see more changes in this area.

If so, can you elaborate on exactly what you are looking for?

**Comment by pascalberger** [comment]
IMHO still the same issue. For Visual Studio Code headings inside of the description appear in a bigger font size than the description header itself (size difference look even more in current release than in screenshot in https://github.com/chocolatey/ChocolateyGUI/issues/356#issue-196418803)

**Comment by gep13** [comment]
@pascalberger the up to date screenshot is as follows:

![image](https://user-images.githubusercontent.com/1271146/56567389-b52e4700-65ac-11e9-9866-c2b2f2da01f3.png)

**Comment by pascalberger** [comment]
Yes, logically the topic tree looks like this:

- Package ID
- Description
  - Features
  - Package parameters
- Release Notes

But visually it looks for example like "Release Notes" is a sub point of "Package parameters" and it's visually not clear that "Features" and "Package parameters" belong to "Description", since "Description" is in a much lower font size.

**Comment by gep13** [comment]
@pascalberger I am open to suggestions on how to improve this 😄

**Comment by pascalberger** [comment]
Can't we just apply a style to the rendering of the description field which results in H2 in the markdown content to be rendered in a style which is less prominent than "Description" is rendered?
Maybe it would also help to make "Package ID", "Description" and "Release Notes" also a little bit more prominent to have more possibilities to style the headings of the description markdown test.

**Comment by gep13** [comment]
@pascalberger honestly, I am not sure.  I wasn't really involved in the implementation of the markdown rendering in the current version of Chocolatey GUI, so I will need to do some digging into what can, and can't be done.

**Comment by punker76** [comment]
@gep13 @pascalberger @ferventcoder @mwallner @AdmiringWorm @RichiCoder1 

Here is my suggestion for the Package view:

To improve the Package view the headings outside of the description have now the same font size and weight. Also the Icon and the Id are moved to the left side. The right side is now vertically stretched and can be scrolled if it's to large.

![2019-04-25_23h46_28](https://user-images.githubusercontent.com/658431/56770492-694dee80-67b4-11e9-8fdc-21befce6679b.png)

![2019-04-25_23h46_51](https://user-images.githubusercontent.com/658431/56770495-6b17b200-67b4-11e9-896c-91f931933dd5.png)

![chocopackage](https://user-images.githubusercontent.com/658431/56770507-710d9300-67b4-11e9-8908-a207db4a7aa5.gif)

**Comment by mwallner** [comment]
this looks fantastic!

**Comment by pascalberger** [comment]
Looks great :shipit:
