### ISSUE TITLE
NullReferenceException opening settings while packages are loading

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/ChocolateyGUI#357]
## Steps to reproduce
* Start ChocolateyGui
* Click on the `settings` link in the title bar while ChocolateyGUI is still loading the packages installed on the local machine

## Exception
![unbenannt](https://cloud.githubusercontent.com/assets/2190718/21315300/ccb30436-c5fb-11e6-83a1-4b4f6fd10eff.png)

## Versions
Chocolatey: v0.10.3 Professional
ChocolateyGUI: v0.14.0-unstable0145

**Comment by gep13** [comment]
@pascalberger since the refactoring, I have not been able to get this to happen again.

For now, I am going to close this out.  Let me know if you can get this to happen again.
