### ISSUE TITLE
Option for hiding disabled package sources

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/ChocolateyGUI#358]
Currently all sources are listed without any visual indication about their state. In my use case I plan to use ChocolateyGUI as self-service portal in an enterprise environment. While we have a feed for testing packages, I don't wan't users to see it by default. A switch to disable listing of disabled feeds in the settings would be nice, and if they are shown they should be shown differently than other sources.

**Comment by RichiCoder1** [comment]
Testing multiple sources has gotten the *least* testing of anything. I'll work on this next :)

**Comment by pascalberger** [comment]
I see ChocolateyGUI as a frontend for endusers for installing and updating packages. So in my case they shouldn't bother about sources at all, and therefore are not interested in hidden sources, or if they are should be able to use cmd line.

**Comment by RichiCoder1** [comment]
Agreed.
