### ISSUE TITLE
Error starting v0.14.0-unstable0147

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/ChocolateyGUI#360]
I just installed ChocolateyGUI on another machine and receive the following error on startup:

![untitled](https://cloud.githubusercontent.com/assets/2190718/21327344/eac68636-c62e-11e6-8d25-dc2b3bb71ee7.png)

OS: Microsoft Windows [Version 10.0.14965]

**Comment by RichiCoder1** [comment]
I do believe you have managed to run into the infamous config corruption bug. I've got a PR open over here to try and fix it: https://github.com/chocolatey/choco/pull/1084

**Comment by gep13** [comment]
@pascalberger fairly sure that this has now been corrected.  Can you please give the latest version a try, and let me know if you are still running into problems.

Closing issue for now, but feel free to re-open.
