### ISSUE TITLE
Two entries in Programs & Features after choco upgrade

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/ChocolateyGUI#366]
To reproduce:

* `choco install chocolateygui --source https://www.myget.org/F/packages_develop/api/v2 --version v0.14.0-unstable0160`
* `choco upgrade chocolateygui --source https://www.myget.org/F/packages_develop/api/v2 --version v0.14.0-unstable0165`

After the `choco upgrade` there are two entries for ChocolateyGUI in the control panel.

**Comment by RichiCoder1** [comment]
Ahh, I think I figured it out. MSI treats installs with the same version code & Major.Minor.Patch version as seperate installs. Looks like if I set `AllowSameVersionUpgrades` to `yes`, it should treat same version installs as upgrades. I'll get on that 👍

**Comment by gep13** [comment]
@RichiCoder1 re-opening this for now...

**Comment by TheVakman** [comment]
If this is also fixed in 0.15.0, that will be awesome!

**Comment by gep13** [comment]
@TheVakman this should be closed going forward.  If you continue to see this issue, then definitely let us know.
