### ISSUE TITLE
Win7 Powershell5 update

### ISSUE THREAD

**Issue by Happy-User** [chocolatey/ChocolateyGUI#368]
Using Win7 SP1 with ChocoGUI 0.13.2.

Unwittingly updated Powershell5 to latest available. GUI now crashes with trying to retrieve installed packages on startup, with an unhandled exception - apologies will post a screen shot when back on my win7 machine.
Haven't upgraded on other systems just in case, which continue to function fine, so not sure if this is a powershell/win7 interaction issue.
![image](https://cloud.githubusercontent.com/assets/24700104/21467798/a729b8d2-c9f1-11e6-9e65-5ce8b204af99.png)

**Comment by RichiCoder1** [comment]
Looks like the same issue as #452. Should be fixed now.
