### ISSUE TITLE
Add check for useBackgroundService 

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#371]
ChocolateyGUI needs to look in the config file and see if features/useBackgroundService is there and if it is set to true.

Then allow running install/upgrade without trying to seek admin rights.

**Comment by ferventcoder** [comment]
Thanks!

**Comment by ferventcoder** [comment]
cc @RichiCoder1 (I believe we chatted about this awhile back so if this is already done... ;))

**Comment by RichiCoder1** [comment]
@ferventcoder Saaaadly no. Everything is in place to make this check, but I haven't done the work itself. Sadly my actual job went from 1 to 60 just recently.
