### ISSUE TITLE
chocolateygui.portable package

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/ChocolateyGUI#376]
This seems like a great add. Just a package that has the software in it with no dependencies.

**Comment by RichiCoder1** [comment]
I don't see why this wouldn't be possible. We might have to tweak how logs are written so we don't write to ProgramData, but otherwise this seems like a fine idea to me.

**Comment by pauby** [comment]
After internal discussion, we have agreed that offering a portable package is not something we are going to do.
