### ISSUE TITLE
InvalidOperationException on startup

### ISSUE THREAD

**Issue by Razzeee** [chocolatey/ChocolateyGUI#377]
For some reason chocolatey gui fails to start for me. I think I also get this on multiple PCs.

![image](https://cloud.githubusercontent.com/assets/5943908/22056568/ff80ce8a-dd60-11e6-89f1-fb5ee968b534.png)

![image](https://cloud.githubusercontent.com/assets/5943908/22056632/4776e9a4-dd61-11e6-9061-c66a01385460.png)

**Comment by wjhill** [comment]
I'm having the same issues. Per the Submitting Issues section:

- [Log](https://gist.github.com/wjhill/72585cf4185d4ba2b65f6d361e291a07)

- OS Version: Windows 10 Pro 1607 (Build 14393.693)

- Chocolatey Version: 0.10.3 (Professional License)

- PowerShell Version: 5.1.14393.693 

Chocolatey has always been run as Admin on this machine, as was the GUI -- I start them from a normal user account and then UAC up to Admin for Chocolatey.

**Comment by Razzeee** [comment]
My problem is gone, not sure why. Might have been a serverside fix.

**Comment by gep13** [comment]
@Razzeee thanks for following up.

I will go ahead and close this issue.  @wjhill let us know if you are still experiencing problems.
