### ISSUE TITLE
Chocolatey Helper Methods

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#38]
Does it make sense to expose UI components to make calls to the Chocolatey Helper Methods?

Such as PinnedItems, DesktopShortCut, etc?

https://github.com/chocolatey/chocolatey/wiki/HelpersReference

**Comment by RichiCoder1** [comment]
I'm not sure I understand this issue.

**Comment by gep13** [comment]
@RichiCoder1 the thought process here was to expose the Chocolatey Helper Methods for doing certain things, like creating shortcuts, pinned items, etc, for the installed packages.  i.e. when someone really wants a desktop shortcut for an application, and one wasn't created.  Provide a UI to allow them to enter the necessary information, and then click a button, rather than having to do anything else, like drop to the command line, etc.

Not sure if this is really relevant anymore.

**Comment by RichiCoder1** [comment]
I think my vote is no at this point.
