### ISSUE TITLE
Dates are displayed in US format not in machine locale format

### ISSUE THREAD

**Issue by laperouse** [chocolatey/ChocolateyGUI#380]
Dates displayed on a package detail view (last update for instance) are displayed in US format whereas the machine date format is French.
Dates times and numbers, should be displayed using the machine locale format.

(Surprisingly package size is in the machine locale already, probably because it is formatted to string through a windows API.)

Localization can be done using a WPF localized binding like this (for instance):

    public class LocalizedBinding : Binding
    {
        public LocalizedBinding()
            : base()
        {
            this.ConverterCulture = System.Globalization.CultureInfo.CurrentCulture;
        }
        public LocalizedBinding(string path)
            : base(path)
        {
            this.ConverterCulture = System.Globalization.CultureInfo.CurrentCulture;
        }
}

**Comment by RichiCoder1** [comment]
Huh. I was 99% sure this was an automatic thing. I'll look into fixing this.
(And you're correct about package sizing).

**Comment by RichiCoder1** [comment]
@laperouse Could you verify this is still an issue with the latest prerelease? I believe some work we're doing with localization might have incidentally fixed this.

**Comment by AdmiringWorm** [comment]
@RichiCoder1 I can verify that this no longer happens (with the latest build from the develop branch).

![image](https://user-images.githubusercontent.com/1474648/27264935-3fcad390-548b-11e7-80d4-ce06e8ede32b.png)

Everything is correctly formatting according to my locale.

**Comment by RichiCoder1** [comment]
Glad to hear!
