### ISSUE TITLE
Globalisation - Dutch

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#395]

**Comment by gep13** [comment]
@chrissie1 following the work that @mwallner has done to get support for the German Language, would you be interested in supporting Dutch?  Thanks!

**Comment by mwallner** [comment]
nice! - I'm going to write a little 'HOWTO- do translation for ChocolateyGUI' - but It'll take 1-2 days...

**Comment by gep13** [comment]
@mwallner that sounds perfect.  Also sounds like something we should get into the new documentation site that I am creating for ChocolateyGUI:

https://chocolatey.github.io/ChocolateyGUI/about

It is very bare bones at the minute, but the framework is at least there, just need to fill it in 😄

**Comment by gep13** [comment]
This has been completed by @chrissie1 😄
