### ISSUE TITLE
Globalisation - Swedish

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#396]
@devlead @patriksvenson following the work that @mwallner has done to get support for the German langauge, would you be interested in providing support for Swedish?  Thanks!

**Comment by magol** [comment]
Jag hjälper gärna till att översätta till svenska 😊

I'm want to help to translate to Swedish

**Comment by gep13** [comment]
>@magol said...
I'm want to help to translate to Swedish

That is great news!

Perhaps @mwallner could provide a brief overview of how to approach adding another locale into the project?

**Comment by mwallner** [comment]
nice! - I'm going to write a little 'HOWTO- do translation for ChocolateyGUI' - but It'll take 1-2 days...
