### ISSUE TITLE
The "title" of the UI is often wrong or non-sensical

### ISSUE THREAD

**Issue by RichiCoder1** [chocolatey/ChocolateyGUI#399]
The title displayed in the task bar or other locations is often wrong or non-sensical. Should go through and make page titles consistent.

**Comment by gep13** [comment]
@RichiCoder1 do you have an example of where this was happening?  I haven't been able to reproduce what is described here.

**Comment by RichiCoder1** [comment]
I may have accidentally fixed this since I made this issue. Will review later.

**Comment by gep13** [comment]
@RichiCoder1 nice one, thank you!

**Comment by RichiCoder1** [comment]
Looks to be resolved
