### ISSUE TITLE
Absolute reference in .ruleset

### ISSUE THREAD

**Issue by fwinkelbauer** [chocolatey/ChocolateyGUI#401]
@gep13 I just wanted to let you know that the `ChocolateyGuiRules.ruleset` contains an absolute reference in line 3:

```xml
<Include Path="D:\github\Forks\chocolatey\ChocolateyGUI\Source\chocolateyguirules.ruleset" Action="Default" />
```

I guess the intended line should read

```xml
<IncludeAll Action="Warning" />
```

I have tested this on my machine and it doesn't change the output in Visual Studio, so I guess that this is just a very very minor thing.

**Comment by gep13** [comment]
@fwinkelbauer thanks for the further information.  This is related to this issue: #393

**Comment by fwinkelbauer** [comment]
My bad... searching for "rule" and "set" didn't bring up anything. Should have checked "ruleset" as well 😆

**Comment by gep13** [comment]
Ha ha, no worries. GitHub search wins again :-)
