### ISSUE TITLE
ChocolateyGUI, Chocolatey GUI, Chocolatey Gui, or something else

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#402]
Seems like we refer to this differently depending on where in the application it is written.

Can you settle on what we want to call the application, and be consistent everywhere?

@ferventcoder @RichiCoder1 @mwallner 

TL/DR

* ChocolateyGUI for when spaces are forbiden or not advised (choco pkg, github), 
* otherwise use Chocolatey GUI for branding

**Comment by RichiCoder1** [comment]
I've always gone with ChocolateyGUI, but mostly for legacy reasons. Don't feel strongly any which way.

**Comment by mwallner** [comment]
My first thought: 'ChocolateyGUI' as official name .. what's the official status/relation to Chocolatey? part of the organization? 
I like how Rob calls biz-edition apps like 'Package Builder UI' 

I'd suggest: either stick with


* ChocolateyGUI

or 'completely change it' to


* Chocolatey UI

**Comment by RichiCoder1** [comment]
The biggest reason I'd say GUI over UI is just that is a much cleaner play on the word `gooey`, as in gooey chocolatey :3.

**Comment by mwallner** [comment]
:D ok - I like it either way!
nevertheless I'd like to hear @ferventcoder and @chrissie1 's opinions!

**Comment by ferventcoder** [comment]
I like "Chocolatey GUI" or "ChocolateyGUI"

**Comment by ferventcoder** [comment]
Package Builder UI, Package Internalizer UI, Package Pusher UI, Package Installer UI - those are some of the smaller ones.

**Comment by mwallner** [comment]
it's going to be "Chocolatey GUI" then?
* will try to identify 'wrong' and fix them sometime this week

**Comment by RichiCoder1** [comment]
My verdicts would be ChocolateyGUI for when spaces are forbiden or not advised (choco pkg, github), but otherwise use Chocolatey GUI for branding. Looks cleaner.
