### ISSUE TITLE
Globalization - Norwegian Bokmål

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/ChocolateyGUI#404]
Since the swedish translation is on its way, perhaps consider a norwegian translation for the most used written edition of the language (Bokmål).

I'm of course willing to help out in that regard of course.

**Comment by gep13** [comment]
@AdmiringWorm this language was next on my list 🙂  Been thinking about what languages I have access to on terms of people I know. Thank you very much for offering to help with this!
