### ISSUE TITLE
Text/Header strings not prepared to be translated

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/ChocolateyGUI#405]
While working on a translation to Norwegian Bokmål I noticed that there was certain parts that haven't yet been prepared to be translated.

*Current findings*
The current parts that I found that haven't been prepared yet.
- Local/Remote package context menu
- Disabled Header in the SettingsView_Source

Places referencing the wrong string
- PackageView pin button is referencing the install button text.

I've fixed this in a local commit, so if interested I can open a PR for it.

**Comment by mwallner** [comment]
I'd like to see a PR :+1:

**Comment by AdmiringWorm** [comment]
@mwallner PR submitted: #406

**Comment by RichiCoder1** [comment]
Closed by #406

**Comment by gep13** [comment]
@AdmiringWorm thank you for submitting this, appreciate you taking the time to look at it!

**Comment by AdmiringWorm** [comment]
@gep13 no problem, I probably missed some strings somewhere, as well as strings related to exceptions and logging was not added in #406. Mainly because, logging shouldn't be translated IMO, and didn't know which exceptions was displayed to the user so basically ignored those.
