### ISSUE TITLE
the 'download count' is not incremented after package install

### ISSUE THREAD

**Issue by mwallner** [chocolatey/ChocolateyGUI#409]
After installing a package it's download count is not increment right away (need to click 'refresh')
might be misleading concerning if a package install was successful or not

**Comment by mwallner** [comment]
@RichiCoder1 I'd just say we incremented the displayed value by 1 after the package install is successful - might not be totally correct on the community feed with a lot of concurrent installs - but it definitely would be an improvement

**Comment by mwallner** [comment]
> but I'm not sure how I feel about that
me neither - drop it / working as intended?
* it just came up because we're using Chocolatey GUI in a small environment with just 100+ Packages (a change in download-count is noticeable if a lot of packages have only 30+ downloads 🤣 )

**Comment by RichiCoder1** [comment]
I'm going to say it's an interesting idea, but veto for now.  Puts things in an inconsistent state, and our package state management in GUI is already a bit weird :P

**Comment by gep13** [comment]
For what it is worth, I agree with this decision.  I prefer the concept of a single source of truth.  ChocolateyGUI is not the source of truth in this instance, so I think we should leave it as is.
