### ISSUE TITLE
Crashes upon open - cannot launch Win7x64-WMF5.1

### ISSUE THREAD

**Issue by CollinChaffin** [chocolatey/ChocolateyGUI#420]
Running Win7x64 and Powershell 5.1.  Get the following unhandled dotnet exception at open followed by the crash and forced close - resulting in not ever being able to successfully launch the app:

https://1drv.ms/i/s!AhSqjTYUuHPKgb4PsVQOZOUnqQk-OQ

https://1drv.ms/i/s!AhSqjTYUuHPKgb4R5COhADZ8q0B5MA

Would really love to use this app, so hopefully this is something that can be fixed quickly.  It is happening on multiple machines here, both physical and virtual - all Win7x64, all same patch and WMF5.1 level.

**Comment by gep13** [comment]
@CollinChaffin can you confirm what version of ChocolateyGUI you are using?

**Comment by gep13** [comment]
Never mind, I see what version you are on...

Can you please try the pre release of the next version, instructions on how to install are on the readme of this repo, and let us know if you still face issues?

**Comment by CollinChaffin** [comment]
Confirmed that the prerelease installed via Github eliminates this exception and crash!  Thanks for the quick reply and solution!
