### ISSUE TITLE
After selecting single package to update upon update completion the UI list of packages remains blank does not refresh

### ISSUE THREAD

**Issue by CollinChaffin** [chocolatey/ChocolateyGUI#421]
This is on the current prerelease.  To reproduce:  list all local packages with available updates.  Select any single package and perform update, expand console output to watch progress.  Upon successful completion, the UI appears to refresh based on status/progress bar, but will always return to an (inaccurate) empty UI list still with the checkbox checked for "show only packages with updates" as shown here:

https://1drv.ms/i/s!AhSqjTYUuHPKgb93o4ohovXPaAfLHQ

Upon clicking to uncheck the "show only packages with updates" box, and then re-checking (enabling) it in a 2-click operation results in the correct full list of locally installed packages with updates available that was initially shown prior to the update operation once again being correctly displayed.  This manual workaround is currently necessary for every package update operation.

**Comment by gep13** [comment]
@CollinChaffin thanks for reporting this issue.  We think that this should now be taken care of.  If you have the time, if you could take a look at the most recent version of Chocolatey GUI from the MyGet feed and let us know, we would really appreciate it.  Thanks.
