### ISSUE TITLE
Current prerelease does not display any versioning information in the ABOUT screen

### ISSUE THREAD

**Issue by CollinChaffin** [chocolatey/ChocolateyGUI#422]
The current prerelease despite scrolling all info in all three panes in the ABOUT window shows no version numbering information as shown here:

https://1drv.ms/i/s!AhSqjTYUuHPKgb94W2haovK4WkNtEA

Opening as an issue/enhancement request as it makes it difficult as an end-user to identify the actual version number for support purposes to consider displaying the major/minor/build number in the ABOUT screen.

Thanks!

**Comment by gep13** [comment]
@CollinChaffin thank you for raising this.

I have changed this to include the following:

![image](https://user-images.githubusercontent.com/1271146/56729774-f90c8200-674d-11e9-9be1-5484ce7d873c.png)

This will be included in the next release of Chocolatey GUI.
