### ISSUE TITLE
Selecting multiple packages with CTRL key to update results in only the first package being updated

### ISSUE THREAD

**Issue by CollinChaffin** [chocolatey/ChocolateyGUI#424]
Sorry to open another issue just started using this prerelease but also did not see this as an open issue which surprises me.  Since the non-prerelease crashes for me I have no idea if this is a new bug or not.

I would think that allowing the user to hold down CTRL and taking a bunch of time to then select/highlight/tag multiple packages just to right click with the tagged list highlighted and select "UPDATE" should result in all the selected packages being updated.  In all my testing, only the first selected package actually gets an update and the rest of the list is simply ignored - forcing a one-by-one or all for updating and nothing in-between.

 I am executing using the installed defaults using the Choco PS host etc.  if there is anything else I can help test or provide on this just let me know and I'll be happy to help!

**Comment by RichiCoder1** [comment]
This is because the context menu is always scoped to the right clicked package. That being said, we could add an [Update Selected] button

**Comment by CollinChaffin** [comment]
Hi guys, any update on this?  As a developer myself I've already helped a few other people struggling with this issue so I am seeing first-hand the confusion this is raising .  With the addition of the windows ability via the OS to hold ctrl and do multi-selection almost three decades ago, I would suggest one of two things - simply tag the controls property (or add the event handler) to simply override the normal ctrl+ multi selection, and just limit the operator's allowed actions to match the functionality you're currently willing to provide in this GUI of single selection -- or -- add the code to kick off the multiple threaded jobs the same way you would do in any other winform GUI down to using the controls in a baked up Powershell GUI (that I have had to do much of lately).  I don't personally mind the lack of the multi-thread as others have complained of, but doing the latter here above would actually make all those folks very happy as well and close at least one or two more currently open issues at the same time.

I'm only pushing perhaps doing one or the other of these things because right now as much as I really do LOVE this GUI (and hopefully might even have some personal time free up here to begin contributing some code).......right now this basic multi-selection we have all lived with for 30yrs that "appears" to work here and then only updates a single package (last selected), seriously appears and feels like it's just flat out broken.   

As a second side-note, I know the history of this GUI, so then this didn't shock me, but I'll add that if new users DO think something is broken not updating the multi-packages it allowed them to select and right-click to update, I may have mentioned before but it appears to have now gotten even worse and we might want to also overhaul the "about/support" page and remove the broken history, because clicking the first three of the "holy crap, help me" section links, takes a brand new user to this, which may make them think at a glance it's no longer even being developed:

![snag_9-1-2017_12-00-48](https://user-images.githubusercontent.com/9301483/29980336-07f42e30-8f0f-11e7-8c90-e7769ec53a3f.png)

Let me know if there is anything else I can do to help or test anything!

**Comment by RichiCoder1** [comment]
At least right now I'm going to go with Option A, aka. only allow single selection. I'd really like to allow multi-select operations but that's further down the line. PR coming to change to single select and I'll create a seperate master issue to enable bulk-operations on local sources.

**Comment by RichiCoder1** [comment]
CTRL + Click has been disabled. I'm going to open a seperate issue to enable bulk ops.
