### ISSUE TITLE
Add additional properties to Sources Tab in Settings screen

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#425]
Specifically:

* By Pass Proxy
* Self Service

/cc @ferventcoder

**Comment by gep13** [comment]
This is how the screen has been made to look:

![image](https://cloud.githubusercontent.com/assets/1271146/23814750/9ab4a6e4-05dc-11e7-8798-5b7faaf7391d.png)

Thoughts?

**Comment by ferventcoder** [comment]
I think that looks great! A small change though to the checkbox labels - I'm not sure they need "Is *State*". I would prefer either "*State*" or "*State*?" 

* Disabled?
* Bypass Proxy?
* Self-Service Allowed? Note: Business Edition Required

**Comment by gep13** [comment]
@ferventcoder yip, I can fix that up.

> Self-Service Allowed? Note: Business Edition Required

That is a lot of text to put in.  Would you be ok with the latter part going into a tooltip?  And for it to be disabled if not in business edition?

**Comment by ferventcoder** [comment]
Tooltip. They can still set it, but let's put in a tool tip over both the text and the checkbox itself.

**Comment by RichiCoder1** [comment]
@gep13 @ferventcoder It might not be a terrible idea to figure out a tooltip or (?) helper, if only to provide either an explainer or link to docs for some of these properties. Currently you have to have some knowledge of sources to understand these properties. Or to run `choco source --help`, which defeats the purpose of the GUI :P

**Comment by ferventcoder** [comment]
Even better - having a help menu that pulls up, running `choco source --help` and converting the markdown in the same way we do when converting the output for the docs part of the wiki/website.

And yes, tooltips are awesome as well. Thinking out loud,  link up the name to the option on CLI and parse the description out of the CLI return.

**Comment by RichiCoder1** [comment]
We don't technically have access to CLI output after the rewrite ;). But I do believe that we can pull the description info though lib. Will have to look...

**Comment by ferventcoder** [comment]
The info is available in each command. :)

**Comment by RichiCoder1** [comment]
This is good now, right?

**Comment by mwallner** [comment]
LGTM, altough we've got a little alignment issue with the German (long) texts ... 
-> will handle in follow-up issue
![image](https://user-images.githubusercontent.com/5354972/30794330-d1f53f60-a1c7-11e7-96d9-1043e4af3998.png)
