### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by DrYSG** [chocolatey/ChocolateyGUI#426]
For some reason, unlike the powershell version, the proxy credentials are not being picked up.

I have CNTLM running at http://localhost:3128 is there a way to get it to use that, so that I can use this at work? alternatively can you pick up the proxy info from internet explorer settings?

**Comment by gep13** [comment]
Can you please confirm what version of ChocolateyGUI you are using?

**Comment by DrYSG** [comment]
Win10 Enterprise version 1607
Chocolatey 0.10.3
ChocolateyGUI 0.13.2

settings seems to only allow me to specify the source url and name.

Steps to reproduce:

1. Start ChocolateyGUI (starts file and shows local installs)
2. Switch from "This PC" to Chocoately

I get an except window popup (Unhandled exception)
![capture](https://cloud.githubusercontent.com/assets/2865368/24051820/c244d760-0b09-11e7-817d-501d05ed8e81.PNG)

**Comment by DrYSG** [comment]
We have a pretty violent firewall here, but I have been able to easily get everything to get around it by installing a local proxy called CNTLM http://cntlm.sourceforge.net/  which if you point any program that does not grab the internet explorer credentials at, will automatically add the credentials and user-agent to the outgoing HTTP request (I can confirm this with fiddler).

**Comment by gep13** [comment]
@DrYSG can I get you to try out the pre-release version?  Installation instructions are here:

https://github.com/chocolatey/ChocolateyGUI#installation

**Comment by DrYSG** [comment]
@gep13 


I tried the pre-release version (0.14.0-unstable0244) and the problem no longer occurs. I don't see it going through my local CNTLM, so I assume you are picking up the proxy credentials from Internet Explorer.

**Comment by gep13** [comment]
ChocolateyGUI, the pre-release, does exactly what Chocolatey does.

Going to go ahead and close this out.
