### ISSUE TITLE
More explicitly call out OS support.

### ISSUE THREAD

**Issue by DrYSG** [chocolatey/ChocolateyGUI#427]
Your help page does not indicate it, but this program does seem to work on windows 10. Maybe add this to the README

**Comment by gep13** [comment]
>@DrYSG said...
Your help page 

Just to confirm, which page are you referring to?

**Comment by DrYSG** [comment]
Ah, not the github page, but I found your program from the packages description that is at:


https://chocolatey.org/packages/ChocolateyGUI

The text below implies that win10 is not supported:

```
Due to a dependency on the Windows Management Framework, this package will 
only work correctly on Windows 7 SP1, Windows Server 2008 R2 SP1 and Windows 
Server 2008 SP2 and above.
````

**Comment by gep13** [comment]
Hmmm, it does say `and above.` but I agree, perhaps this could be worded better.
