### ISSUE TITLE
install folder

### ISSUE THREAD

**Issue by DrYSG** [chocolatey/ChocolateyGUI#428]
Any chance of adding an option to specify the install folder. Or if one has the pro version of chocolately, to use their features for install folder?

**Comment by gep13** [comment]
@ferventcoder I have just tried the following:

![image](https://cloud.githubusercontent.com/assets/1271146/24056391/5b379ef4-0b3b-11e7-8a36-7fcebf0e89ac.png)

And the installation directory wasn't affected, it still went to the default location.  Is this:

https://github.com/chocolatey/ChocolateyGUI/blob/develop/Source/ChocolateyGui.Install/Product.wxs#L52

the problem?

If I run this:

![image](https://cloud.githubusercontent.com/assets/1271146/24056560/20424dca-0b3c-11e7-8983-0259fcda2ee1.png)

Then it installs to the specified location:

![image](https://cloud.githubusercontent.com/assets/1271146/24056553/17063eb0-0b3c-11e7-9043-d29f8db2721f.png)

So for now, @DrYSG, you can install to an alternative location using:

`choco install chocolateygui --source https://www.myget.org/F/chocolateygui/ --
pre --ia="INSTALLFOLDER=c:\temp"`

**Comment by gep13** [comment]
@ferventcoder i.e. is out WiX project just not particularly well written?  That is entirely possible as I did the first version of it 😄

**Comment by DrYSG** [comment]
actually, I was not asking about chocolateyGUI installing a different folder, but allowing  rather that when I use the chocolateyGUI to do an install of some other package, that I have the option to change the install folder.

**Comment by gep13** [comment]
@DrYSG oh, I see....

Sorry, yes, that is likely something that we will be adding in at some point.

**Comment by ferventcoder** [comment]
@gep13 The licensed edition should pick up other MSI properties and switch to them over TARGETDIR if they are available. Let's ensure INSTALLFOLDER is one of them.

**Comment by ferventcoder** [comment]
Looks like it is looking for INSTALLDIR - I will ensure the next version also looks for INSTALLFOLDER.

**Comment by gep13** [comment]
Nice one! Not sure where I got that variable name from initially. Must have copied it from somewhere.

**Comment by gep13** [comment]
This is really a duplicate request to what is earmarked for this issue:

https://github.com/chocolatey/ChocolateyGUI/issues/545

As such, I am going to close this issue out.
