### ISSUE TITLE
0.14 package details view missing 'Gallery' link

### ISSUE THREAD

**Issue by welwood08** [chocolatey/ChocolateyGUI#430]
Firstly, I've been using the pre-release version 0.14.0-unstable0245 for a few weeks now and have found it to be a significant improvement over the previous stable version (0.13.2). This is the most noticeable quibble I have with what's changed so far.

When viewing a package's details, occasionally I found it useful to be able to directly open the package's gallery page in my browser. Usually it's because either I'm having a problem with the Chocolatey part of the package, or I've learned through other channels that the package is out of date. It's useful to quickly see if there's any discussion about problems at the bottom of the gallery page, there's normally also a link to get to the package source to search for (and submit) issues, and there's multiple options for informing the maintainer of the outdated package (ie through chocolatey.org or an issue on the source repo).

I can't tell if this feature was intentionally removed or just an oversight during the changes, so here's this issue just in case it was the latter.

**Comment by gep13** [comment]
Also, check to see why the `Report Abuse` link was removed.

**Comment by gep13** [comment]
@welwood08 thank you for raising this issue.  The Gallery link hasn't actually been "removed" as such...

All of the code to show and display the Gallery link is still there, it is just that the Url is no longer being populated.  Between version 0.13.2 and 0.14.0 (which actually became 0.15.0 for "reasons") we switched from getting the package information from the gallery oData feed, to using the Chocolatey.Lib (which is the same as what choco.exe is using).  As a result, some information such as the GalleryDetailsUrl, the ReportAbuseUrl, the DownloadCount, etc, are no longer populated, and as a result, not shown in Chocolatey GUI.

I am looking into whether or not we can retrieve some of this information for display.

**Comment by gep13** [comment]
@welwood08 I take it back, the information was there, it just wasn't being mapped properly.  This has been corrected, and should be available in the next release of Chocolatey GUI.

**Comment by gep13** [comment]
Semi-related to this, in the local package source view, the package size was being incorrectly displayed, showing a value of -1.  This has also been corrected, and again will be included in the next release.
