### ISSUE TITLE
Add different background for outdated packages

### ISSUE THREAD

**Issue by silverqx** [chocolatey/ChocolateyGUI#431]
Would be nice to  have different background for packages, which are outdated.

Something like this:

![2017-04-26- 1](https://cloud.githubusercontent.com/assets/86900/25446738/ccab0b48-2ab2-11e7-8d71-5d6cdb30e7ab.png)

**Comment by silverqx** [comment]
thx 👍

**Comment by silverqx** [comment]
out of date tag looks good, thx

**Comment by gep13** [comment]
@silverqx thanks for confirming!
