### ISSUE TITLE
Limit non-admin list to self service only.

### ISSUE THREAD

**Issue by lukemgriffith** [chocolatey/ChocolateyGUI#432]
Currently with feature useBackgroundServiceWithSelfServiceSourcesOnly enabled, a user without admin permissions can do choco list and return items from all configured sources by default, including packages from sources that are not configured for self service.

Would it be possible for non elevated users to only have self service packages returned, as its the only items they can actually install.

**Comment by ferventcoder** [comment]
If the background service is on and the user is a non-admin that is.

**Comment by RichiCoder1** [comment]
I can look into this after we do #382. Would chocolatey gui do anything? Or would choco.lib be smart enough to only pass back relevant sources & packages?

**Comment by ferventcoder** [comment]
@RichiCoder1 Chocolatey.lib would be smart enough only to pass back relevant sources.

**Comment by ferventcoder** [comment]
I'll start adding the details for this feature

**Comment by RichiCoder1** [comment]
@ferventcoder Is this feature complete?

**Comment by ferventcoder** [comment]
I started on this, there is still one component missing here.

**Comment by gep13** [comment]
@ferventcoder @RichiCoder1 should we bump this to the next release of Chocolatey GUI?

**Comment by ferventcoder** [comment]
Yes, please.

**Comment by gep13** [comment]
@ferventcoder am I right in saying that this will be included in the change that I am away to make for using `source_list` rather then reading the available sources directly from the Chocolatey Configuration file?

**Comment by ferventcoder** [comment]
@gep13 @lukemgriffith I want to say this is covered by the change to not see admin only - that's where we've decided to hide those sources that would be admin only. Non-admins would see self-service and normal sources.

**Comment by ferventcoder** [comment]
I want to say that's where this conversation ended up.
