### ISSUE TITLE
System.IO.FileFormatException: File Contains Corrupted Data - Crashes ChocolateyGUI instantly upon launch

### ISSUE THREAD

**Issue by Hexexpeck** [chocolatey/ChocolateyGUI#437]
I recently installed ChocolateyGUI using the .msi from the releases page [here](https://github.com/chocolatey/chocolateygui/releases/latest) and the install seemed to successfully complete (no errors encountered at all)

However, when I launch ChocolateyGUI upon installation, I get the error shown in the screenshot attached.
![screencap](https://cloud.githubusercontent.com/assets/20467576/26031202/68af8cfc-3838-11e7-928a-1f194631d90c.png)
I don't know why this is, maybe either my Chocolatey or my ChocolateyGUI installation(s) are corrupt?

I am running this on a Windows 10 x86 computer.

Also, attempting to install ChocolateyGUI via the command-line returns the following:
```
C:\Windows\system32>choco install chocolateygui
Chocolatey v0.10.5
Installing the following packages:
chocolateygui
By installing you accept licenses for the packages.
Unable to read package from path 'ChocolateyGUI\ChocolateyGUI.nupkg'.
```
Any help here would be appreciated!

**Comment by Hexexpeck** [comment]
Gonna close this as I have gotten it to successfully work

**Comment by RichiCoder1** [comment]
Ohh? Sorry, I didn't get to this sooner. What ended up being the issue?

**Comment by Hexexpeck** [comment]
Initially, ChocolateyGUI loaded up and said that a file(?) seemed to be corrupted. All it took was me deleting the ChocolateyGUI folder from C:\Chocolatey\lib-bad and reinstalling ChocolateyGUI and it worked again

**Comment by RichiCoder1** [comment]
That's really weird. Package must have somehow gotten corrupted during the pull. Glad you resolved it :)
