### ISSUE TITLE
Package refresh should be automatic and hidden.

### ISSUE THREAD

**Issue by billw2012** [chocolatey/ChocolateyGUI#439]
Why do I have to click "refresh packages". When would I not want them refreshed? Especially annoying if you are updating individual packages, using the Show Only Packages with Updates checkbox. It appears as if the update failed because the item stays in there.

**Comment by RichiCoder1** [comment]
Package refresh is currently a somewhat expensive two part process, so we've tried to avoid doing it unnecessarily. Plus thanks to some code debt (sorry), the refresh isn't 100% clean. That being said, it has gotten less expensive recently, so I could look into do a semi-regular background refresh.

The second half, though sounds like a bug. *Anytime* you do a package operation, it should refresh the package details in the list. Is that not the behavior you're seeing? If so, could you file a bug w/ the steps to reproduce?

**Comment by daggmano** [comment]
I can confirm this issue. When updating a package, ChocoGUI returns with the full list of packages even though Show Only Packages with Updates is ticked. When the checkbox is unticked and reticked, the recently updated package still shows with the old version. Clicking Refresh Packages does refresh the version, but again shows all packages even though Show Only Packages with Updates is ticked, requiring a further unticking / reticking.  Is this not what you see?

**Comment by RichiCoder1** [comment]
This should actually be fixed by 5b758857.
