### ISSUE TITLE
Fix inconsistencies in German translation

### ISSUE THREAD

**Issue by mwallner** [chocolatey/ChocolateyGUI#443]
discovered several inconsistencies between the English and German version, also in some cases a 'hard translation' is not the way to go!
example: "pin/unpin" should not translate to "anheften/..?" - but rather to "Version fixieren/ Updates zulassen"
- will post decisions as comments on this issue

**Comment by mwallner** [comment]
* pin / unpin
"pin" translates to "fix the version of a package" / "forbid updates for a package" - "unpin" the opposite (allowing updates again)
I've picked the translation "Updates sperren" (forbid udpates) for pin and "Updates zulassen" (allow updates) for unpin

* author
"author" translated to "Autor", but "Urheber" fits better (orignator)

**Comment by RichiCoder1** [comment]
I'm all for translations that make intuitive sense over literally translations
