### ISSUE TITLE
Random Chocolatey GUI crash

### ISSUE THREAD

**Issue by mwallner** [chocolatey/ChocolateyGUI#448]
![image](https://user-images.githubusercontent.com/5354972/26970966-9a86d2de-4d0b-11e7-8d9c-b1956beb1627.png)

only happened once so far (cannot reproduce)
version is current develop (eb464a1381ce19a5d9d2b3904876fb06045f14ec)

**Comment by RichiCoder1** [comment]
Fixed since we've moved away from subprocess.
