### ISSUE TITLE
Chocolatey GUI crashes when closed while still loading packages

### ISSUE THREAD

**Issue by mwallner** [chocolatey/ChocolateyGUI#449]
![image](https://user-images.githubusercontent.com/5354972/26971000-c9b21956-4d0b-11e7-9f19-3716bfad04c1.png)

Steps to reproduce:
* open ChocolateyGUI
* close the GUI (x) while still fetching package-lists

version is current develop (eb464a1)

**Comment by RichiCoder1** [comment]
I probably just need to shutdown the log pipe when I get the kill signal.

**Comment by gep13** [comment]
@mwallner I am going to go ahead and close this one out, as I think it has been taken care of in the refactoring.  Let us know if this is still an issue.
