### ISSUE TITLE
Chocolatey GUI crashes when started from another working-directory

### ISSUE THREAD

**Issue by mwallner** [chocolatey/ChocolateyGUI#450]
![image](https://user-images.githubusercontent.com/5354972/26971075-129e42c0-4d0c-11e7-96cf-da24a6e40f81.png)

ChocolateyGUI instantly crashes when opened from another directory - i.e. cwd is `C:\` - then the call to `C:\Program Files (x86)\ChocolateyGUI\ChocolateyGui.exe` results in the exception above.

When ChocolatyGUI is started from another process, and the `StartupInfo.WorkingDirectory` (in whatever language) is set to 'C:\Program Files (x86)\ChocolateyGUI\` everything works as expected.

version is current develop (eb464a1)

**Comment by RichiCoder1** [comment]
Hmmm. Cef automagically looks for it's parts relative to CWD I guess. I think there's a way to code that to point to the correct directory though.

**Comment by drfrpjr** [comment]
I tried starting ChocoGUI right from C:\Program Files (x86)\ChocolateyGUI and it crashes as above.

Where do you set the variable StartupInfo.WorkingDirectory?

Thanks.

**Comment by mwallner** [comment]
can you provide a screenshot of the exception message your're getting? / there are a couple of other crashes as well (i.e. when you've already got a GUI running) - this one should really only when the GUI is called from another directory.

**Comment by drfrpjr** [comment]
Hi,

Below is the screenshot directly starting the app from Powershell in the directory "C:\Program Files (x86)\ChocolateyGUI". Thanks.

![image](https://user-images.githubusercontent.com/14821996/28380526-a0adcf84-6c85-11e7-9d6e-99688444542b.png)

**Comment by RichiCoder1** [comment]
Are you using a company machine? Looks like you have the .Net FIPS Algorithm Check enabled.

**Comment by drfrpjr** [comment]
Yes, this is a company machine. Is turning on the .Net FIPS Algorithm Check a problem? If so, is there a workaround?

----Fred

**Comment by gep13** [comment]
@RichiCoder1 Do you have any thoughts on this one?  I have just tried this out after the refactor, and I am still getting Cef Exceptions in the log file.

**Comment by RichiCoder1** [comment]
The issue that was affecting @drfrpjr should be resolved. And I think I have a fix for the original issue. Will issue a PR later.

**Comment by gep13** [comment]
@RichiCoder1 were you able to have a look at what was required here? Thanks.

**Comment by RichiCoder1** [comment]
Let me know if you're still getting this issue with the latest pre @mwallner

**Comment by mwallner** [comment]
working in latest dev :-)
