### ISSUE TITLE
Please run processes on another thread

### ISSUE THREAD

**Issue by daggmano** [chocolatey/ChocolateyGUI#453]
Not sure if this has been covered, but it appears any processes (refreshing versions, updates, installs, etc) occur on the UI thread, locking the window.  It would be nice to be able to at least reposition the window (or minimise it) while it is working away at something.

**Comment by RichiCoder1** [comment]
They do, actually. A whole other process actually. I'm assuming you're referring to the progress modals however? I agree that the currently implementation can be frustrating (especially since it covers the window grab bar).

**Comment by daggmano** [comment]
Proves you can never make assumptions of implementation based on behaviour!  But yes, to be able to minimise / move the window while the modal dialog is showing would be an improvement.

**Comment by RichiCoder1** [comment]
Looks like we just need to add `ShowDialogsOverTitleBar`. Will do so now.
