### ISSUE TITLE
Add export/import list of installed items

### ISSUE THREAD

**Issue by superbonaci** [chocolatey/ChocolateyGUI#457]
Please add an option to import/export the list of installed apps. This makes much easier to migrate to a new computer.

**Comment by astrom0** [comment]
This isn't an issue.

Did you check further afield?
[Installing Packages](https://chocolatey.github.io/usage.html#installing-packages)

Get yourself the [gui](https://chocolatey.org/packages/ChocolateyGUI) and it's a quick click to export the package config. Use the details above to import them to another machine. Easy.

**Comment by gep13** [comment]
@superbonaci I think I have to agree with @astrom0 here.  There is already the ability to export the list of currently installed packages as a packages.config file.  From there, you can then pass this packages.config file to the choco command line, which would install all of those application, including Chocolatey GUI.

If you are not happy with this workflow, then please feel free to respond to this issue, and we can discuss further.

**Comment by astrom0** [comment]
@bcurran3 - thanks. I'll check it out. Reads like a worthwhile improvement.

**Comment by superbonaci** [comment]
@bcurran3 thank you very much!

**Comment by AresS31** [comment]
Why not natively supporting the export feature with the CLI as some people (me for example) would rather use it over the GUI?
Additionally, when SSHing into a remote Windows machine we should be able to export all the installed packages as well.

**Comment by AdmiringWorm** [comment]
@AresS31 supporting exporting packages is in progress for the CLI.
See the following PR for the work in progress: https://github.com/chocolatey/choco/pull/1825

**Comment by AresS31** [comment]
Thanks @AdmiringWorm nice to know that this feature is coming.
