### ISSUE TITLE
ChocoGUI Crash on Startup -- Windows 10

### ISSUE THREAD

**Issue by drfrpjr** [chocolatey/ChocolateyGUI#458]
I have been using Choco and ChocoGUI -- the latest versions -- with Windows 10 on a Surface. Works fine. Powershell version=5.0.10240.17443

However, I just got a new desktop PC and while Choco is fine, ChocoGUI viciously crashes with the error below. This is running as administrator, etc. I think I have tried everything else above as well. Powershell version=5.1.14393.953

I included the Powershell versions because that seems to be the only differences between the two systems in terms of dependencies. 

Any advice?

Thanks. 

![image](https://user-images.githubusercontent.com/14821996/28343669-720031b6-6bec-11e7-9bb6-4b01457d5cc8.png)

**Comment by TheVakman** [comment]
I'll add that this also occurs over here too.
It seems to only crash when selecting an internal source. My source is running Chocolatey Server. 
Issue does not occur in the pre-release version from MyGet.

**Comment by wjk** [comment]
@drfrpjr @TheVakman This actually isn't what you think it is. The problem (as evidenced in that TLDR error dialog) is that the Choco GUI client is trying to use the MD5 crypto algorithm on a system with Windows' FIPS mode feature enabled. When FIPS mode is enabled, the .NET Framework will refuse to load certain crypto algorithms, instead throwing an exception. This has nothing to do with one's package source, and entirely with an incompatibility between ChocoGUI and the security policies of your organization.

This problem can be corrected by placing the following code in [the App.config file for ChocolateyGUI](https://github.com/chocolatey/ChocolateyGUI/blob/develop/Source/ChocolateyGui/app.config), and then rebuilding the project from source. I got this code from the App.config file for the choco checksum tool. You can see it [here](https://www.chocolatey.org/packages/chocolatey/0.10.7) (click the "Show" link next to the file called `checksum.exe.config`).

```xml
<configuration>
    <runtime>
        <enforceFIPSPolicy enabled="false"/>
    </runtime>
</configuration>
```

I am not certain as to ChocolateyGUI's policies regarding FIPS mode compatibility. If anyone wants me to submit a PR with this change, please let me know. Hope this helps!

**Comment by drfrpjr** [comment]
William,

Thanks for the information. I actually did not build ChocolateyGUI, but installed it using Choco. Any chance of making this the default in the ChocolateyGUI build?

That said, what compiler tools are needed to compile from source?

----Fred

**Comment by wjk** [comment]
@drfrpjr You'll need Visual Studio 2017 (the free Community edition is OK to use here, as this is an open-source project, and the Community edition's license terms specifically allow use for open-source development, but of course a higher edition will do if you have a license).

What you'll want to do is install VS2017 (you'll need to select at least the .NET Desktop Development workflow during the installation process, or else the project won't load). Once that is done, clone the ChocolateyGUI repository and run the `build.ps1` script in the repository root. Once that has finished running, you can open `Source\ChocolateyGUI.sln` and edit away. You will need to add the `<enforceFIPSPolicy />` tag from my above post into the `Source\ChocolateyGUI\app.config` file (try inserting it directly after [line 3](https://github.com/chocolatey/ChocolateyGUI/blob/develop/Source/ChocolateyGui/app.config#L3)), and then build the entire solution.

**Comment by drfrpjr** [comment]
I have VS2015 … will that work?

-----Fred

**Comment by wjk** [comment]
It should, but I haven't been able to test it. The main reason I recommended VS2017 was because the solution file had a VS2017 header in it. However, a cursory search reveals no VS2017-specific project features. Try it and let me know how it goes. Thanks!

**Comment by drfrpjr** [comment]
Thanks, I’ll give it a try on a personal device with VS17 … and let you know what happens!

----Fred

**Comment by TheVakman** [comment]
@wjk Thanks. I'm okay with using the pre-release version as that's the default in that version. I just wanted to note that it didn't happen on the pre-release version and now we know why. I'm very curious when that one will replace the older version.

**Comment by RichiCoder1** [comment]
I took @wjk and simply disabled the check in d365ec335. It doesn't make any sense to respect this policy for ChocolateyGUI and even microsoft recommends against it.

**Comment by drfrpjr** [comment]
Is that fix reflected in a ChocolateyGUI update with Choco?

----Fred



Sent from my iPad

On Sep 26, 2017, at 12:39 PM, Richard Simpson <notifications@github.com<mailto:notifications@github.com>> wrote:


I took @wjk<https://github.com/wjk> and simply disabled the check in d365ec3<https://github.com/chocolatey/ChocolateyGUI/commit/d365ec335e349b22f5aeb0402856b8f1895cdd36>. It doesn't make any sense to respect this policy for ChocolateyGUI and even microsoft recommends against it.

**Comment by RichiCoder1** [comment]
It should be in the latest prerelease.

**Comment by hltdev8642** [comment]
> @drfrpjr @TheVakman This actually isn't what you think it is. The problem (as evidenced in that TLDR error dialog) is that the Choco GUI client is trying to use the MD5 crypto algorithm on a system with Windows' FIPS mode feature enabled. When FIPS mode is enabled, the .NET Framework will refuse to load certain crypto algorithms, instead throwing an exception. This has nothing to do with one's package source, and entirely with an incompatibility between ChocoGUI and the security policies of your organization.
> 
> This problem can be corrected by placing the following code in [the App.config file for ChocolateyGUI](https://github.com/chocolatey/ChocolateyGUI/blob/develop/Source/ChocolateyGui/app.config), and then rebuilding the project from source. I got this code from the App.config file for the choco checksum tool. You can see it [here](https://www.chocolatey.org/packages/chocolatey/0.10.7) (click the "Show" link next to the file called `checksum.exe.config`).
> 
> ```xml
> <configuration>
>     <runtime>
>         <enforceFIPSPolicy enabled="false"/>
>     </runtime>
> </configuration>
> ```
> 
> I am not certain as to ChocolateyGUI's policies regarding FIPS mode compatibility. If anyone wants me to submit a PR with this change, please let me know. Hope this helps!

Thank you!! this works perfectly. I just edited the ChocolateyGUI.exe.config file and added that and it works now.

**Comment by drfrpjr** [comment]
Hi,

Thanks for the update. Actually, Chocolatey GUI has been fixed for some time now. I am not sure what changed it, but it has been working for at least a year now.

Thanks,

--Fred
________________________________
Frederick R. Phelan Jr., Ph.D.
________________________________
NIST
100 Bureau Dr., STOP 8542
Gaithersburg, MD 20899-8542
301.975.6761
301.975.4924 (FAX)

frederick.phelan@nist.gov<mailto:frederick.phelan@nist.gov>

My WebEx<https://nist-secure.webex.com/meet/frederick.phelan>

My NIST Home Page<https://www.nist.gov/people/phelan-jr-frederick-r>

WebFF Project Page<https://mgi.nist.gov/webff-force-field-repository-organic-and-soft-materials>
[mml]
-Omnia in mensura et numero et pondere disposuisti. (Sapientiae 11:21)-
