### ISSUE TITLE
Updating a package doesn't honour "Show Only Packages with Updates" when list is refreshed

### ISSUE THREAD

**Issue by nickdodd79** [chocolatey/ChocolateyGUI#462]
When I select "Show Only Packages with Updates" it displays a list of packages that can be updated. I then select one to update and choco goes off and does it's thing. Once done the installed packages list is refreshed, but the "Show Only Packages with Updates" flag is ignored even though it is still ticked. I need to untick the checkbox, click the "Refresh Packages" button and then retick the checkbox to get the filtered list again. Just unticking and reticking doesn't remove the updated package from the list.

**Comment by gep13** [comment]
@nickdodd79 Thank you for reporting the issue.  This should now be taken care of.  If you could take a look at the latest version of Chocolatey GUI from the MyGet Feed and let us know, we would really appreciate that.  Thanks.
