### ISSUE TITLE
Seemingly Random Chocolatey GUI Crash

### ISSUE THREAD

**Issue by TheVakman** [chocolatey/ChocolateyGUI#470]
![randomchocoerror](https://user-images.githubusercontent.com/18545156/30644811-a721b370-9de1-11e7-96d5-94f03c196719.PNG)

This one doesn't seem to affect any particular version of 0.14.x as I've had it happen on some older ones, .290 and .300.

It happens when I try to view details for a package in ChocolateyGUI. After it crashes, if I relaunch, the same package details display without any issue. Therefore, I'm unable to reproduce this error consistently.

**Comment by RichiCoder1** [comment]
This will be resolved by #466 I believe.

**Comment by RichiCoder1** [comment]
This should be resolved in the latest prerelease. Let me know if you still see this issue!
