### ISSUE TITLE
Self Service within ChocolateyGUI

### ISSUE THREAD

**Issue by TheVakman** [chocolatey/ChocolateyGUI#473]
I'm aware that using self service by non-admins within ChocolateyGUI is being worked on for licensed users but I didn't see an official bug logged for this. 

As such, I just want to log it as it's a feature that I'm very interested in utilizing.

FYI, I can confirm in 0.14.0-unstable0343 that I am unable to test again for this the Self Service portion due to the crash when launching as a non-administrator (#469).

**Comment by RichiCoder1** [comment]
I believe this is being actively worked on. /cc @gep13 @ferventcoder

**Comment by gep13** [comment]
@TheVakman based on closing of the other issue, I am going to go ahead and close out this one as well.

This functionality was demonstrated in this video here: https://youtu.be/k5VLMIeMRYE?t=3904

**Comment by TheVakman** [comment]
Thanks @gep13 - meant to close before, it is functional in .345 and up.

**Comment by gep13** [comment]
@TheVakman thank you for confirming!
