### ISSUE TITLE
German texts in settings page are to long

### ISSUE THREAD

**Issue by mwallner** [chocolatey/ChocolateyGUI#478]
![image](https://user-images.githubusercontent.com/5354972/31264282-3af93216-aa68-11e7-9433-c536ab80c3c0.png)

**Comment by mwallner** [comment]
just bumped into this - will fix this weekend.
two possible solutions: 
1. make texts shorter
2. right-align checkboxes to get a little more space in this dialog

**Comment by mwallner** [comment]
bump @RichiCoder1 - what would you prefer?

**Comment by punker76** [comment]
@mwallner I prefer playing with `Grid.IsSharedSizeScope` and `SharedSizeGroup` for the columns...

![2017-10-06_10h11_06](https://user-images.githubusercontent.com/658431/31268948-cd23f7c8-aa7e-11e7-93f1-319b0b25c221.png)

So it should now work with all languages.

**Comment by mwallner** [comment]
thanks! :-) - fixed with GH-478

**Comment by RichiCoder1** [comment]
@punker76 I didn't even realize that was a possibility! That's awesome.
