### ISSUE TITLE
Add translations for Tooltips

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#486]
Some new tooltips were added in this PR: https://github.com/chocolatey/ChocolateyGUI/pull/482

Which will need to be translated into the different languages that we now support.

**Comment by gep13** [comment]
@magol @AdmiringWorm @mwallner 

If I could get you to cast your eyes over this issue when you have some time, I would really appreciate it.

Thank you!

**Comment by AdmiringWorm** [comment]
@gep13 I'll try to have a look at it sometime tomorrow.

**Comment by RichiCoder1** [comment]
Nice catch. Completely spaced on making those resources.

**Comment by gep13** [comment]
>@RichiCoder1 said...
Nice catch. Completely spaced on making those resources.

Not a problem.  Don't think it should hold up the release at this point, we can always do a quick 0.15.1 release to include them once they are ready.

**Comment by AdmiringWorm** [comment]
Seems like I'm unable to translate anything today unfortunately, however I noticed that those tooltips haven't yet been made translatable. Currently they are just hard coded strings without being binded to the resource file (unless I'm missing something).

**Comment by mwallner** [comment]
I'm on it - will put in PR shortly (en & de)
