### ISSUE TITLE
Easy Branding of Chocolatey GUI

### ISSUE THREAD

**Issue by TheVakman** [chocolatey/ChocolateyGUI#488]
We would like to brand ChocolateyGUI using our company logo somewhere in the application that is deployed to our users.

Perhaps, this could be a licensed only feature?

**Comment by gep13** [comment]
@TheVakman this is definitely something that we are thinking about. Where exactly were you thinking that your own logo would appear?

**Comment by TheVakman** [comment]
@gep13 I'm pretty open. Perhaps, in the bottom left?

Unless, you're open to replacing the Chocolatey logo itself for licensed users.

**Comment by RichiCoder1** [comment]
Hmm. At least on machines with small source sets, we do have a 250 x something space that's pretty much unused. No reason we couldn't dynamically load a PNG into that space.

**Comment by TheVakman** [comment]
That would work for me!

**Comment by gep13** [comment]
@ferventcoder...

What are your thoughts on this?

> Unless, you're open to replacing the Chocolatey logo itself for licensed users.

**Comment by ferventcoder** [comment]
Not completely sure what that means.

**Comment by TheVakman** [comment]
@ferventcoder I was suggesting the top left have an option for company branding (where the Chocolatey logo currently sits). It could have something like "Powered by Chocolatey" underneath the company branding that the ChocolateyGUI user has replaced the main logo with. It might be a good selling point for licensed users.

My initial suggestion was that the bottom left be used for company logos - this is a good option too.

**Comment by ferventcoder** [comment]
I see. Great idea.

**Comment by gep13** [comment]
Ok, so I am starting to think about this again, and I want to get some more details about exactly what is required here.

* How are where should this branding be applied?
  * Through the settings screen?
  * Through convention? i.e. placing icon in a specific location with name?
* What exactly should be branded?
  * Font?
  * Colour?
  * Anything else?
* Where should the above be set?
  * Through the settings screen?
  * via a configuration file that is read at run time?

Is branding something that anyone is allowed to apply?  Or is this a licensed Chocolatey feature?

@punker76 could you jump in here with what is/isn't possible?

**Comment by TheVakman** [comment]
@gep13 Sure, let me know if you want any more information after this too!

- I'd prefer through convention. C:\ProgramData\Chocolatey GUI\Icon or something similar. The setting screen would not great for deployment.

- In addition to the logo itself, I would not mind changing the colour of the overall interface but this would be a nice to have - the logo is much more important. I'm not at all concerned with changing the font.

- Without a doubt, in a configuration file. If it's through the setting screen only, that wouldn't really be helpful from a deployment perspective.

- Personally, I'd suggest having this as a licensed feature to add to the reasons to purchase a subscription. However, I'm saying that as a licensed user but I do think that it makes sense for it to be a licensed feature.

**Comment by exportgoldman** [comment]
We would like to with the Chocolatey for Business be able to change the big Chocolatey logo in the top left hand side. Management are very keen on this.

**Comment by exportgoldman** [comment]
If we were to fund this work to get the branding work completed (including replacing the branding on the big top left Chocolatey logo could we get a estimate how much this would be to fund?

**Comment by ferventcoder** [comment]
Hello @exportgoldman - please reach out directly (rob at chocolatey dot io) to discuss. In short, branding ability will be in commercial editions only.

**Comment by gep13** [comment]
@TheVakman @exportgoldman This is going to be implemented as a feature for Chocolatey for Business customers. If you are interested in taking this for a spin, we are almost at the point of having a working beta version ready for testing. Reach out to Chocolatey support through the usual channels for additional information if you are interested.

For now, going to close this issue. Let me know if you have any additional questions.

**Comment by gep13** [comment]
What has been implemented is the ability to change:

* Splash Screen Logo (what is shown when application is loading)
* Image in top left section of the application once loaded
* The icon which is shown in the TaskBar when application is running
