### ISSUE TITLE
Drop support for SVG Icons

### ISSUE THREAD

**Issue by RichiCoder1** [chocolatey/ChocolateyGUI#490]
Currently we support svg icons very well, but this is done by spinning up a mini browser process in the background, loading the svg in a document, and taking a snapshot of it. This is wasn't too ideal, but I did some work around caching and error handling to make it work fairly well. However with the arrival of Markdig.wpf, the only other major reason we had a dependency on CefSharp (Markdown Rendering) is gone. Having tested all other solutions for rendering Svg to images or Xaml (SharpVector, vvvv, and others), I've determined that any other solution is either too heavyweight or error prone.

With that, I am recommending the removal of support of Svg from Chocolatey GUI and recommending that Chocolatey standardize icons and discourage the use of Svg for package icons.

/cc @ferventcoder @gep13

**Comment by ferventcoder** [comment]
@RichiCoder1 look at what Chocolatey.org does for this. I think it would work best.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/chocolatey.org/blob/bef7bea1ba6f32a60b52e209f4152e2a82e48025/chocolatey/Website/Services/ImageFileService.cs#L202-L215
