### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zero77** [chocolatey/ChocolateyGUI#500]
How do I remove a package from chocolatey without uninstalling it.

For example, I am using the standard dropbox, I want to remove it but not uninstall it from chocolatey, and then change it to the beta.
Thanks

**Comment by mwallner** [comment]
Hello @zero77 - I'm don't quite get what you're trying to achieve.. can you eplain in more detail?
additionaly - for such questions please use our gitter chatroom https://gitter.im/chocolatey/choco  - you'll get responses much quicker there!

I'm closing this issue for now, if you're still looking for help, please visit the gitter channel - there'll most likely be folks around 24/7 :-)
