### ISSUE TITLE
Package description should use all available client space

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/ChocolateyGUI#501]
Package description doesn't seemes to be anchored correctly:

![image](https://user-images.githubusercontent.com/2190718/31810521-6825b902-b57c-11e7-8fad-dbc38d3ae4f3.png)

I would expect it to use full available height

**Comment by pascalberger** [comment]
This seems to be still an issue with 0.16.0:

![image](https://user-images.githubusercontent.com/2190718/36311068-57d02f22-132a-11e8-9524-88a0607c649b.png)

**Comment by gep13** [comment]
@pascalberger thanks for following up with this.  @punker76 would you be in a position to look at this?

**Comment by gep13** [comment]
@pascalberger new screenshot:

![image](https://user-images.githubusercontent.com/1271146/56462914-07ac0f80-63c3-11e9-81c7-d727871714b9.png)
