### ISSUE TITLE
Disable "Show Only Packages with Updates" while information is still loaded

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/ChocolateyGUI#502]
After start of Chocolatey GUI it already shows the packages installed, while still a background process is running. If I enable the "Show Only Packages with Updates" checkbox during this time it won't show any package, even if updates are available. As soon as the background process has finished it works.

It would expect the "Show Only Packages with Updates" checkbox to be disabled while a background process is running checking for updates.

**Comment by gep13** [comment]
@pascalberger thank you for raising this issue.  This has been corrected, and it will be available in the next release of Chocolatey GUI.
