### ISSUE TITLE
ChocolateyGUI won't start due to a revoked certificate on win10

### ISSUE THREAD

**Issue by winnieXY** [chocolatey/ChocolateyGUI#505]
I've installed chocolateyGUI 0.15 just today and had problems executing it from the start menu or by clicking on the exe (even as administrator) due to a revoked certificate.  The only way to execute the GUI was bypassing the UAC test and calling the gui from powershell. 

As I think that this is not the desired behaviour here are some more informations about the certificate:
![image](https://user-images.githubusercontent.com/6831918/31861181-e2532ac2-b728-11e7-910d-d740736590c3.png)
![image](https://user-images.githubusercontent.com/6831918/31861184-f6edf1c4-b728-11e7-8cf8-ef34c89d2deb.png)
![image](https://user-images.githubusercontent.com/6831918/31861187-0fa78518-b729-11e7-8526-48866b4b1a05.png)
![image](https://user-images.githubusercontent.com/6831918/31861188-18c43efc-b729-11e7-8aee-80a67c3875f8.png)

Please contact me if you need more information in order to fix this issue. 

Thanks for your work!

**Comment by TheVakman** [comment]
Control Panel > Manage Computer Certificates > Trusted Root Certification Authorities > Certificates. Or open MMC and add the snap in.
Do you have DigiCert Assured ID Root CA on this list? If not, do you maintain your own root CA bundles in your environment?

**Comment by winnieXY** [comment]
Hey, 
I've the digicert root CA on this list - see screenshot:
![image](https://user-images.githubusercontent.com/6831918/31863027-1038615e-b748-11e7-9c58-1623cc1a8ac4.png)

And no - I do not maintain an own set of root CA bundles . This should be an absolute standard windows10 installation.

**Comment by ferventcoder** [comment]
I can assure you that the certificate is not revoked. We signed it as a sha256, but maybe we should have signed it with sha1.

**Comment by winnieXY** [comment]
I know ;-) I've checked it manually and the certificate is okay - I don't know why one of my pcs is not accepting the certificate/signature

**Comment by winnieXY** [comment]
However this is not related to ChocolateyGUI alone - The signature on Choco.exe is also not valid

**Comment by ferventcoder** [comment]
You need Digicert SHA2 Assured ID Code Signing CA. You can get that from https://www.digicert.com/digicert-root-certificates.htm (search for "Digicert SHA2 Assured ID Code Signing CA") or download directly from https://www.digicert.com/CACerts/DigiCertSHA2AssuredIDCodeSigningCA.crt.

**Comment by winnieXY** [comment]
I've installed the certificate - nothing changes.

**Comment by Daniel15** [comment]
The digital signature looks fine to me on Windows 10. The DigiCert root CA should be available out-of-the-box on Windows.

@winnieXY Can you try clicking the last tab ("Certification Path" on English versions of Windows) in the certificate details dialog?
![](http://ss.dan.cx/2017/10/Digital_Signature_Details_22-13.57.16.png)

It should say "This certificate is OK" for the status at all three levels.

**Comment by winnieXY** [comment]
On the pc where it is working the certificaton path is correctly shown - on the other not as shown below:
![image](https://user-images.githubusercontent.com/6831918/31902946-e901c564-b826-11e7-8d6d-aa9772dd3fa1.png)

However according to mmc the certificates are installed

**Comment by winnieXY** [comment]
Okay - I'll close this issue. Somehow the Chocolatey Software Certificate was installed as not-trusted. After fixing this everything is working.

If someone else hits the problem: Open mmc -> Add two certificate snap-ins (one for your current account, one for a computer account on the local pc), right-click on both  and search for Chocolatey. The certificate shouldn't pop up! If it pops up in the folder "not-trusted certificates" (translated from german, so wording could be different) - simply delete it. Afterwards it should work
