### ISSUE TITLE
Latest Version not showing

### ISSUE THREAD

**Issue by daggmano** [chocolatey/ChocolateyGUI#506]
The long awaited new version of Chocolatey GUI is here, allowing us to move the window during operations!  Fantastic, and the UI looks good.

Unfortunately, on my PC at least, the Latest Version column remains blank.  Even through I know there is an update awaiting me for at least one package, the column is blank and when I select 'Show Only Packages with Updates', the list is empty.

Let me know if you want any log files (and where they are).

**Comment by RichiCoder1** [comment]
That is very odd. 
Can you produce the output of `choco outdated`?
Do you have any sources aside from the defaults?
Are there errors or warnings in your log files? If so, could you produce them? I'm available on gitter or twitter if they're in anyway sensitive.

**Comment by daggmano** [comment]
Hmm, so there seems to be a path problem, perhaps?

    > choco outdated
    This is try 1/3. Retrying after 400 milliseconds.
     Error converted to warning:
     Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config.22644.update' is denied.
    This is try 2/3. Retrying after 600 milliseconds.
     Error converted to warning:
     Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config.22644.update' is denied.
    Maximum tries of 3 reached. Throwing error.
    Chocolatey v0.10.8
    Outdated Packages
     Output is package name | current version | available version | pinned?

    webstorm|2017.2.4|2017.2.5|false

    Chocolatey has determined 1 package(s) are outdated.

**Comment by RichiCoder1** [comment]
No, the access denied is a weird quirk of Chocolatey of running from an unelevated prompted. For some reason it always tries to update the config. 

That's so weird. The output from `outdated` is correct :\. I'm not sure why it's not showing up.

**Comment by daggmano** [comment]
Happy to wait a day or two to see if anyone else has any issues :)

**Comment by daggmano** [comment]
@RichiCoder1  I uninstalled and reinstalled ChocolatelyGUI and all seems to be working now.  Is it correct that only apps where the latest version is different to the installed version will show version in the Lastet Version column?

**Comment by RichiCoder1** [comment]
Yup, only apps with updates will show updates. Maybe there's some flaw in the logic that Gui uses that's accidentally filtering out webstorm. I'll see if I can reproduce. Thanks for the details!
