### ISSUE TITLE
Use https instead of http

### ISSUE THREAD

**Issue by Opensourcecommunitydevelopment** [chocolatey/ChocolateyGUI#507]
For chocolately main repo updates!

i have tried https://www.chocolatey.org:443/api/v2/ as source but still uses port 80 http for fetching

**Comment by ferventcoder** [comment]
Weird - wonder where it is getting http? Everything uses https.

**Comment by ferventcoder** [comment]
Assuming this was done without the `www.`

**Comment by ferventcoder** [comment]
@Opensourcecommunitydevelopment can you take a look over the day today and see if this resolves itself?

**Comment by gep13** [comment]
@Opensourcecommunitydevelopment I am going to go ahead and close this.  Please feel free to reply back here if things haven't corrected themselves.
