### ISSUE TITLE
Add keybinding for navigating between sources

### ISSUE THREAD

**Issue by RichiCoder1** [chocolatey/ChocolateyGUI#513]
We should pick some bindings for navigating quickly between sources views. Maybe some crtl+something+arrow keybind. Would also be nice to be able to Alt+Num or something to quickly navigate between the first 10 sources (as most people will have between 2-5 at most).

**Comment by gep13** [comment]
Ooo, I like this idea.  On a Windows Machine, you can do Win + 1, to start, or focus, the first pinned item in your taskbar.  Same with Win + 2, etc.  If we equate pinned items on your taskbar to sources in the list, then I think either CTRL + 1,2,3 or ALT + 1,2,3, would make a lot of sense.

**Comment by RichiCoder1** [comment]
Exactly what I was thinking.

**Comment by mwallner** [comment]
I'd vote for CTRL + 1..9 - I think it'd be more consistent with other apps (i.e. googlechrome)

**Comment by huffSamuel** [comment]
Is this still a feature you'd like implemented? I have a branch that implements Ctrl + 1..9 as keybindings for sources. Sources higher than 9 don't have a keybinding.
