### ISSUE TITLE
ERROR Log with Windows 10 Fall Creators Update

### ISSUE THREAD

**Issue by superbonaci** [chocolatey/ChocolateyGUI#514]
[1021/225927.318:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[1025/190006.199:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[1026/210129.467:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain

**Comment by gep13** [comment]
@superbonaci can you confirm what version of Chocolatey GUI you are using?

**Comment by RichiCoder1** [comment]
I've actually seen this error myself, though I've yet to reproduce sadly. Chocolatey GUI 0.15, Windows FCU 1709.

**Comment by TheVakman** [comment]
When I am back from SaltConf17, I'll upgrade a machine internally to see if I can replicate. We will likely be upgrading in the near future so I'll need to make sure it works anyway.

**Comment by gep13** [comment]
@TheVakman @superbonaci I have been running Windows 10 for a while now, and I have yet to be able to reproduce this error.  I am going to go ahead and close off this issue, but please feel free to comment here for further discussion.

**Comment by TheVakman** [comment]
@gep13 Yes, that's a good idea. I meant to comment back that I was unable to reproduce it for them. We're running the v1709 (Fall Creators) on all systems by this point and haven't run into this one.
