### ISSUE TITLE
opera fails to upgrade

### ISSUE THREAD

**Issue by superbonaci** [chocolatey/ChocolateyGUI#515]
choco upgrade opera
Chocolatey v0.10.8
Upgrading the following packages:
opera
By upgrading you accept licenses for the packages.

You have Opera v48.0.2685.50 installed. Version 48.0.2685.52 is available based on your source(s).
Progress: Downloading Opera 48.0.2685.52... 100%

Opera v48.0.2685.52 [Approved]
opera package files upgrade completed. Performing other installation steps.
The package Opera wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): y

ERROR: The term 'Is32BitInstalled' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
The upgrade of opera was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\Opera\tools\chocolateyInstall.ps1'.
 See log for details.
 Unsuccessful operation for opera.
  Rollback to previous version (package files only)?([Y]es/[N]o): y

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - opera (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\Opera\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by superbonaci** [comment]
Reported here:
https://github.com/chocolatey/chocolatey.org/issues/537

**Comment by ferventcoder** [comment]
Packages are separate from the tools - as it looks, this is a package issue. You will need to report that directly to the community maintainers. HTH
