### ISSUE TITLE
Locally installed packages shown for feed

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/ChocolateyGUI#519]
Sometimes the locally installed packages are shown for a feed.

To reproduce:
- Start ChocolateyGUI
- While package for local maschine are still loading switch to feed
- Afterwards it shows the packages installed on the local machine, but in the left sidebar the feed is selected

Event refreshing the view doesn't help and still shows the locally installed packages instead of the packages from the feed

**Comment by gep13** [comment]
This was actually duplicated by the creation of this issue: https://github.com/chocolatey/ChocolateyGUI/issues/807 and was addressed as part of the Chocolatey GUI 0.17.3 release.

As such, I am going to close out this issue.
