### ISSUE TITLE
Allow installing a version besides latest

### ISSUE THREAD

**Issue by RichiCoder1** [chocolatey/ChocolateyGUI#526]
Allow the ability to install a version that isn't the latest, including operations like downgrading (which most times will be uninstall -> install). This should be built as a power user option and should not affect a normal user's flow or perf.

Use case: I was using Node 8.1.0 and I wanted to upgrade. Upgrading to 9.x however was breaking many of my projects, so I wanted to jump to latest 8.x (aka 8.8.0). There was no way to do that through UI.

Possible addendum: Add option to block or warn on "breaking" upgrades, or upgrades with a  major version. Or to only upgrade minor and/or patch versions.

**Comment by gep13** [comment]
I believe that this would be covered by the work that will be done in this issue:

https://github.com/chocolatey/ChocolateyGUI/issues/545

As such I am going to go ahead and close this one out.
