### ISSUE TITLE
Search only on enter / with delay

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/ChocolateyGUI#527]
If I enter something in the search box, search is started, after a very short amount of time after stopping typing. This can be disruptive for the user. I would suggest to either only search on enter (plus add a search button) or increase the time to start the search.

**Comment by punker76** [comment]
@pascalberger Adding a delay for the search is simple to implement, by using the Delay property for the binding (or at code behind at the Observable). But a button would maybe nice for people who use often the mouse... :-D

**Comment by RichiCoder1** [comment]
Actually, the search already has a delay by using an observable. Or at least it should. We could add an enter/button option to short circuit however.

**Comment by pascalberger** [comment]
@RichiCoder1 What's the expected delay? In my case it feels like below 1 second - short enough to already start searching if one needs to think quickly how to spell something.

**Comment by RichiCoder1** [comment]
It's currently a half second I believe.

**Comment by soulflyman** [comment]
It should be possible to disable automatic search after typing completely and only allow search by pressing return or a button.
So the software will be much more accessible for slow typing people. Such as disabled ones, who need to type with a pen.

**Comment by ferventcoder** [comment]
@chocolatey/chocolateygui should we move this to 0.17.0? We'd like to get a release out soon with all of the goodness and improvements that have been implemented so far!
