### ISSUE TITLE
Please stop flashing

### ISSUE THREAD

**Issue by pavelvasev** [chocolatey/ChocolateyGUI#528]
Dear developers!

Very often ChocolateyGUI darkens it's background, for example when perform a Chocolatey task or asking remote API. Then it lightens it again, when operation complete.

Every such switch to dark and then back to light is a strike on users eyes. 

Probably it is better to make it not too dark (say opacity 0.9 instead of 0.3), or better maybe use another way to show that ChocolateyGUI performs blocking operation.

Ready to discuss it. Thank you!

**Comment by gep13** [comment]
@punker76 if/when you have time, would you be able to comment on this one?  Thanks!

**Comment by punker76** [comment]
@gep13 @pavelvasev We can set `OverlayOpacity="0.3"` on the main window:

**Before**

![chocoalt](https://user-images.githubusercontent.com/658431/56737184-26672900-676a-11e9-8327-26164f4b1eca.gif)

**After**

![choconeu](https://user-images.githubusercontent.com/658431/56737197-2bc47380-676a-11e9-926e-8bd384679298.gif)

**Comment by pavelvasev** [comment]
@punker76 Thank you! I think this new variant is better! For an actual value, you may try yourself to use the program at the night (without any lamps around) and I think this will help to find a comfortable one!

**Comment by gep13** [comment]
@punker76 this is a great suggestion!  Let's start with this, and gather some feedback from users, and we can continue to iterate with future issues as they come up.

**Comment by gep13** [comment]
@pavelvasev I have made this change, and it should be available in the next release of Chocolatey GUI.

**Comment by pavelvasev** [comment]
OK guys, thank you very much!!
