### ISSUE TITLE
Move version on Package view to the left column

### ISSUE THREAD

**Issue by punker76** [chocolatey/ChocolateyGUI#530]
I'm very often don't see the version for a package at the package view. So I think it should be better also at the left column where all other numbers are.

Thoughts?

![2017-11-15_09h08_24](https://user-images.githubusercontent.com/658431/32825401-2d1e75b0-c9e5-11e7-8a43-9f0dd83f8187.png)

**Comment by gep13** [comment]
@punker76 I would have no objections to this.

**Comment by AdmiringWorm** [comment]
IMO that would be better, they way it currently is feels out of place for me (mainly because it is shown as a subscript)

**Comment by gep13** [comment]
@RichiCoder1 what were your thoughts on this one?

**Comment by gep13** [comment]
@DamianMaslanka5 thank you very much for taking the time to fix this issue!  😄
