### ISSUE TITLE
Allow users to change the locale to use

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/ChocolateyGUI#533]
One thing I feel is missing is to allow the user to change the locale to display Chocolatey GUI in (I like to change from Norwegian to English and back, depending on the circumstance).

It is possible to allow such an option by doing a naïve check during runtime by checking which locale folder exists: see https://stackoverflow.com/a/32963564 for more info there.

Or creating a static configuration list of the available locales during build, which can be done using the Cake.Transifex addin by using the `TransifexStatus` alias (If I have remembered to correctly implement it, I think I have).

Optimally changing the locale would be dynamic, but that would require quite a few changes, including a a major change in the code base, which probably shouldn't be a priority at this time.
Alternatively, it would notify the user to restart Chocolatey GUI to change the locale.

**Comment by mwallner** [comment]
Hey Kim,
definitely worth having the possibility to switch locales, I'd say we just add a simple dropdown-option in the settings-page, how about that?

thanks for bringing this up again, totally forgot about it

**Comment by mwallner** [comment]
CC @RichiCoder1 & @punker76 you're the WPF pros :-) - do you know if there's an easy way of implementing that?

**Comment by gep13** [comment]
@AdmiringWorm you must be reading my mind!  I was thinking about adding the same issue the other day, but I forgot!

**Comment by AdmiringWorm** [comment]
@mwallner yeah, I think a dropdown box would be a sufficient option to change the locale.

@gep13 I thought I heard someone somewhere mention a issue for this was needed, so you were the one 😸

**Comment by gep13** [comment]
@AdmiringWorm yip, could have been me 😄 

Agree that a dropdown list in the Settings page makes sense.

**Comment by AdmiringWorm** [comment]
Just a small update, I'm actually working on implementing this one (and have for the past couple of days).

Stay peeled at the gitter channel later today, as I'll be showing a little of what I've done so far there.

**Comment by AdmiringWorm** [comment]
Here is my work so far

![dynamic-localization](https://user-images.githubusercontent.com/1474648/50797442-10c21680-12d5-11e9-9ac4-064cc71576d6.gif)

**Comment by gep13** [comment]
Very cool! 👍

**Comment by xmedeko** [comment]
I see the work on this improvement has stopped. IMO dynamic change is not necessary, I would be happy with change locale and restart the app.

**Comment by gep13** [comment]
@punker76 @AdmiringWorm I have added this to the 0.19.0 milestone as I think this would be a great addition to the application.  I will try to free up some time to take a look at this if no-one else gets to it first.

**Comment by punker76** [comment]
@gep13 I have this on my large todo list... My future steps will be to look at the changed in this PR and try to take it to the current source. But if you want to take this, then it's ok.

**Comment by gep13** [comment]
@punker76 I don't have any immediate plans to start working on this, as there are a few others things ahead of it on the list, but I will let you know if I start working on this.
