### ISSUE TITLE
Globalisation - Portuguese

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#542]
@gsferreira has volunteered to help with this translation.

**Comment by gsferreira** [comment]
Working on it :)

**Comment by gep13** [comment]
@gsferreira thank you very much! 😄 Please let me know if you have any questions.

**Comment by gsferreira** [comment]
This is probably a stupid question but I didn't find it... How can I change the language in the ChocolateyGUI?

**Comment by AdmiringWorm** [comment]
@gsferreira currently you would need to modify the code to change the language (unless you have your system locale set to the one you want to use).

See here on the suggested edit to test out a locale:
https://github.com/chocolatey/ChocolateyGUI/issues/397#issuecomment-278137802

**Comment by gsferreira** [comment]
Thanks guys! 
I will test it

**Comment by gsferreira** [comment]
@gep13 Translation complete :) I will try to find someone in a local user group to review it

**Comment by josemaia** [comment]
Hi, I've volunteered. What do I need in order to test?

**Comment by gsferreira** [comment]
@gep13 could you invite @josemaia to transifex?

**Comment by gep13** [comment]
@gsferreira this is great news!  @josemaia you should be able to create an account on Transifex and request membership of the Portuguese Language.  From there, I can get you added to the team to help with on-going translations.

Thank you both for your help with this!

**Comment by gsferreira** [comment]
@rjcarneiro will also help us 😀
@rjcarneiro please read the comment from @gep13 and create the account at https://www.transifex.com/chocolatey/chocolatey-gui/dashboard/

**Comment by gep13** [comment]
@rjcarneiro perfect, I have accepted your request, and added you to the team.  Thanks for helping out!

**Comment by AdmiringWorm** [comment]
@josemaia I've accepted your request as well.

**Comment by gsferreira** [comment]
@gep13 and @AdmiringWorm could you set @josemaia and @rjcarneiro as Reviewers?

**Comment by gsferreira** [comment]
Translation to Portuguese is completed! 😄

**Comment by gep13** [comment]
@gsferreira that is great news! Thank you very much!  This should go out in the next release 😄
