### ISSUE TITLE
Creates two folders - "ChocolateyGUI" AND "Chocolatey GUI"

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/ChocolateyGUI#546]
In ProgramData I'm seeing a `ChocolateyGUI` and a `Chocolatey GUI` folder (note the space). I think the one with the space is created, but it's never used. I see the same in Program Files. It appears we have a lingering thing where one uses the name of the application and the other uses a non-spaced name.

**Comment by gep13** [comment]
@ferventcoder this is a duplicate of this: https://github.com/chocolatey/ChocolateyGUI/issues/534

Which has already been addressed, and should go out in the next release.

**Comment by ferventcoder** [comment]
Ah thanks! I didn't see that one.
