### ISSUE TITLE
Context Menu Position issue in the package details.

### ISSUE THREAD

**Issue by fakoua** [chocolatey/ChocolateyGUI#548]
<img width="910" alt="issue" src="https://user-images.githubusercontent.com/2089210/34313828-f0663db0-e776-11e7-8e77-bf7204813914.png">

There is an office in the context menu position in the package details form.

- Open the details for any package.
- Right click in the details pan.
- The issue should be reproduced.

### Version

ChocolateyGUI Version 0.15.0

**Comment by gep13** [comment]
@fakoua I have just tried to reproduce this problem in the latest pre-release version of Chocolatey GUI and I do not believe that this is an issue anymore.

As such, I am going to close this issue.  Please feel free to re-open if you still believe it to be a problem.

Thanks for reporting the issue.
