### ISSUE TITLE
Upgrade of Chocolatey GUI to 0.15.0 just caused a Chocolatey downgrade to 0.10.3

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/ChocolateyGUI#549]
Something just happened that was VERY strange with ChocolateyGUI and it's dependencies.

Installing ChoclateyGUI just downgraded the version of Chocolatey!

C:\WINDOWS\system32>cup all
Chocolatey v0.10.8
Upgrading the following packages:
all

blah blah

You have ChocolateyGUI v0.13.2 installed. Version 0.15.0 is available based on your source(s).
Progress: Downloading chocolatey 0.10.3... 100%
Progress: Downloading ChocolateyGUI 0.15.0... 100%

chocolatey v0.10.3 [Approved]
chocolatey package files upgrade completed. Performing other installation steps.
Creating ChocolateyInstall as an environment variable (targeting 'Machine')
  Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
WARNING: It's very likely you will need to close and reopen your shell
  before you can use choco.
Restricting write permissions to Administrators
We are setting up the Chocolatey package repository.
The packages themselves go to 'C:\ProgramData\chocolatey\lib'
  (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
  and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName'.

Creating Chocolatey folders if they do not already exist.

WARNING: You can safely ignore errors related to missing log files when
  upgrading from a version of Chocolatey less than 0.9.9.
  'Batch file could not be found' is also safe to ignore.
  'The system cannot find the file specified' - also safe.
WARNING: Not setting tab completion: Profile file does not exist at 'D:\Data - Personal\My Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
Chocolatey (choco.exe) is now ready.
You can call choco from anywhere, command line or powershell by typing choco.
Run choco /? for a list of functions.
You may need to shut down and restart powershell and/or consoles
 first prior to using choco.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The upgrade of chocolatey was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

ChocolateyGUI v0.15.0 [Approved]
chocolateygui package files upgrade completed. Performing other installation steps.
Installing ChocolateyGUI...
ChocolateyGUI has been installed.
  chocolateygui may be able to be automatically uninstalled.
 The upgrade of chocolateygui was successful.
  Software installed as 'msi', install location is likely default.

**Comment by RichiCoder1** [comment]
@gep13 Is this an issue with our nuspec pining a version?

**Comment by pauby** [comment]
This is a very old issue with no updates. I'm going to go ahead and close this, but we can reopen it if necessary.
