### ISSUE TITLE
Package source link for ChocolateyGUI 0.15.0 in nuspec is wrong

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/ChocolateyGUI#550]
current points to: https://github.com/chocolatey/ChocolateyGUI/tree/develop/ChocolateyPackage
instead of: https://github.com/chocolatey/ChocolateyGUI

**Comment by AdmiringWorm** [comment]
seems to be a remnant of before the directory structure changed.
the correct url would probably be:
https://github.com/chocolatey/ChocolateyGUI/tree/develop/nuspec/chocolatey

**Comment by gep13** [comment]
@bcurran3 thank you very much for reporting that!
