### ISSUE TITLE
Hiding "settings" for non-admins

### ISSUE THREAD

**Issue by dfranciscus** [chocolatey/ChocolateyGUI#554]
It would be nice to hide the "settings" button for non-admin users. I do not believe there is any reason they would need to access it, at least in our environment. 

Thanks!

**Comment by TheVakman** [comment]
I second this, it would be a nice option to have.

**Comment by teamdresch** [comment]
+1
We'd also like the ability to hide admin-only sources from non-admin users.

**Comment by gep13** [comment]
@dfranciscus this makes sense to me, and I think we should include it in the next release.

**Comment by gep13** [comment]
This is going to be implemented as a feature for Chocolatey for Business customers.  If you are interested in taking this for a spin, we are almost at the point of having a working beta version ready for testing.  Reach out to Chocolatey support through the usual channels for additional information if you are interested.

For now, going to close this issue.  Let me know if you have any additional questions.
