### ISSUE TITLE
Failed to update package

### ISSUE THREAD

**Issue by dfranciscus** [chocolatey/ChocolateyGUI#559]
I am getting this error as a standard user when trying to update anything it seems. I am on Win 10 Enterprise 1709 and ChocoGUI v0.16. Configed Choco with this:

choco feature disable --name=showNonElevatedWarnings
choco feature enable --name=useBackgroundService
choco feature enable --name=useBackgroundServiceWithNonAdministratorsOnly
choco feature enable --name=useBackgroundServiceInteractively

![image](https://user-images.githubusercontent.com/11379800/36281500-e24e6480-126b-11e8-8dc1-ad9f1ac1304f.png)

**Comment by gep13** [comment]
@dfranciscus any chance that you can grab the logs that go along with this upgrade attempt?  Also, can you please confirm what version of Chocolatey and chocolatey.extension that you are using?

**Comment by gep13** [comment]
@dfranciscus can you confirm that `choco upgrade` outside of Chocolatey GUI is working as you would expect?

**Comment by dfranciscus** [comment]
Hi @gep13 yep choco upgrade is working outside GUI. I am using the latest Chocolatey and ChocolateyGUI v0.16.0. Attached are the logs. Thanks!

[logs (3).zip](https://github.com/chocolatey/ChocolateyGUI/files/1759662/logs.3.zip)

**Comment by exportgoldman** [comment]
WE have the same problem. Fresh install of Windows 10 v1709 and chocolatey. Enable that option useBackgroundServiceInteractively and nothing will install, even chocolateygui will fail to install.

**Comment by pauby** [comment]
@dfranciscus @exportgoldman there has been no update to this for almost 6 years. Are you still having this issue?
