### ISSUE TITLE
Fix links in Settings/About (0.16)

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/ChocolateyGUI#562]
The following get 404 and WordPress database errors: (possibly a site problem?)

•	All new Chocolatey GUI
•	Making a chocolatey package for Chocolatey GUI
•	Chocolatey GUI

The above are available via web.archive.org

First link to Gary Ewan Park - https://www.gep13.co.uk/about/ 404's :)

**Comment by gep13** [comment]
@bcurran3 aw man, we should totally fix those!  Thanks for reporting!

**Comment by gep13** [comment]
@bcurran3 The blog posts links I am likely going to have to just remove.  I remember @chrissie1 saying that these had been removed from the lessthandot.com site, and I don't think they have been moved anywhere else.
