### ISSUE TITLE
Chocolatey GUI v0.16.0 uninstall errors (but uninstalls)

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/ChocolateyGUI#563]
I think most the "confusion" stems from:
"$packageName = "Chocolatey GUI";" 
instead of:
$packageName = "chocolateygui";
in chocolateyUninstall.ps1

I haven't looked into the registry key error but want to point it out as well.

Microsoft Windows [Version 10.0.16299.248]
(c) 2017 Microsoft Corporation. All rights reserved.
C:\WINDOWS\system32>choco uninstall chocolateygui
Chocolatey v0.10.8 Professional
Uninstalling the following packages:
chocolateygui

chocolateygui v0.16.0
Property ProductName does not exist at path HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Products\99E80CA9B0328e74791254777B1F42AE.
0
WARNING: Write-ChocolateySuccess is deprecated and will be removed in v2. If you are the maintainer, please remove it from your package file.
Only an exit code of non-zero will fail the package by default. Set
 `--failonstderr` if you want error messages to also fail a script. See
 `choco -h` for details.
 Running auto uninstaller...
 Skipping auto uninstaller - 'Chocolatey GUI' appears to have been uninstalled already by other means.
 chocolateygui has been successfully uninstalled.
chocolateygui not uninstalled. An error occurred during uninstall:
 Unable to find package 'ChocolateyGUI'.

Chocolatey uninstalled 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - chocolateygui (exited 1) - chocolateygui not uninstalled. An error occurred during uninstall:
 Unable to find package 'ChocolateyGUI'.

If a package uninstall is failing and/or you've already uninstalled the
 software outside of Chocolatey, you can attempt to run the command
 with `-n` to skip running a chocolateyUninstall script, additionally
 adding `--skip-autouninstaller` to skip an attempt to automatically
 remove system-installed software. This will only remove the packaging
 files and not things like software installed to Programs and Features.

If a package is failing because it is a dependency of another package
 or packages, then you may first need to consider if it needs removed
 as it is typically installed as a dependency for a reason. If you
 decide that you still want to remove it, head into
 `$env:ChocolateyInstall\lib` and find the package folder you want
 removed. Then delete the folder for the package. This option should
 only be used as a last resort.

C:\WINDOWS\system32>

**Comment by gep13** [comment]
@bcurran3 thanks for raising this.  This has been addressed and will ship in the next release.
