### ISSUE TITLE
Chocolatey GUI is randomly unable to list all packages

### ISSUE THREAD

**Issue by Janek91** [chocolatey/ChocolateyGUI#565]
Sometimes ChocolateyGUI is listing only few packages and searching for desired package doesn't return anything. Investigating issue with Fiddler - I see, that instead of
[https://chocolatey.org/api/v2/Packages()?$filter=IsLatestVersion&$orderby=DownloadCount%20desc,Id&$skip=0&$top=30&searchTerm=%27%27&targetFramework=%27%27&includePrerelease=false](https://chocolatey.org/api/v2/Packages()?$filter=IsLatestVersion&$orderby=DownloadCount%20desc,Id&$skip=0&$top=30&searchTerm=%27%27&targetFramework=%27%27&includePrerelease=false)
query, it's running this one:
[https://chocolatey.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=DownloadCount%20desc,Id&$skip=0&$top=30&searchTerm=%27%27&targetFramework=%27%27&includePrerelease=false](https://chocolatey.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=DownloadCount%20desc,Id&$skip=0&$top=30&searchTerm=%27%27&targetFramework=%27%27&includePrerelease=false)
which is returning much less results.
I don't know if it's more related to API behavior than ChocolateyGUI, but please look at it and decide how to resolve it.

**Comment by gep13** [comment]
@Janek91 Do you happen to have a note of when this occured?  I wonder if this is related to this issue:

https://github.com/chocolatey/choco/issues/1494

Due to problems with the caching of the website that we have from time to time, package search results sometimes don't have back either at all, or only with a few results.

**Comment by CWhyMedia** [comment]
I can confirm this happening. For example, OBS (named "Open Broadcaster Software Studio"). Search "open broadcaster", "open AND broadcaster", "open broadcaster software", or "open broadcaster software studio", OBS does not come up. Put in "OBS", and OBS shows up as the fourth result, after... FFmpeg, a deprecated extension pack for VirtualBox, and GitLink?! Why does that even show up? 

Anyway, if you leave out "Open", and instead just search "Broadcaster", it shows up as the first result. This seems like a bug?

**Comment by gep13** [comment]
Chocolatey GUI uses the same underlying search that Chocolatey itself uses, so if there is an issue, it is outside of this repository.  As such, I am going to close out this issue.
