### ISSUE TITLE
Chocolatey GUI infinite load

### ISSUE THREAD

**Issue by ghost** [chocolatey/ChocolateyGUI#566]
Hello, I am contacting you to inform you that the software does not work in French. As soon as he makes a query in the console, it runs indefinitely. Thank you for correcting this bug as soon as possible. Ps: if there is fault it is because I am French sorry in advance.

**Comment by mwallner** [comment]
@alal700 - thanks for reporting this issue - please give a little more detail about your environment (OS Version, Choco GUI Version)

@x-jokay - can you reproduce this?

**Comment by x-jokay** [comment]
Just tried, but I cannot reproduce this error.

I don't think this error can be language specific.

**Comment by gep13** [comment]
@jokay thanks for confirming.  I am going to go ahead and close this out, as we haven't had any additional reports regarding this.
