### ISSUE TITLE
Package shows as installed in GUI when it did not actually install

### ISSUE THREAD

**Issue by dfranciscus** [chocolatey/ChocolateyGUI#573]
After failing a package (cygwin" in my example), when right clicking on the package again, it shows options to pin, uninstall, reinstall, details as if its installed but it did actually install. This would be confusing for users. Hitting "refresh packages fixed it" so the proper menu showed when right clicking again (install,details). I will send logs if needed.

**Comment by gep13** [comment]
@dfranciscus if you could capture the full steps to reproduce the problem, so that we can troubleshoot the problem, that would help.  In this case, I think you attempted the install using the background service, when it wasn't fully configured, right?  If so, can you capture those steps here so that it doesn't get forgotten?

**Comment by ferventcoder** [comment]
https://chocolatey.zendesk.com/agent/tickets/2433

**Comment by exportgoldman** [comment]
The easiest way to repro is to install a package which has a missing dependancy. The command line will show a error, but the GUI will happily say it's installed until a refresh.
![gui-problem](https://user-images.githubusercontent.com/39711253/41744431-da35ce7e-75f7-11e8-83b7-ab15dc5e8dc8.png)

**Comment by gep13** [comment]
I am able to reproduce this problem, but only when running with the background service enabled.  When running in normal mode, attempting the installation results in the following:

![image](https://user-images.githubusercontent.com/1271146/56369983-4a6abd80-61f2-11e9-8921-ca1c99b6a2ec.png)

This was reproduced using:

![image](https://user-images.githubusercontent.com/1271146/56370123-974e9400-61f2-11e9-85a7-9ba98040f910.png)

I had hoped that this issue https://github.com/chocolatey/chocolatey-licensed-issues/issues/51 would have helped with this, but looks like there is more work to be done here.  I will continue to investigate.

**Comment by gep13** [comment]
@dfranciscus @exportgoldman I have just re-tested this with the following installed:

![image](https://user-images.githubusercontent.com/1271146/56417217-2313ff00-628b-11e9-90fd-657861421d5f.png)

Notice the change from chocolatey-agent 0.8.1 to 0.9.0, and I can confirm that any error returned from the background service is now being reflected in Chocolatey GUI.  The changes made to background service, both within chocolatey.extension 2.0.0 and chocolatey-agent 0.9.0 are required to make Chocolatey GUI work correctly.

There is a side effect where the displayed error may not show the exact cause of the problem, and that is related to this issue:

https://github.com/chocolatey/ChocolateyGUI/issues/635

But for now, this issue can be closed.  Please let me know if you have any questions.
