### ISSUE TITLE
Chocolatey GUI not found in the PATH

### ISSUE THREAD

**Issue by adriens** [chocolatey/ChocolateyGUI#574]
Hi @gep13 , i wanted to give a try to chocolateyGUI package to make a visual demo. While playing with your software, i discovered that the `exe` was not in the `PATH` ...and sometimes it's pretty convenient.

Please find below a screenshot showing all this :

![2018-03-20 11_56_56-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/5235127/37630049-5b09b530-2c36-11e8-80bc-6059091e8910.png)

**Comment by adriens** [comment]
Hopefully you will find this issue interesting 😸

**Comment by RichiCoder1** [comment]
I'm curious how this would be useful for you? Gui can't really do anything that would make it relevant on the cmd besides, well, start. (That isn't already done by choco that is)

**Comment by adriens** [comment]
@RichiCoder1  : Sometmes, it's useful tu launch GUI from console.

**Comment by gep13** [comment]
Given the functionality that was recently added (https://chocolatey.github.io/ChocolateyGUI/docs/commands/feature) I believe that this is more important than it previously was.  As such, I think creation of a shim is a good idea to launch/run Chocolatey GUI from command line.

**Comment by gep13** [comment]
This has now been included, and will ship in the next release of Chocolatey GUI.
