### ISSUE TITLE
GUI crashes when view-ing details!

### ISSUE THREAD

**Issue by aadrian** [chocolatey/ChocolateyGUI#578]
After the latest Windows 8.1 updates, the UI is crashing when view-ing the details of packages (with the exception of the Chocolatey packages).
```
chocolatey 0.10.8
chocolatey-core.extension 1.3.3
chocolatey-windowsupdate.extension 1.0.2
chocolateygui 0.16.0
```
The steps performed:
 - clean log files in both chocolatey and chocolatey GUI directories
 - start the chocolatey GUI
 - right click on any item (except those mentioned above) and click "details".
 - the detail window is loaded, text is readable
 - after max 2 seconds, the window crashes.
 - it leaves **no** traces in logs.

The visible crash:
![choco_gui_crash](https://user-images.githubusercontent.com/140953/37868249-bc1f9a90-2fa3-11e8-9c8f-8eb334b8955a.png)

The windows error window displays: the text:
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	ChocolateyGui.exe
  Application Version:	0.16.0.0
  Application Timestamp:	5a85a84e
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.3.9600.18895
  Fault Module Timestamp:	5a4b127e
  Exception Code:	c0000005
  Exception Offset:	0001de33
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	6153
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	d2dd
  Additional Information 4:	d2ddcae25462e2b2f29684f70c88f75a

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\WINDOWS\system32\en-US\erofflps.txt
```

**Comment by AlbinoGeek** [comment]
Is this related to #584 ?

**Comment by aadrian** [comment]
@AlbinoGeek seems to be the same problem only on a different OS version. So technically that issue is a duplicate of this one :) .

We can reproduce this problem on Win7 and Win 10 too, on **all** machines - it makes practically the the ChocolateyGUI useless.

The problem seems to be the loading from the net of further resources in the detail page - there seems to be no correct handling for that, so it crashes the entire app. 
The packages I mentioned as an exception from the rule, don't seem to crash the app, since they're cached (not downloaded from the net).

**Comment by jacktose** [comment]
As the #584 reporter, I don't think it's a dupe. CCleaner (and everything I've tried except rufus) works fine for me, the errors are different, and there are logs.

That's with chocolatey 0.10.10 and this was reported with 0.10.8. Is this fixed or replicated in .9 or .10?

**Comment by aadrian** [comment]
@jacktose The problem still happens with the newest versions too, on **all** computers we've tried.

**Comment by jacktose** [comment]
@aadrian It doesn't happen on either of my (Win 10) computers. What can I do to help troubleshoot?

**Comment by aadrian** [comment]
> What can I do to help troubleshoot?

@jacktose I have no idea :( .  

The only common theme between the various computers where I've installed over the last 3 weeks seems to be:
 - the packages that I installed (at least a part of them)
 - (locale)/region
 - other packages not managed by choco that are still installed on those machines

I can reproduce the crash from newly bought Thinkpads with Win 10 Pro till very old computers still running Win 7 Home, or corporate ones with the Enterprise version.

Trying to see details about the "Rufus" package (on the computer I'm typing this now) is producing this error:
```
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	ChocolateyGui.exe
  Problem Signature 02:	0.16.0.0
  Problem Signature 03:	5a85a84e
  Problem Signature 04:	System
  Problem Signature 05:	4.7.2558.0
  Problem Signature 06:	59d41488
  Problem Signature 07:	36f
  Problem Signature 08:	73
  Problem Signature 09:	System.UriFormatException
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	6153
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	d2dd
  Additional Information 4:	d2ddcae25462e2b2f29684f70c88f75a

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\WINDOWS\system32\en-US\erofflps.txt

```

**Comment by gep13** [comment]
@aadrian @AlbinoGeek @jacktose if possible, could you all take a look at the latest Chocolatey GUI pre-release version?

You can install this using:

```
choco install chocolateygui --source https://www.myget.org/F/chocolateygui/ --pre
```

Hopefully this issue has been fixed.
