### ISSUE TITLE
Crash opening details page for Rufus

### ISSUE THREAD

**Issue by jacktose** [chocolatey/ChocolateyGUI#584]
### To reproduce:
1. Switch to “chocolatey” on the left.
2. Search for "[rufus][rufus]".
3. Double-click or right-click > details.

### Expected:
1. Open details page.

### Actual:
1. Open [this dialog][dialog].
2. When dialog is dismissed, close entirely.
3. Leave [this log file][log].

### Notes:
[`choco info rufus` in admin PS works as expected.][PS]

### Context:
Chocolatey GUI 0.16.0  
Chocolatey 0.10.10  
Powershell 5.1.17133.73
Win 10 Pro 1803 build 17133.73

[rufus]: https://chocolatey.org/packages/rufus
[dialog]: https://i.imgur.com/THSbNSo.png
[log]: https://gist.github.com/jacktose/2f4f574dcda6df9d023b4a3aefa4d4d3
[PS]: https://gist.github.com/jacktose/22416f9e8a84226b2f520ef9e60c0448

**Comment by jacktose** [comment]
Replicated on another machine:

Chocolatey GUI 0.16.0
Chocolatey 0.10.10
Powershell 5.1.16299.251
Win 10 Enterprise 1709 build 16299.309

**Comment by AdmiringWorm** [comment]
I can confirm this issue on my own computer as well. Not sure yet if there is a problem with the rufus package though as the error message mentions that the URI is invalid, but in my opinion such errors should probably be silently ignored by chocolatey gui.

**Comment by AdmiringWorm** [comment]
Been looking through the rufus package now, and other than a broken image.
I can't see anything in the package that should cause the error, but from the error report it also seems to be a problem with the markdown, although I couldn't reproduce any error when testing it on the babelmark page.

Basically, I have no idea what's causing this. Could perhaps be wrong data returned by chocolatey? (probably not though).

**Comment by AlbinoGeek** [comment]
Is this related to #578 ?

**Comment by jacktose** [comment]
Looks similar, but I've only replicated the issue with rufus. All other packages I've tried work fine, including CCleaner.

**Comment by AdmiringWorm** [comment]
well, I tried it with the latest pre-release and I don't get any erros.

Unfortunately I don't know if that is because the update of markdig, or if because the package(s) have been fixed (or at least updated) since last time I checked.

**Comment by jacktose** [comment]
I just replicated this with CGUI 0.16.0, so it's not the package that's fixed.
Then I upgraded to 0.17.0-unstable0080 and Rufus works fine.

**Comment by gep13** [comment]
@jacktose thanks for confirming! 😄
