### ISSUE TITLE
Tiles View -- Null Reference Exception in LiteDB

### ISSUE THREAD

**Issue by AlbinoGeek** [chocolatey/ChocolateyGUI#587]
### Summary:

Tile View causes Null Reference Exception in LiteDB

![Image of the issue](https://i.imgur.com/GjAmmZl.png)

### Reproduction

1) Install Chocolatey 0.10.10 (latest) for Windows 10 x64
2) Install Chocolatey GUI 0.16.0 via Chocolatey *
3) Open Chocolatey GUI (opens as Administrator)
4) Click "Tile View" in the top right

### Long Description

- No program log could be found.
- No symbols are available for debugging.
- The exception occurred in external code (JIT cannot catch.)
- Task debugging is not available, as it thinks you did not target .NET 4 or higher

![In the debugger](https://i.imgur.com/usnjOUL.png)
![When I look for tasks](https://i.imgur.com/cJWjQCt.png)

Upon continued execution, the software fails entirely, and JIT cannot catch the next exception.

**Comment by gep13** [comment]
@AlbinoGeek are you able to confirm if this continues to happen on the latest pre-release version of Chocolatey GUI?

Installation instructions for this can be found here:

https://github.com/chocolatey/ChocolateyGUI#installation

I have just tested your reproduction steps, and I can't get this to happen.

**Comment by gep13** [comment]
I believe that this issue was fixed as a result of the upgrade to the latest LiteDB version which shipped with 0.18.0 of Chocolatey GUI.  As such, I am going to close out this issue.
