### ISSUE TITLE
Settings descriptions/explanations

### ISSUE THREAD

**Issue by vertigo220** [chocolatey/ChocolateyGUI#605]
GUI settings should have short descriptions explaining what they do, either as tooltips or by expanding them or something. Especially ones like "Use delayed search," as it's not at all clear what that does.

![](https://user-images.githubusercontent.com/12024557/39887280-d201251e-545f-11e8-8cce-a101b8721855.png)

Some of these are obvious (e.g. "Show Console Output" and "Default to Tile View"), but some are not. I have no idea what "Use delayed search" would do, and there's no explanation at all for it. Other settings have descriptions, but they're not always as useful as they could be, such as allowGlobalConfirmation (unclear whether on means prompt or bypass), failOnAutoUninstaller (fail if it fails?), and failOnStandardError (I assume this means that if it writes to stderr, something must have gone wrong so count it as a failure, but it only makes what sense it does to me because I know what stderr is, which a lot of people might not and it seems like it should be enabled by default). Maybe Chocolatey is only meant for advanced users, but it seems to me it should be accessible to more basic users as well.

**Comment by gep13** [comment]
@vertigo220 thank you for your valuable feedback.  This is certainly something that we will look at.

The Chocolatey GUI settings we can handle directly in the Chocolatey GUI application, the Chocolatey settings come directly from the Chocolatey CLI, so we would need to create a similar issue there it changes are actually required.

With regard to the setting that prompted this question...

Use delayed search is referring to the search dialog that exists in Chocolatey GUI.  In a previous version, as soon as you would start typing it would start searching.  With the delayed search, it will wait until you actually click the search button before initiating the search.

**Comment by vertigo220** [comment]
https://github.com/chocolatey/choco/issues/1572 already exists, in case one is needed there. 😄

**Comment by gep13** [comment]
Okay, let's get that one re-opened to be specifically about the Chocolatey descriptions.

**Comment by gep13** [comment]
A first stab at this will be released in the next version of Chocolatey GUI:

![image](https://user-images.githubusercontent.com/1271146/42580067-91df4a86-8521-11e8-9a21-4e69f05a3490.png)

**Comment by vertigo220** [comment]
Here's my thoughts on how to shorten the descriptions to minimize clutter while maintaining the same level of information (much of the suggested descriptions simply restate the name of the option, which is like using a word in its own definition):

- Show Console Output - Shows output from the commands being executed when a job is running.
- Use Tile View for Local/Remote Source - Default to tile instead of list view. It is still possible to switch during use.
- Use Delayed Search - Enables live search, which returns results after a short delay without clicking the search button. (at the very least, manually is misspelled as manaully)

I also think some of the 'Features' option descriptions could be improved, especially autoUninstaller (I'm assuming it means programs installed with Chocolatey can be uninstalled directly from Windows instead of needing to be done with a choco script?), allowGlobalConfirmation, and failOn... (e.g., fail if...fails seems redundant, and I'm assuming it means choco will throw an error in that case only if that option is enabled, but it's not very clear, at least to me).

**Comment by gep13** [comment]
@vertigo220 those seem like sensible suggestions to me.  I have updated the Resource strings to use these.

>@vertigo220 said...
I also think some of the 'Features' option descriptions could be improved, especially autoUninstaller

As I think I have mentioned, those descriptions/titles are coming from Chocolatey itself, and Chocolatey GUI is simply displaying them, so those will not be updated here.  That is what the other issue that you raised is tracking.

**Comment by vertigo220** [comment]
> As I think I have mentioned, those descriptions/titles are coming from Chocolatey itself, and Chocolatey GUI is simply displaying them, so those will not be updated here. That is what the other issue that you raised is tracking.

Ah, you're right, you did. Sorry, forgot about that. Look forward to the further discussion there. :)

**Comment by gep13** [comment]
@vertigo220 if you want to make some suggestions on how the titles/descriptions can be improved by adding information to that ticket, then we can discuss further.

**Comment by vertigo220** [comment]
I assume since this is closed these new descriptions should be showing now, but they're not for me.

**Comment by gep13** [comment]
>@vertigo220 said...
I assume since this is closed these new descriptions should be showing now, but they're not for me.

The individual issue is closed yes. however the milestone that this issue is associated with, 0.17.0, is still open, and therefore not shipped.  If you want to take it for a spin, see the installation instructions on the readme for details of how to install the pre-release version.
