### ISSUE TITLE
Don't allow navigation to settings or about screen while dialog is open

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#606]
This will cause confusion to user, and shouldn't be allowed.

![image](https://user-images.githubusercontent.com/1271146/41598109-30623c02-73c7-11e8-8ebc-3144968b5093.png)

Wait for dialog to close, before allowing settings or about button to be clickable.

**Comment by gep13** [comment]
@punker76 I think I am right in saying that this is due to, in part, this setting:

`ShowDialogsOverTitleBar`

on our main `MetroWindow`.  Is there another setting that I can use to prevent clicking of these buttons while dialog is open, so would I need a guard property on the button itself to only be clickable when not showing the dialog?

**Comment by punker76** [comment]
@gep13 There happened a few changes for the Dialogs in v1.6.x. So maybe we can move to this version for a better handling with opened dialogs...

- `MetroWindow` (`Dialogs`)
	+ Add a new (readonly) `IsAnyDialogOpen` dependency property. This property will be updated if a dialog is shown or not.
	+ New: `OwnerCanCloseWithDialog` property at `MetroDialogSettings` which can be used to handle how the owner of the dialog can be closed.
	+ New: `IsCloseButtonEnabledWithDialog` property at `MetroWindow` which indicates if the close button should be enabled or not if a dialog is shown.
	+ The `HandleOverlayOnHide` and `HandleOverlayOnShow` methods sets the `IsCloseButtonEnabledWithDialogPropertyKey` and restores focus if needed
	+ New: `OverlayFadeIn` and `OverlayFadeOut` properties to set/override the overlay fade in/out Storyboards which are used for the `Dialogs`
	+ Fix: Fade in and out animation was wrong if no duration exists
	+ Fix: `HideMetroDialogAsync` fails sometimes to close dialog (async call order)

**Comment by gep13** [comment]
@punker76 ooo, interesting.  Okay, lets swing back on this once I have done a couple other things.  Currently Chocolatey GUI is using 1.5.0.  Should it be a straight forward upgrade, or are there things that are going to need to change?

**Comment by punker76** [comment]
@gep13 It's straight forward to upgrade without doing some changes. (The only thing is, I saw on doing this, that the version of the assembly is wrong, so I should publish a fixed v1.6.5, damn...)

**Comment by gep13** [comment]
@punker76 ouch! Hopefully a simple fix for the version number.

Ok, cool.  Let me finish up what I am working on, and I will try to take a look at this as well.

**Comment by punker76** [comment]
@gep13 give me a hint and I can (will) make the upgrade (incl. the IconPacks)

**Comment by gep13** [comment]
@punker76 that would be amazing if you could 👍 

What do you need from me?

**Comment by ferventcoder** [comment]
Looks like just a review of #608 ;)

**Comment by gep13** [comment]
@ferventcoder yip, I saw the PR, but I think that is only part of the work, right @punker76?  That PR pulls in the latest MahApps pieces, but I think there is still some configuration work required.  Although, I haven't taken the PR for a spin yet.

**Comment by punker76** [comment]
@gep13 I'm done with #608. This issue is also added to the PR, so you can close this one.
