### ISSUE TITLE
Icons stored as a cache in data.db does not get a refresh if icon changed on nexus repository

### ISSUE THREAD

**Issue by hahaki** [chocolatey/ChocolateyGUI#624]
I have nexus 3.14 (latest version) storing nupkg / exe and icons for chocolatey packages. At the first time the new package appear in Nexus nuget repo Chocolatey Gui stores the image in data.db in User's home directory. In nuspec file it has a url to nexus as a reference for an icon in chocolatey which works fine at the beginning. If i change the icon (delete old on from Nexus and upload a new one) chocolatey gui does not recognise the change and use the old icon. If i just simply delete the icon from Nexus, chocolatey gui still shows the old one. Restart of chocolatey gui does not solve the issue. Only delete of data.db file forces chocolatey to check the icons a download them again. 
Desired functionality: at least for refresh button or/and restart chocolatey gui the icons should be checked if they are obsolete or not and data.db should be updated. If it looks not fast enough md5 checksum can be used for that comparison, Nexus supports that.

(chocolatey Gui version 0.16, choco version 0.10.11, windows 7 sp 1)

**Comment by gep13** [comment]
@punker76 @pascalberger @mwallner I am going to take a stab at adding this functionality, as I also want the ability to purge the Outdated Packages cache which was added here: https://github.com/chocolatey/ChocolateyGUI/pull/669 but I am not clear on "where" these new buttons (assuming that they are surfaced as buttons) should appear.

I don't think these global actions should appear here:

![image](https://user-images.githubusercontent.com/1271146/57129321-f0d7c680-6d8d-11e9-9f3d-e77dd88a9be0.png)

As they are not specific to one particular source.  Instead, I was thinking about putting them here:

![image](https://user-images.githubusercontent.com/1271146/57129371-15cc3980-6d8e-11e9-94a6-ac81a3271470.png)

In the new `Chocolatey GUI` tab in the setting screen, along the bottom of that screen.  Perhaps using similar button styles to those shown on the Package Details screen:

![image](https://user-images.githubusercontent.com/1271146/57129423-401df700-6d8e-11e9-9fa0-68837c138078.png)

What are your thoughts?

**Comment by punker76** [comment]
> I don't think these global actions should appear here:
> 
> As they are not specific to one particular source. Instead, I was thinking about putting them here:
> 
> In the new `Chocolatey GUI` tab in the setting screen, along the bottom of that screen. Perhaps using similar button styles to those shown on the Package Details screen:
> 
> What are your thoughts?

@gep13 I think using the same "button command bar" at the bottom is a good idea. If something like this can always be found in the same place, then users will find it easier to find their way around.

**Comment by gep13** [comment]
@punker76 sounds like we are on the same page 😄 

Thoughts...

![image](https://user-images.githubusercontent.com/1271146/57144088-2a252c00-6db8-11e9-8e91-c0187cf115f5.png)

**Comment by gep13** [comment]
@punker76 ooo, starting to come together now...

![image](https://user-images.githubusercontent.com/1271146/57145190-9739c100-6dba-11e9-844f-f2e32f041e91.png)

All localized, ready for translations 😄
