### ISSUE TITLE
Speed issues

### ISSUE THREAD

**Issue by atocyo** [chocolatey/ChocolateyGUI#625]
It takes ages to load Page 1 of respository (up to 2min), new pc, 300Mbps internet.
Moreover after starting to type it begins searching thus not allowing to finish your query (taking another 2 minutes). This GUI is pain and I try to use command line now. I want to know if this is to be expected  or I am outlier.

**Comment by boring10** [comment]
For the search problem you can enable "use delayed search" in the Chocolatey GUI settings. This will allow you to type in the search and hit enter before the search is performed.

**Comment by atocyo** [comment]
Duplicate of [https://github.com/chocolatey/ChocolateyGUI/issues/595](url)

**Comment by atocyo** [comment]
Duplicate deleted, reopening this.
