### ISSUE TITLE
GUI misses update that shows in CLI (again)

### ISSUE THREAD

**Issue by jacktose** [chocolatey/ChocolateyGUI#626]
I previously reported #585, which was similar to #506. Both were fixed by #557 making a comparison of package names case-insensitive.
It's happening to me again and I'm guessing it's a similar (case matching) issue, because the packages affected all have uppercase in their names, while all-lowercase packages (e.g. vim-tux) are working as expected.

### To reproduce:
1. In PowerShell, run `choco outdated` or `cup SourceTree -whatif`. Note that there are updates available, e.g. `SourceTree|2.6.10|3.0.8|false`:
![screenshot of command output showing updates available][cli]
2. In ChocolateyGui, find “Foxit Reader.”

### Expected:
1. Version=2.6.10, Latest Version=3.0.8.
2. Upgrade or Update All installs new version.

### Actual:
1. Version=2.6.10, no Latest Version listed.
![screenshot of GUI showing no update available][gui]
2. Upgrade option not available.

### Context:
Chocolatey GUI 0.17.0-unstable0082
Chocolatey 0.10.11
Powershell 5.1.17134.228
Win 10 Enterprise 1803 build 17134.345

[gui]: https://i.imgur.com/zvItA8r.png
[cli]: https://i.imgur.com/7NC6j7W.png

**Comment by DamianMaslanka5** [comment]
You are right. This is again a problem with case matching.
#557 fix doesn't work correctly, I thought that the rest of package ids are lower case but they are not.
Changing `if (message.Id != Id)` to `!string.Equals(message.Id, Id, StringComparison.OrdinalIgnoreCase)`  in [PackageViewModel](https://github.com/chocolatey/ChocolateyGUI/blob/b6eea32261687a7a02a35de8f4966647ffb3af5d/Source/ChocolateyGui/ViewModels/Items/PackageViewModel.cs#L596) should fix this problem. I think changes in the mentioned PR should be reversed.

@gep13 I think there should be a static method to compare ids just to make sure ids are compared correctly.
For example `var package = Packages.First(p => p.Id == message.Id);` in [LocalSourceViewModel](https://github.com/chocolatey/ChocolateyGUI/blob/b1e1a421580c53ac464ce0f11120118d140fc050/Source/ChocolateyGui/ViewModels/LocalSourceViewModel.cs#L246) I assume this works ok right now but someone could use id from remote source and it won't work correctly with some packages.

**Comment by DamianMaslanka5** [comment]
@gep13 I think this can be closed

**Comment by ferventcoder** [comment]
Duplicate of #585 

Marking as duplicate as we hadn't released the other feature yet, and this was found in testing a prerelease. So it's fine for us to have reopened that issue since there wasn't an actual release yet.

**Comment by ferventcoder** [comment]
Duplicate of #585

**Comment by jacktose** [comment]
Roger that. Glad there's a fix. I've installed `unstable-0114` and it looks good at the moment. It showed `everything` needing an update, and v16 didn't. Whenever `foxitreader` updates, I'll try to confirm that this specific breakage is fixed.
