### ISSUE TITLE
Provide ability to hide packages that are known to already be installed when viewing sources

### ISSUE THREAD

**Issue by dfranciscus** [chocolatey/ChocolateyGUI#627]
I would prefer it so users viewing packages on a source do not see packages that are already installed.

**Comment by mwallner** [comment]
how about adding a toggle to enable/disable this in the global settings?

**Comment by dfranciscus** [comment]
@mwallner yep thats what I meant. The ability to enable/disable that would be cool.

**Comment by daveMueller** [comment]
#636
