### ISSUE TITLE
Source Package URL is broken on chocolatey.org/packages/ChocolateyGUI

### ISSUE THREAD

**Issue by ssjw** [chocolatey/ChocolateyGUI#628]
The Source Package link for the ChocolateyGUI package on chocolatey.org points to the URL below which doesn’t exist:

https://github.com/chocolatey/ChocolateyGUI/tree/develop/ChocolateyPackage

Per an email from Rob Reynolds it should point to:

https://github.com/chocolatey/ChocolateyGUI/tree/develop/nuspec/chocolatey

**Comment by AdmiringWorm** [comment]
actually, if you look at the nuspec file in this repository you'll see that the correct url is used.
https://github.com/chocolatey/ChocolateyGUI/blob/develop/nuspec/chocolatey/ChocolateyGUI.nuspec#L11

It seems like it was fixed the day after the latest available release on chocolatey, which is why it doesn't show up there

**Comment by ssjw** [comment]
Is there any chance of getting the package source URL updated on chocolatey.org before the next release?

**Comment by AdmiringWorm** [comment]
that probably won't happen until a new release.

When a version is approved on chocolatey.org, they can't be changed. So a new package version would be needed to be pushed to change the package source URL.

**Comment by ssjw** [comment]
Roger.  Should this issue be closed then?

**Comment by AdmiringWorm** [comment]
I would say yes, as it has already been solved in the source code.

I don't have the power to close issues though.

**Comment by gep13** [comment]
@AdmiringWorm thanks for commenting on this.

Yes, this was fixed here: https://github.com/chocolatey/ChocolateyGUI/issues/550 which is due for release in 0.17.0.
