### ISSUE TITLE
Fix French Translation

### ISSUE THREAD

**Issue by CorentinDy** [chocolatey/ChocolateyGUI#631]
Hi,
3 months ago, i've made some changes and correction in the French translation but it still remain the error.

Changes has been made trought [transifex](https://www.transifex.com/chocolatey/chocolatey-gui/)

Not in the hurry but did you plan to make a future update ?

Thx for this awesome GUI ;)

**Comment by gep13** [comment]
@CorentinDy thank you for making these changes.

The Transifex updates are only refreshed when a new version of the application is released.  i.e. when 0.17.0 is released, you will see any updates that have been made to the translations.

I am going to go ahead and close this issue out, but feel free to ask any other questions.
