### ISSUE TITLE
Icons: keep aspect ratio

### ISSUE THREAD

**Issue by Schroedingers-Cat** [chocolatey/ChocolateyGUI#633]
Currently, icons are forced into a 1:1 ratio in the details section of a package. As most programs have an icon with a 1:1 ratio, that is fine.  

Sometimes, a software doesn't have an icon (because that software runs inside a host software hence there is no icon available) so you use a screenshot of the software from the developer's site. What chocolatey GUI does is turning [this image](https://www.voxengo.com/cdn/img/0/0lmtks3a-1.jpg) into this:  
![grafik](https://user-images.githubusercontent.com/6382400/50684938-a29cfb80-1017-11e9-8183-da83e4751063.png)

So the image is quite distorted. It would be a nice improvement if ChocolateyGUI could keep the aspect ratio like it is done on the [webpage of the community server](https://chocolatey.org/packages/voxengo-stereo-touch/2.9).

**Comment by gep13** [comment]
@Schroedingers-Cat thank you for raising this.  This has been corrected, and it will be included in the next release of Chocolatey GUI.
