### ISSUE TITLE
Crash on filezilla install

### ISSUE THREAD

**Issue by esamo** [chocolatey/ChocolateyGUI#638]
Can not reproduce. Tell me where can I find logs for you to investigate. This is Win10.

**Comment by gep13** [comment]
@esamo Logs are written into the C:/ProgramData/Chocolatey GUI folder

**Comment by esamo** [comment]
These are all the logs, not sure it helps.

[ChocolateyGui.20190121.log](https://github.com/chocolatey/ChocolateyGUI/files/2780789/ChocolateyGui.20190121.log)
[ChocolateyGui.20190122.log](https://github.com/chocolatey/ChocolateyGUI/files/2780790/ChocolateyGui.20190122.log)

**Comment by gep13** [comment]
Based on the logs, I am not seeing any crash reported in the logs.  The only mention of the filezilla package, suggests that the installation completed successfully.

**Comment by esamo** [comment]
Ok so already 3 times I had experienced a crash and it always happens when tile view is on. I can not have a tile view and not experience a crash. This is most likely #639.

**Comment by gep13** [comment]
@esamo can you please update that issue with some more details?  Such as version number of Chocolatey GUI, as well as exact version number of Windows, etc.  Thanks
