### ISSUE TITLE
Crash when loading tile view

### ISSUE THREAD

**Issue by esamo** [chocolatey/ChocolateyGUI#639]
This is easily reproduced.
1. Open ChocolateyGUI.
2. Switch to Remote source.
3. Search for example for 'backup'.
4. Switch to tile view.
5. It loads thumbs for about half a minute and then crashes.

---

Windows 10 Pro x64, v1803 build 17134.556
Chocolatey v0.10.11
Chocolatey GUI v0.16.0

**Comment by esamo** [comment]
I've added environment details.

**Comment by gep13** [comment]
>@esamo said...
I've added environment details.

Thank you!

**Comment by gep13** [comment]
@esamo I have just tried to reproduce the problem that you have raised here with the latest pre-release version of Chocolatey GUI, and I am unable to do it.

Can you please try to reproduce on the latest version, and if the issue persists, we can re-open this issue.

**Comment by loic74** [comment]
Sam problem here with tile view or when opening package details (doucle clic).  Occurs with some packages, for example with WinFsp, Mozilla Firefox or Node JS. No problem with Google Chrome or Notepad++ etc.

When debugging: "An unhandled exception of type 'System.AccessViolationException' occurred in Magick.NET-Q16-x86.dll"

Windows 7 Pro x64 SP1
Chocolatey 0.10.13
ChocolateyGUI 0.16.0

**Comment by hkeibel** [comment]
This issue still seems to be present.
It consistently occurs on my PC which I just set up with a clean install of Windows 10 and Chocolatey.

```
Windows 10 Pro 20H2, Build 19042.746
Chocolatey: 0.10.15
ChocolateyGui: 0.17.3.0
```

In the Windows event logs, the issue occurs in combination with an error event in .NET Runtime:
```
Application: ChocolateyGui.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at ImageMagick.MagickImage+NativeMethods+X64.MagickImage_Resize(IntPtr, IntPtr, IntPtr ByRef)
   at ImageMagick.MagickImage+NativeMagickImage.Resize(System.String)
   at ChocolateyGui.Common.Windows.Controls.InternetImage+<DownloadUrl>d__14.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

The second error event then happens at the very same timestamp:
```
Faulting application name: ChocolateyGui.exe, version: 0.17.3.0, time stamp: 0x6017c606
Faulting module name: OpenCL.dll, version: 2.2.5.0, time stamp: 0x5f6b2f14
Exception code: 0xc0000005
Fault offset: 0x00000000000015fb
Faulting process id: 0x34f0
Faulting application start time: 0x01d6febabf37ea57
Faulting application path: C:\Program Files (x86)\Chocolatey GUI\ChocolateyGui.exe
Faulting module path: C:\Windows\SYSTEM32\OpenCL.dll
Report Id: 70a2e9f2-6911-4b5e-8206-35a1708d1420
Faulting package full name: 
Faulting package-relative application ID: 
```


Would you rather like me to open a new ticket for this?

**Comment by punker76** [comment]
@hkeibel I think this will be fixed with the next 0.18 release, because we dropped the ImageMagick lib. You can try the pre-release until 0.18 come out https://github.com/chocolatey/ChocolateyGUI#installation

/cc @gep13

**Comment by hkeibel** [comment]
@punker76 
Thanks a lot, that's good news.
The pre-release for 0.18 does not seem to be available yet. Can you give me a rough estimate as to when it will be available.

**Comment by gep13** [comment]
@hkeibel the pre-release is available. The instructions for getting it are in the link the @punker76 provided.

**Comment by hkeibel** [comment]
> @hkeibel the pre-release is available. The instructions for getting it are in the link the @punker76 provided.

@gep13 
Yes, I followed those instructions and executed this:
```
choco install chocolateygui --source https://www.myget.org/F/chocolateygui/ --pre --force
```

But I got a failure message
```
Failures
 - chocolateygui - chocolateygui not installed. The package was not found with the source(s) listed.
 Source(s): 'https://www.myget.org/F/chocolateygui/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.
```


To me it looks like the cause is that https://www.myget.org/F/chocolateygui/ currently does not list any packages:
``` xml
<service xmlns="http://www.w3.org/2007/app" xmlns:atom="http://www.w3.org/2005/Atom" xml:base="https://www.myget.org/F/chocolateygui/">
<workspace>
<atom:title>Default</atom:title>
<collection href="Packages">
<atom:title>Packages</atom:title>
</collection>
<collection href="Screenshots">
<atom:title>Screenshots</atom:title>
</collection>
</workspace>
</service>
```

That's why I concluded the pre-release is not yet available...

**Comment by hkeibel** [comment]
@gep13 
Update:
I managed to install the most recent pre-release version by specifying it explicitly:
```
choco install chocolateygui --version 0.18.0-alpha0432 --source https://www.myget.org/F/chocolateygui/
```

This is also documented at:
https://www.myget.org/feed/chocolateygui/package/nuget/chocolateygui/0.18.0-alpha0432
