### ISSUE TITLE
Tile View - Prevent Version text overlap

### ISSUE THREAD

**Issue by iessa-pragg-ctct** [chocolatey/ChocolateyGUI#651]
Packages with particularly long version indicators clash in the tile view when they have updates available.
#### Environment
Win 10 Pro
ChocolateyGUI 0.16.0

![chocolatey-gui-version-collision-ui-issue](https://user-images.githubusercontent.com/38093909/53307578-c6d1d600-38fe-11e9-9274-1d29e05f107d.png)

**Comment by gep13** [comment]
@punker76 If you have some time, what are your thoughts on this?

**Comment by gep13** [comment]
@CTCTIPragg I can confirm that this remains an issue in the latest pre-release version of Chocolatey GUI.

@punker76 do you have any suggestions on how best to approach this?

**Comment by punker76** [comment]
So after some UI brain storming with @gep13 here are some options to improve these update situation for the tile view:

- **Prefered option** for me and Gary
Left aligned version informations above the title.

![2019-04-23_11h18_52](https://user-images.githubusercontent.com/658431/56570070-861ed200-65ba-11e9-8a33-3c7f90b0487b.png)
- Left aligned version informations under the title.
![2019-04-23_11h32_07](https://user-images.githubusercontent.com/658431/56570570-7e136200-65bb-11e9-94f5-f8da5181d846.png)
- Right aligned version informations above the (centered) title.

![2019-04-23_10h48_13](https://user-images.githubusercontent.com/658431/56570213-cd0cc780-65ba-11e9-87ad-bb21db4ec925.png)
- Right aligned version informations under the (centered) title.

![2019-04-23_11h00_03](https://user-images.githubusercontent.com/658431/56570375-1d842500-65bb-11e9-8eec-9a43bc92b778.png)

**Comment by pascalberger** [comment]
From the four options I agree with both of you for the left aligned version information above the title option.

Another idea: Title on top (above icon), version at the bottom

**Comment by mwallner** [comment]
all versions look good imo, although @pascalberger could have a point with placing the title above the icon ...

**Comment by gep13** [comment]
>@pascalberger said...
Another idea: Title on top (above icon), version at the bottom

Oooo, I think I like that...

@punker76 could you create another screenshot with that option?  Sorry to be a pain!

**Comment by punker76** [comment]
@gep13 @pascalberger @mwallner 

![image](https://user-images.githubusercontent.com/658431/56669953-3de2db00-66b2-11e9-86d9-d6f4e4b122b3.png)

**Comment by punker76** [comment]
@gep13 @pascalberger @mwallner

Also possible with a little bit opacity for the 'Out Of Date' ('Installed') overlay

![image](https://user-images.githubusercontent.com/658431/56670478-340da780-66b3-11e9-8459-aa203fb43b1f.png)

**Comment by AdmiringWorm** [comment]
@punker76 the title seems a little out of place when it is above the icon (IMO). Would it be better to have that centred?

**Comment by punker76** [comment]
@gep13 @pascalberger @mwallner @AdmiringWorm 

So, like this...

![2019-04-24_17h14_55](https://user-images.githubusercontent.com/658431/56671272-a16e0800-66b4-11e9-91ef-0483f2d7b391.png)

![2019-04-24_17h15_12](https://user-images.githubusercontent.com/658431/56671278-a3d06200-66b4-11e9-943f-f93cd9209328.png)

**Comment by AdmiringWorm** [comment]
Personally, I think that looks good (not considering the "Out of date" overlay of course)

**Comment by pascalberger** [comment]
Centered title looks generally better IMHO, except when there is an overlay. Would it be possible to move the overlay to the bottom right corner, as this is the place where there is most whitespace?

**Comment by gep13** [comment]
>@pascalberger said...
Would it be possible to move the overlay to the bottom right corner, as this is the place where there is most whitespace?

That would start to have the same problem when there is a large version number, for example on GitVersion.

**Comment by pascalberger** [comment]
> That would start to have the same problem when there is a large version number, for example on GitVersion.

Sure, but only with large version numbers. Which I assume is less often the case than large titles

**Comment by punker76** [comment]
![image](https://user-images.githubusercontent.com/658431/56671999-ec3c4f80-66b5-11e9-9221-b6160856d3d0.png)

**Comment by gep13** [comment]
>@pascalberger said...
Which I assume is less often the case than large titles

Yes, that is a valid point!

**Comment by gep13** [comment]
@punker76 I think I like the final option:

* Package Name on Top
* Version numbers in lower left cornet
* Out of Date/Installed overlays on the bottom right hand corner

Would you be able to update the PR to reflect this?

**Comment by punker76** [comment]
> @punker76 I think I like the final option:
> 
> * Package Name on Top
> * Version numbers in lower left cornet
> * Out of Date/Installed overlays on the bottom right hand corner
> 
> Would you be able to update the PR to reflect this?

Yes, I'll do a PR as soon as I can.
