### ISSUE TITLE
Tile View - Nitpick inconsistent spacing

### ISSUE THREAD

**Issue by CTCTIPragg** [chocolatey/ChocolateyGUI#652]
Vertical and horizontal spacing of the tile grid outer edge have different sizes.

If this is by design of course feel free to ignore this, it does look a little bit odd though.

#### Environment
Win 10 Pro
ChocolateyGUI 0.16.0

![chocolatey-gui-inconsistent-spacing-ui-issue](https://user-images.githubusercontent.com/38093909/53307800-f5e94700-3900-11e9-8ae7-d0d178386f2b.png)

**Comment by gep13** [comment]
@punker76 If you have some time, what are your thoughts on this?

**Comment by gep13** [comment]
@CTCTIPragg I can confirm that this was an issue in the 0.16.0 release of Chocolatey GUI:

![image](https://user-images.githubusercontent.com/1271146/56559660-1862ae00-659a-11e9-85b6-b27a3372e508.png)

However, in the most recent pre-release version of Chocolatey GUI, I am happy to say that this is no longer the case:

![image](https://user-images.githubusercontent.com/1271146/56559707-3cbe8a80-659a-11e9-8edd-c07e360c81f7.png)

**Comment by gep13** [comment]
As such, I am going to go ahead and close this issue.  Let me know if you still find this to be a problem.
