### ISSUE TITLE
prerelease packages are incorrectly labeled "outdated"

### ISSUE THREAD

**Issue by mwallner** [chocolatey/ChocolateyGUI#653]
See sample screenshot: "chocolatey" 0.10.12-beta is newer than the latest available 0.10.11, yet ChocolateyGUI marks it as outdated.

![image](https://user-images.githubusercontent.com/5354972/53407654-f5ae8180-39bc-11e9-8f89-b412d3f428b8.png)

**Comment by gep13** [comment]
@mwallner thank you for raising this.  This has now been corrected, and will ship in the next release of Chocolatey GUI.
