### ISSUE TITLE
Download and/or create package index to increase speed

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/ChocolateyGUI#654]
RE: https://github.com/chocolatey/choco/issues/1740#issuecomment-471645331

^ Hopefully this gets implemented in Chocolatey soon so it will be easier.

Right now ChocolateyGUI is dreadfully slow since it reads ~30 package's of info at a time over the web from chocolatey.org and repeats as necessary. An option to create a local catalog/index of all packages would greatly improve speed.

**Comment by gep13** [comment]
@bcurran3 this is not something that is going to be implemented here in Chocolatey GUI.  That would be a duplication of effort.  Once package indexing is implemented in Chocolatey, Chocolatey GUI can take advantage of this, but not something that it will implement directly.

**Comment by pauby** [comment]
This was raised under https://github.com/chocolatey/choco/issues/820.

As there is nothing to do here, I'm going to close this issue.
