### ISSUE TITLE
Pre-release v0.17 cannot update packages anymore: "The handle is invalid"

### ISSUE THREAD

**Issue by Kobus-Smit** [chocolatey/ChocolateyGUI#659]
The latest pre-release v0.17 cannot update packages anymore because of "The handle is invalid" error. 

![image](https://user-images.githubusercontent.com/11263864/56477570-76d05380-64ea-11e9-8640-48295aca6846.png)

![image](https://user-images.githubusercontent.com/11263864/56477561-60c29300-64ea-11e9-9919-bb2ebc818c52.png)

**Comment by gep13** [comment]
@kobus-smit that error isn’t anything to do with Chocolatey GUI directly I don’t think. Can you confirm by attempting the upgrade directly through Chocolatey?

**Comment by Kobus-Smit** [comment]
@gep 

Upgrading through pre v0.17 Chocolatey GUI does not work:
![image](https://user-images.githubusercontent.com/11263864/56545985-95068400-65bc-11e9-9dba-8638cdc22c5e.png)

Upgrading through Choco works:
![image](https://user-images.githubusercontent.com/11263864/56545807-0d207a00-65bc-11e9-92f6-efb596f116b6.png)

Upgrading used to work fine with v0.16 Chocolatey GUI on my computer.

**Comment by gep** [comment]
@Kobus-Smit I'm the wrong person you are referring to.

**Comment by Kobus-Smit** [comment]
Sorry @gep , I meant @gep13 ;-)

**Comment by gep13** [comment]
@Kobus-Smit are you still having this issue?  I have been doing some testing today ahead of the release, and I am not able to replicate this problem.

**Comment by Kobus-Smit** [comment]
@gep13 I've rolled back to v0.16 in April but installed v0.17 just now and still the same issue:

![image](https://user-images.githubusercontent.com/11263864/58672298-a431dc00-8389-11e9-820e-9a8e1502686b.png)

![34ADCA51-1207-4688-9092-E132674C594C](https://user-images.githubusercontent.com/11263864/58672658-5ddd7c80-838b-11e9-87a8-183b8c818c3a.GIF)

Other issue is that it shows that DisplayFusion and Foxit Reader is outdated but they are not:

![image](https://user-images.githubusercontent.com/11263864/58672851-36d37a80-838c-11e9-901b-cbecaf13a149.png)

**Comment by gep13** [comment]
>@Kobus-Smit said...
I've rolled back to v0.16 in April but installed v0.17 just now and still the same issue:

I will keep digging, but so far, I am unable to reproduce this 😢 

>@Kobus-Smit said...
Other issue is that it shows that DisplayFusion and Foxit Reader is outdated but they are not:

While they might be up to date, that update must have happened outside of Chocolatey.  As far as Chocolatey is concerned, you have 9.4.1.16829 of Foxit Reader installed, and the latest available package is 9.5.0.20723.  If you update applications directly through the application, i.e. not using Chocolatey, then things like this will happen.

**Comment by gep13** [comment]
@Kobus-Smit would you be in a position to test again to see if you are still seeing this issue?  Thanks

**Comment by Kobus-Smit** [comment]
I got a new PC, I'm on the latest v0.17 GUI and do not have this problem anymore.
