### ISSUE TITLE
Update to Chocolatey.Lib 0.10.15

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#670]
When doing this, remove the NuGetEncryptionUtility which was introduced in #665 as this will no longer be required.

**Comment by gep13** [comment]
Can't do this until Chocolatey 0.10.14 is released.

**Comment by FelschR** [comment]
Any updates on this?

**Comment by gep13** [comment]
@FelschR my intention is to get to this, and the last remaining item in the milestone this week, and to get 0.17.0 released.  Please understand that this isn't a commitment to this happening, but rather, that is what I am hoping to achieve.
