### ISSUE TITLE
Packages with pre-release versioning never found on list/search

### ISSUE THREAD

**Issue by mojonator5000** [chocolatey/ChocolateyGUI#676]
Checking the "Include Prerelease" box in 0.16.0 appears to have no effect. Packages on remote sources with pre-release version numbers (i.e. "1.0.0-whatever") are never found by a search. This can be reproduced using the MyGet.org feed for Chocolatey GUI itself, https://www.myget.org/F/chocolateygui/. Using following the CLI command returns 18 packages as of today, 8 stable and 10 pre-release versions of 0.17.0.

choco list -s "https://www.myget.org/F/chocolateygui/" -pre --all

However, using Chocolatey GUI with the same source displays only the 8 stable versions, even when both "Include Prerelease" and "All Versions" checkboxes are checked.

**Comment by gep13** [comment]
@mojonator5000 thank you for taking the time to report this.  This has been corrected in the latest pre-release version of Chocolatey GUI, as shown here:

![image](https://user-images.githubusercontent.com/1271146/58566079-d88d8700-8227-11e9-9d2e-4c0616643b62.png)

If you want to take the pre-release version for a spin, see the instructions in the readme of this repository.
