### ISSUE TITLE
Remove tilting chocolatey logo

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#680]
Based on new recommendations for usage of logo, and also to match the changes that are coming to the Chocolatey website, the Chocolatey Logo in the top left corner of Chocolatey GUI should no longer move.

**Comment by gep13** [comment]
![image](https://user-images.githubusercontent.com/1271146/59261904-28ac1680-8c36-11e9-9a1f-8eefa9b5c016.png)

**Comment by gep13** [comment]
@ferventcoder @designxsteph this is my first stab at implementing this.  Thoughts?

**Comment by designxsteph** [comment]
@gep13 Looks good to me!
