### ISSUE TITLE
Set the source to view on launch

### ISSUE THREAD

**Issue by dfranciscus** [chocolatey/ChocolateyGUI#684]
I would prefer to have the capability to set on a specific source when GUI is launched. Right now it defaults to the local, which to me is not very helpful in most scenarios where it will be used in my environment.  I would love the ability to set it to open on an internal repo.

**Comment by gep13** [comment]
@dfranciscus I "think" I am right in saying that this request is a duplicate of this one:

https://github.com/chocolatey/ChocolateyGUI/issues/657

right?

**Comment by dfranciscus** [comment]
Ah yes it is, sorry I didnt see that one.
