### ISSUE TITLE
Inline context sensitive KB input search ("jump")

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/ChocolateyGUI#688]
Instead of using Search:...
(A search enhancement.)

It would be nice if Chocolatey GUI would accept a typed letter from the keyboard and then jump to the first package name beginning with that letter and highlight it. As well as two characters (etc.) to jump to the first package matching the KB input. Ditto if sorted by Authors.

**Comment by gep13** [comment]
@bcurran3 the first part of this request has been completed by the work that @daveMueller has done, and it will ship as part of the 0.18.0 release of Chocolatey GUI.  The latter part, with regard to inline searching via the author has not been implemented.  If you wanted to raise this as a separate issue, we can perhaps look at doing that later.
