### ISSUE TITLE
Exception after startup

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/ChocolateyGUI#690]
After installing v0.17.0-unstable0210 I received the following exception after startup:

![grafik](https://user-images.githubusercontent.com/2190718/60624605-0301cf80-9de6-11e9-884f-73136ff25fab.png)

Application was loaded and reading installed packages for "This PC".

Next startup was successful without exception

**Comment by gep13** [comment]
@pascalberger was this a fresh installation? Or did you already have Chocolatey GUI installed?

**Comment by pascalberger** [comment]
@gep13 This was after installing over latest stable version on startup

**Comment by pascalberger** [comment]
@gep13 Got the same exception during WinOps workshop when switching first time from list to tile view

**Comment by mkevenaar** [comment]
@gep13 I was able to reproduce the issue on the winops machine.
Version: 0.17.0-unstable0233

**Comment by gep13** [comment]
@pascalberger @mkevenaar I too have also seen this happen on occasion, but as yet, I haven't been able to narrow down exactly what is going on here.  I am preparing to release 0.18.0, but I don't want this issue to hold up the release, so for now, I am going to remove it from the 0.18.0 milestone, and will continue monitoring for this to happen, to try to isolate exactly what is going on.

**Comment by gep13** [comment]
@pascalberger I haven't been able to replicate this problem at all, and I suspect that it may have been "fixed" by upgrading to the latest LiteDB version, so I am going to close this out.
