### ISSUE TITLE
Typo in README: the Requirements section is incorrect

### ISSUE THREAD

**Issue by Lemmingh** [chocolatey/ChocolateyGUI#693]
Currently, the **Requirements** section of `README.md` says

> Windows 7 SP1 through Windows 10 (1708) or Windows Server 2008 R2 SP1 through Windows Server 2016

However, there is **no such a version** of Windows 10 called 1708.

Besides, based on my test, Chocolatey GUI 0.16.0 works on Windows 10 Version **1903**.

Please solve the problem to get rid of confusion.
Thanks.

**Comment by gep13** [comment]
@Lemmingh thank you for raising this. I believe I have clarified this in this recent commit:

https://github.com/chocolatey/ChocolateyGUI/commit/3750053af87b6386d5acf175d1da0b3d7f06707f
