### ISSUE TITLE
ChocolateyGui.exe - blank icon

### ISSUE THREAD

**Issue by superbonaci** [chocolatey/ChocolateyGUI#696]
Don't know why doesn't show a proper icon, if there's such a thing for the .exe:

![Chocolatey GUI exe doesn't show a picture](https://i.imgur.com/mdRUYmY.png)

File version 0.16.0.0

**Comment by AdmiringWorm** [comment]
This should be fixed in the upcoming version of ChocolatyGUI.
See issue #589
