### ISSUE TITLE
Chocolatey GUI doesn't write to chocolatey.log

### ISSUE THREAD

**Issue by jacktose** [chocolatey/ChocolateyGUI#697]
Chocolatey CLI writes to `C:\ProgramData\chocolatey\logs\chocolatey.log`, but Chocolatey GUI does not.

This is especially confusing because the CLI output that the GUI shows says to look in the chocolatey log: ![image](https://user-images.githubusercontent.com/12414794/66088304-7e7f3400-e52f-11e9-862f-81e30a09c9c2.png)

@gep13 says it's a known issue:
> This is a side effect of the way that Chocolatey GUI calls into Chocolatey. We pass in an additional logger which should mean that logging happens to both the chocolatey log and the chocolatey gui log.

Possibly related to #695.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/issues/2122
