### ISSUE TITLE
Enhancement - Add export of installed packages to packages.config file

### ISSUE THREAD

**Issue by chrissie1** [chocolatey/ChocolateyGUI#7]
I want to add an export of installed packages in JSON format so that you can save it and import and install those packages on another machine. 

Suggested enhancement:
Allow the option to generate Boxstarter URL for selected packages as well.

**Comment by gep13** [comment]
What do you think of the following:

![image](https://cloud.githubusercontent.com/assets/1271146/6812839/6002c452-d269-11e4-88b8-95b4eff67107.png)

This simply generates a packages.config file, in the following format:

![image](https://cloud.githubusercontent.com/assets/1271146/6812848/718ee3a4-d269-11e4-99ec-1fe62e6c42c0.png)

Which contains all of the currently installed packages.

If people are happy with this, we can look to extend this to include the ability to generate a chocolatey package with all the currently installed packages as dependencies, and create a boxstarter script that will have all entries as a single command.

Thoughts?

**Comment by gep13** [comment]
I am going to break this issue into two, one for export, and one for import.
