### ISSUE TITLE
Add footer with information about current version in bottom left hand corner

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#705]
Following a conversation with Rob, the suggestion was made to add some footer text in this area:

![image](https://user-images.githubusercontent.com/1271146/67287399-fdceaa80-f4d2-11e9-992d-d7b5b897ffb4.png)

This will include the current version number of the application when running the Open Source version.  It will also flip to include the license information when running the Chocolatey for Business version of Chocolatey GUI.

**Comment by gep13** [comment]
This will look something like this in Open Source Edition:

![image](https://user-images.githubusercontent.com/1271146/67287980-05db1a00-f4d4-11e9-96ef-3f88c08245c2.png)

And like this in the Licensed editions:

![image](https://user-images.githubusercontent.com/1271146/67288038-21462500-f4d4-11e9-9a04-095efa55540a.png)

**Comment by ferventcoder** [comment]
👍
