### ISSUE TITLE
Settings to prevent preloading on remote views

### ISSUE THREAD

**Issue by iammael** [chocolatey/ChocolateyGUI#706]
Hello!

I'd suggest to add this toggler :

![cxiVhXElNo](https://user-images.githubusercontent.com/7931135/67447066-fa423d00-f612-11e9-982e-1e78fb28b8c5.png)

It makes the page load a little bit faster. I have the code done for it and could submit a PR on approval (and yes I added a dot at the end of the description in the code).

**Comment by gep13** [comment]
@iammael This looks like an interesting addition.  If you can send a PR, we can review the code.  Thanks for your interest in this project.

**Comment by iammael** [comment]
Thank you for your answer. I'll send it when I get back home in 3 days!

**Comment by opusforlife2** [comment]
@iammael Have you taken a look at this again?

**Comment by iammael** [comment]
Hi!

I'm really sorry, I didn't have time to log on Github for a while.

Is this still something you're interested in ?

**Comment by opusforlife2** [comment]
I definitely am.

@gep13 Could you confirm that this isn't already done/being done so that the effort doesn't get duplicated?

**Comment by gep13** [comment]
@opusforlife2 no work has/is currently been done on implementing this issue.

**Comment by opusforlife2** [comment]
Wow! That was fast! Thanks!

**Comment by opusforlife2** [comment]
@gep13 What's the reason behind the slow release cadence? Is there a reason why there aren't smaller releases with more frequent bug fixes and feature additions?

**Comment by gep13** [comment]
There are lots of reason why the 0.17.0 release took so long, but going forward, we are not planning on making the next release wait so long.  Having said that, I don't know when the next release will be.

If you want to take the pre-release of Chocolatey GUI for a spin, you can definitely do that.  The instructions are on the readme of this repository.
