### ISSUE TITLE
need more Improvements 

### ISSUE THREAD

**Issue by vk96mustafa** [chocolatey/ChocolateyGUI#707]
the app needs more polish design 
the app has a poor GUI design and it can be much better then that 
make it much cleaner, simple and much nicer , it needs to be more polish, again 
also it has a problem to dealing with images or "icons" with a width more then the height like this ms logo for example ...
![ChocolateyGui_ens7uyMx2E](https://user-images.githubusercontent.com/32788610/67688288-a8027280-f9aa-11e9-9f79-348f90affddb.png)
another think i wanna talk about is that i heard some folks tell you to add a search index so the search became better, it's a nice idea but you can simply see that the search for a packages in the choco website is really fast and nice so why don't you just use your website API to get the search result in both of your cmd and the GUI app ?
finally, you can see "for example" the design structure or principles of the chrome extension store or mac app store ... etc , so you get better idea about having a better GUI app 
you can also "for example" compare between LastPass Desktop app for win10 and Bitwarden Desktop app as they are both a PM apps with Different UI

**Comment by gep13** [comment]
@vk96mustafa thank you for providing your feedback.

Unfortunately, what you have provided isn't very actionable.  If you can pin point to specific problems that you have with the design, and perhaps provide a Pull Request to correct the perceived issues, then perhaps we can work to make improvements.

**Comment by vk96mustafa** [comment]
@gep13 now update my feedback
" I pressed the "Comment" button while i was typing by mistake , sorry"

**Comment by gep13** [comment]
@vk96mustafa with regard to the icon stretching, that is possibly something that we can look at.

Regarding the other feedback, I am still not sure that there is anything actionable there.  If you have specific pieces of feedback that can be directly addressed then please raise them as separate issues.  Let's keep this issue about the icon being stretched incorrectly.

**Comment by punker76** [comment]
@gep13 The icon stretching is fixed in the current source.

**Comment by gep13** [comment]
@punker76 yip, you are right!

@vk96mustafa in which case, I am going to suggest that we close this issue.  If you can create other issues that address specific areas of concerns, or suggestions for improvements, then I think that this would be the best way forward.

**Comment by vk96mustafa** [comment]
Hello @gep13, @punker76 sorry for this late response ...
I've decided to design a GUI (just an example) to show you an idea of a more polish (more premium) user interface for your choco app (using affinity designer), [this image](https://mega.nz/#!wIglQawB!1HNPvEWifwMr5XH-46zsrjhB8nKSKxiGniveFEv8NE4) for my design so you can preview it

Note: It would me very recommended to adding a vibrancy effect to the left side menu thou ([this example](https://static.businessinsider.com/image/557dd8886da811745a7e02fd/image.jpg) show you an app have vibrancy "or blur" effect for the left side menu).

However, if you have any question you can ask me  :)
