### ISSUE TITLE
Context menu not displayed

### ISSUE THREAD

**Issue by mkevenaar** [chocolatey/ChocolateyGUI#709]
Currently with v0.17.0.0 unstable 0255 (current latest version) the context menu is not showing when you right click on an item.

This was available in v0.16.0.0

**Comment by gep13** [comment]
I have just tested this, and I can confirm that the context menu seems to have been lost on the `LocalSourceView` however it is still working as expected on the `RemoteSourceView`.

At this point, not immediately clear on why this would have been lost.

**Comment by gep13** [comment]
More interestingly...

The context menu works when in the tile view of the LocalSourceView, but it isn't working on the list view.

**Comment by mkevenaar** [comment]
@gep13 I can confirm that I have the same results.

**Comment by punker76** [comment]
@gep13 This was my fault during MahApps v2.0 alpha support, I'll fix that.

**Comment by punker76** [comment]
@gep13 done

![2019-11-01_12h21_28](https://user-images.githubusercontent.com/658431/68021713-7cc99d00-fca2-11e9-9e02-13616eb8e019.png)

**Comment by mkevenaar** [comment]
@gep13 @punker76 I can confirm that it works again with unstable0256

Thank you @punker76 for your quick fix!

**Comment by gep13** [comment]
@punker76 thank you very much for doing this! 🎉

**Comment by gep13** [comment]
@punker76 is it possible that something else might have happened here as well?  I seem to remember that we added a prerelease label on the tile view when a pre-release version was installed.  Or am I misremembering that?

**Comment by punker76** [comment]
> @punker76 is it possible that something else might have happened here as well? I seem to remember that we added a prerelease label on the tile view when a pre-release version was installed. Or am I misremembering that?

@gep13 I will check this later

**Comment by gep13** [comment]
@punker76 so I had a quick look during the stream that I did this lunch time, and I think I was misremembering something.  I don't think anything else has been lost here.
