### ISSUE TITLE
Add support of tag <icon>

### ISSUE THREAD

**Issue by Zaknafeyn** [chocolatey/ChocolateyGUI#713]
**_Feature request_**

Add support of tag <icon> to allow embedding package icon inside the package instead of referencing the icon by url. This will allow to list packages with icons on machines without internet.

Description of the similar feature in NuGet https://docs.microsoft.com/en-us/nuget/reference/nuspec#icon

**Comment by gep13** [comment]
@Zaknafeyn Chocolatey GUI is a wrapper around Chocolatey.  What you are requesting would be a Chocolatey feature, which could then be supported in Chocolatey GUI.  Can I ask that you raise this issue over here: https://github.com/chocolatey/choco
