### ISSUE TITLE
Any plans making this work with chocolatey agent?

### ISSUE THREAD

**Issue by mtnielsen** [chocolatey/ChocolateyGUI#718]
Using GUI with the chocolatey agent is apparently supposed to be supported (???) https://chocolatey.org/docs/features-agent-service

    OPTIONAL (highly recommended): For use with Chocolatey GUI, you need Chocolatey Extension v1.12.4+, and at least Chocolatey GUI v0.15.0. Uninstall any version of the GUI you already have installed first, then run choco upgrade chocolateygui -y --allow-downgrade (you will also need at least .NET 4.5.2 installed)

But it's clearly not working, as GUI will not run without being provided credentials, and if it is provided non-privileged credentials it will throw every kind of access denied error imaginable when attempting to install if you are not running as admin.

It is supposed to send install commands to the agent service, and not attempt to install on its own, given this choco feature

    choco feature enable --name="'useBackgroundService'

So, any plans on fixing this behavior?

**Comment by gep13** [comment]
@mtnielsen to the best of my knowledge, this feature is working.  I have personally tested it a number of times, and I know lots of Chocolatey for Business Customers are also using this without any issues.

Can you please confirm what versions of each Chocolatey component you have installed?  Also, assuming you are a Chocolatey Licensed Customer, your best avenue for support would be to reach out directly to the Support Team.  Run the command `choco support` for more information on how to do that.

**Comment by mtnielsen** [comment]
I'm running 

    	chocolatey 0.10.15
	chocolatey-agent 0.9.1
	chocolatey-core.extension 1.3.5.1
	chocolatey-license 1.0.0
	chocolatey.extension 2.0.2
	chocolateygui 0.16.0

An attempt to uninstall a random app:

(attached)
[log.txt](https://github.com/chocolatey/ChocolateyGUI/files/3922440/log.txt)

**Comment by gep13** [comment]
@mtnielsen by default, uninstallation of a package via the background service, and therefore Chocolatey GUI, is prevented via a configuration option.  Can you confirm that you have changed this config value to allow the uninstall command to be used?

**Comment by mtnielsen** [comment]
Huh. That's it. It seems so obvious and yet it is so easy to miss.

    choco config set backgroundServiceAllowedCommands install,upgrade,uninstall
