### ISSUE TITLE
Provide the ability to not populate the package results when navigating to a source tab

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey/ChocolateyGUI#719]
When the user clicks on a source tab such as "chocolatey", it immediately starts fetching packages to populate the list. This blocks the user from interacting with the GUI until the first page of results is fetched. The wait can span up to a minute or more.

The user should have the option to disallow this automatic fetching of packages.

Alternatively, the GUI should not block the user from interacting with the application, while the package fetching continues in the background.

**Comment by gep13** [comment]
This issue was created after discussion in this issue: https://github.com/chocolatey/ChocolateyGUI/issues/595

**Comment by gep13** [comment]
I think this could be related to this issue: https://github.com/chocolatey/ChocolateyGUI/issues/706

**Comment by opusforlife2** [comment]
Fixed by #706.
