### ISSUE TITLE
Choose what version of packages you want to install in the GUI

### ISSUE THREAD

**Issue by nutterthanos** [chocolatey/ChocolateyGUI#722]
Maybe implement a gui box to choose what version of package you want just like how Hot Chocolatey already does it.
https://imgur.com/a/raFQw7f

**Comment by nutterthanos** [comment]
why is this not getting replies?

**Comment by gep13** [comment]
@nutterthanos apologies for not replying sooner about this, I didn't see the notifications about this issue.  This suggestion is really a duplicate of what was suggest here: https://github.com/chocolatey/ChocolateyGUI/issues/545.  There is an open PR for providing this functionality here: https://github.com/chocolatey/ChocolateyGUI/pull/823 would be great if you can provide feedback on that.  I am going to close this issue out as a duplicate.
