### ISSUE TITLE
Chocolatey GUI does see newest version of packages

### ISSUE THREAD

**Issue by jmacura** [chocolatey/ChocolateyGUI#723]
Crawling through the history of Issues here, this looks like a recurring bug (#585).

## Description

There is at least one package with update available in my list. I can see it via Power Shell command. Yet the latest version does not show up in the Chocolatey GUI.

## System
chocolatey 0.10.15
chocolatey-gui 0.16.0
PowerShell 5.1.18362.145
Windows 10 Pro 1903

## Screenshots
![choco_issue_cmd](https://user-images.githubusercontent.com/5598693/71725593-dbdb9780-2e34-11ea-9684-d2fc3ad60992.png)
![choco_issue_gui](https://user-images.githubusercontent.com/5598693/71725595-dda55b00-2e34-11ea-9964-d4eb2ce0ec4c.png)

**Comment by gep13** [comment]
@jmacura the issue that you link to was fixed in version 0.17.0 which hasn't shipped yet.  You are still using 0.16.0.  If you want to take the pre-release for a spin, you can find the installation instructions on the readme of this repository.

**Comment by jmacura** [comment]
Honestly, it really didn't crossed my mind, that it takes almost 2 years to make a new release...
Seriously, what's blocking the 0.17.0 to be shipped to the public?

**Comment by gep13** [comment]
@jmacura this is a community driven open source project, and there are no timescales associated with releases.  The pre-release version is currently considered stable, and there are upstream reasons why we haven't yet shipped 0.17.0.  My suggestion would be that you install the pre-release version, and when 0.17.0 is shipped, it will be a simple upgrade to move to the latest version.
