### ISSUE TITLE
Change mentions of "Pin" to be "Pin (Ignore updates)"

### ISSUE THREAD

**Issue by vertigo220** [chocolatey/ChocolateyGUI#730]
Not sure if this is a GUI issue or a choco one, so please let me know if I need to move it over there.

A big feature missing is the ability to tell chocolatey, probably via the right-click context menu, to ignore updates for an app. It should provide the options to ignore the current update or ignore all updates.

**Comment by gep13** [comment]
@vertigo220 are you familiar with the `choco pin` command?  I believe that this will do what you want.

**Comment by vertigo220** [comment]
Ah, ok. Should've known that based on #1607. Guess I just didn't connect the two, though now that you mention it, it's pretty obvious, though only based on that. In other words, I should have known that due to my participation in that issue, but otherwise, for a "normal" user, it wouldn't be at all obvious, so maybe that would be worth a GUI change, to change the context menu entry from "Pin" to "Pin (Ignore Updates)" and possibly even make something like a <choco pintemp> or <choco pinver> command with a corresponding menu entry that would be something like "Pin (Ignore Current Update" or "Pin (Ignore This Update)?"

**Comment by vertigo220** [comment]
Apparently I did the code tag wrong, and I don't know what it is nor can I edit my posts. I hate that GitHub changed so it no longer works on ESR. Anyway, that should say "make something like a *choco pintemp* or *choco pinver* command"

**Comment by gep13** [comment]
>@vertigo220 said....
Apparently I did the code tag wrong, and I don't know what it is nor can I edit my posts. I hate that GitHub changed so it no longer works on ESR. Anyway, that should say "make something like a choco pintemp or choco pinver command"

I am not sure if I completely follow this.  Can you elaborate?  Chocolatey GUI is simply a wrapper around the underlying Chocolatey commands.  If you are asking for a new Chocolatey command, which I _think_ you might be, then the correct place to make that request would be on the Chocolatey Repository.  Once implemented there, that functionality could be exposed within Chocolatey GUI.

**Comment by gep13** [comment]
>@vertigo220 said...
so maybe that would be worth a GUI change, to change the context menu entry from "Pin" to "Pin (Ignore Updates)" 

I think that this is a good suggestion.

**Comment by gep13** [comment]
@vertigo220 I have updated the title of this issue to reflect what is actually being requested.  Let me know if you have any additional comments.

**Comment by vertigo220** [comment]
"I am not sure if I completely follow this. Can you elaborate? Chocolatey GUI is simply a wrapper around the underlying Chocolatey commands. If you are asking for a new Chocolatey command, which I think you might be, then the correct place to make that request would be on the Chocolatey Repository. Once implemented there, that functionality could be exposed within Chocolatey GUI."

Yes, that's what I was asking, just figured I'd make sure that it was something I should open an issue for there before doing so, and it sounds like it is, so I'll do that now. Thanks!

**Comment by vertigo220** [comment]
Issue reference didn't work properly, referenced this issue number in that repo, so here it is: https://github.com/chocolatey/choco/issues/1997
