### ISSUE TITLE
ChocolateyGUI Icon

### ISSUE THREAD

**Issue by xmha97** [chocolatey/ChocolateyGUI#734]
Hello,
ChocolateyGUI icon can't be loaded because of the icon file removed:
https://cdn.rawgit.com/chocolatey/choco/8b6217061a4efe6543622e903996bb8eac012db2/docs/images/Choco_Icon.png
![image](https://user-images.githubusercontent.com/23485114/74505067-5e16ab80-4f0b-11ea-8916-2ce4f5a638a7.png)

**Comment by gep13** [comment]
@xmha97 thank you for raising this issue.  This has actually been addressed here:

https://github.com/chocolatey/ChocolateyGUI/issues/558

And it will ship in the next release of Chocolatey GUI.
