### ISSUE TITLE
Chocolatey GUI started installing (seemingly) random packages upon clicking "Next Page" button

### ISSUE THREAD

**Issue by durhambell** [chocolatey/ChocolateyGUI#735]
I've never seen it do anything like this. I installed `LinkShellExtension` then clicked the "Next" button to browse the next page, and it started to install a ton of random packages. Looking at the log, they seem to be grouped somewhat. By that I mean there are .install and .portable versions of the same packages installed back to back, but they aren't alphabetical or anything like that. Here's the list of packages it installed:

```

bépo
freetube
qttabbar1
microsoft.aspnet.mvc
myoddweb.piger
winevdmd]
openalsdk
little-system-cleaner 
jacked
gtools
solvespace
lossless-audio-checker
zpaq
7zip.portable
zandronumd
freedoomed
brutaldoomed
corsixth.portable 
corsixth.install
corsixth
moonlight-qt.install
moonlight.install
tusk.portable
opentyrian
moonlight-qt.portable
moonlight.portable
brutaldoom-scythe2
brutaldoom-hellbound
brutaldoom-goingdown
brutaldoom-d2reload
ctop
brutaldoom-epic2
open-dvd-producer
eduke321
3dduke-shareware
spaceradar
hikvision-sadp
dotmemory-unit.portable
stirling-jp
keepass-kpentrytemplates 
abastart
doom-sigil
dbforge-ora-studio-ent
dbforge-ora-studio-ent-32 
dependency-scanner 
hexamail-pop3-downloader 
7zip.commandline 
innounp 
lyricsfinder
cmaptools
screenlogic-connect
renamer.portable 
tonelib-zoom 
tonelib
regeditor
fluxfonts
aerozoom 
altcopy
windows-sandbox 
weasel
prometheus-grok-exporter

```

I don't have any of these apps installed, and I have never even heard of some of them.

___

Also, it tried to install a bunch of packages it couldn't find returning the `"The package was not found with the source(s) listed. ..."` error. These are the ones it tried unsuccessfully to install:

```

visualstudio15
core2d.avalonia.cairo
core2d.avalonia.direct2d
core2d.avalonia.skia
core2d.wpf
beyondcompare4
core2d-avalonia-cairo
mxnitro
exactaudiocopy
kino.leaseprovider
nodejs-win32.commandline
yammer-notifier
wlan-optimizer
grabit
micloud-link
gitversion.portable.reachfork
git-istage
supermarioflashback
validity-fingerprint-sensor-driver 
synaptics-touchpad-driver
hp-osd-utility
hp-launch-box
hp-application-assistant-software
hp-quick-launch-software
realtek-lan-driver
qualcomm-atheros-ar9000-series-wlan-driver
atheros-bluetooth-driver
leiningen
blender.tool
chewie

```

___
Can zip the logs tomorrow if anyone wants to peruse them. I tried to see what commands were issued, but they are spread across several logs and I'm pretty tired. Also, choco's logs are incredibly verbose (ironically without containing a lot of useful information).

**Comment by durhambell** [comment]
Okay, the plot thickens. Upon attempting to uninstall the apps in question, many of them return the following error:
`WARNING: brutaldoom-scythe2 has already been uninstalled by other means.`

...the the uninstall (obviously) doesn't complete. I'll keep trying to troubleshoot this since it obviously isn't getting any views. Understandable, since I've never even heard of this happening, so it must be a pretty outlying outlier.

**Comment by gep13** [comment]
@durhambell providing the log files would definitely help to try to troubleshoot what is going on here.

To be clear, clicking the `next` button doesn't perform any operation other than moving to the next page of the source that is currently being viewed.

Due to the dependencies in place for the `LinkShellExtension` package, a number of other packages will get installed, but not any of the packages that you mention in your first code block.

**Comment by pauby** [comment]
There has been no update to this issue for over 4 years. I'm going to go ahead and close this, but we can reopen it if necessary.
