### ISSUE TITLE
GUI crashing on startup - missing config

### ISSUE THREAD

**Issue by f-tischler** [chocolatey/ChocolateyGUI#737]
I am on business trial and just tried to start Chocolatey GUI (0.16.0) but without success:

![image](https://user-images.githubusercontent.com/2072678/77325671-fbd67500-6d18-11ea-85ec-3ec1b79dcfc8.png)

The german part reads: A part of path "...." could not be found.

Checking the path I can confirm that the "config" directory is indeed missing. Reinstalling does not fix the problem.

**Update 26.03.20**
tried the lastest version from myget.org - same behaviour.

[Install log](https://gist.github.com/f-tischler/ae65e3542d957ea48df680e747add940)

I could not find any application logs - they should be in "%APPDATA%/Chocolatey GUI/Logs" right?

**Comment by gep13** [comment]
@f-tischler sorry to hear that you are having issues.

Can I ask how you have installed the Chocolatey GUI application?  The error message suggests that the application is looking in the wrong place for the chocolatey configuration file.

If you are on a Business Trial, the best advice would be to raise a support ticket directly, as that is your best option for getting an immediate response.

**Comment by f-tischler** [comment]
I have installed Chocolatey GUI via chocolatey. The directory "C:/Program Files (x86)/Chocolatey GUI" exists, just "config/chocolatey.config" is missing.

**Comment by gep13** [comment]
@f-tischler can you confirm what version of Chocolatey GUI you are using?

There doesn't need to be a `config/chocolatey.config` file at that location, and this is why I am confused.  Chocolatey GUI should be using the system level config file located at `C:/programdata/chocolatey/config/chocolatey.config`.

**Comment by f-tischler** [comment]
Alright, I think I have found the problem, your comment pointed me in the right direction. I figured that the GUI depends on some environment variable to detect where Chocolatey is installed and that it may fall back to its own installation directory if ít can not retrieve that info.

Seems like I have a corrupted Chocolatey install as $env:ChocolateyInstall is missing. I did a quick test by defining the variable at machine level and reinstalling Chocolatey GUI: et voila it works.

So I guess reinstalling Chocolatey will fix the problem, however, I wonder how I managed to mess up the installation so badly. I was strictly following the instructions on how to activate the business trial.

Thanks for your time @gep13 !

**Comment by gep13** [comment]
@f-tischler on that, I am not sure.

Just to give you a heads up, if you are on a business trial, the best course of action would be to reach out directly to the support team, rather than creating an issue here.  Over there you have a better chance of getting a timely response, compared to over here in the OSS issues.

For now, I am going to go ahead and close this out, as I think we have this figured out.  If you don't agree, feel free to respond back, and we can continue the discussion.
