### ISSUE TITLE
Improve how application icons are rendered within Chocolatey GUI

### ISSUE THREAD

**Issue by batzen** [chocolatey/ChocolateyGUI#739]
Hi there,

i just noticed that "ico" files aren't displayed anymore.

This can be fixed by telling `MagickImage`, via `MagickReadSettings`, that it's an "Ico".
When doing so the image quality is very bad.
In case of "ico" the current image loading loads the first frame present in the "ico" which means it's almost always 16x16.

I made some changes to improve the image quality on my machine.

Before:
![image](https://user-images.githubusercontent.com/1971030/77848451-f9ff2c80-71c4-11ea-90b7-2d6d479de909.png)

After:
![image](https://user-images.githubusercontent.com/1971030/77848454-fec3e080-71c4-11ea-8f26-1ff4e2f7da91.png)

That's the part for "ico" files.

"SVG" files don't seem to be rendered/loaded correctly too.
Currently this is what i get for Firefox:
![image](https://user-images.githubusercontent.com/1971030/77848469-3894e700-71c5-11ea-97a6-7731c9d8b1d0.png)

Would you be interested in a PR changing the decoding of images to different kinds of decoders for different image formats?
My PR would only affect "ico" currently, as i am not familiar with `MagickImage` and how to fix the wrong "SVG" rendering.

**Comment by gep13** [comment]
@batzen I would definitely be interested in a PR to fix these issues, yes.

**Comment by gep13** [comment]
@punker76 can you offer anything with regard to how SVG's are being handled?

**Comment by batzen** [comment]
Ok. Will create a PR during the weekend.

**Comment by gep13** [comment]
@batzen just wanted to touch base to see if this is still something that you are interested in tackling.  Thanks

**Comment by batzen** [comment]
Sure. Will create the PR later today. Wasted some time trying to figure out the svg issue, but couldn't find a solution.
