### ISSUE TITLE
Option to have auto check for new versions of installed packages and notify user

### ISSUE THREAD

**Issue by bsara** [chocolatey/ChocolateyGUI#74]
Basically I'm looking for a feature like windows update. I get notified, I can set it up to automatically update my packages or just notify me of available updates and then choose to run the updates.

**Comment by gep13** [comment]
Based on the feature set that is coming with Chocolatey, adding this feature to ChocolateyGUI doesn't make much sense.  This functionality will be in Chocolatey, and doesn't need to be in ChocolateyGUI.

**Comment by Thilas** [comment]
I didn't find anything about this feature in chocolatey. Do you know if it's still planned?
If relevant, I propose to work on this in ChocolateyGui.
