### ISSUE TITLE
Suggestion for local source view  context menu

### ISSUE THREAD

**Issue by punker76** [chocolatey/ChocolateyGUI#745]
I have this suggestion for the context menu at the local source view, because of miss clicking the uninstall menu... 🙅‍♂ 

Currently we have

![2020-04-02_18h36_55](https://user-images.githubusercontent.com/658431/78276106-dd3f5d80-7512-11ea-8ea5-aec4debeb49e.png)

My suggestion is to re-sort this to this

![2020-04-02_18h36_551](https://user-images.githubusercontent.com/658431/78276137-e8928900-7512-11ea-8ae1-2892c9743246.png)

/cc @gep13 @pascalberger @ferventcoder @mwallner @RichiCoder1

**Comment by mwallner** [comment]
Lgtm!

**Comment by gep13** [comment]
@punker76 this seems like a good improvement to me!
