### ISSUE TITLE
Replace Log4Net with something else (NLog, Serilog)

### ISSUE THREAD

**Issue by punker76** [chocolatey/ChocolateyGUI#764]
We should maybe replace Log4Net with another logging library, because of this

> As of April 1, 2020 Log4Net is a dormant project of Apache Logging Services. The dormant status means the project has been classified as inactive since it has had no recent development activity and there are no active volunteers to perform code reviews, commit code, or perform releases. Although it is possible volunteers might choose to participate in the future, it is best to assume there will be not future development or releases.

**Comment by AdmiringWorm** [comment]
@punker76 ChocolateyGUI don't use `Log4Net`, but rather `Serilog`.
The dependency on `Log4Net` comes from chocolatey itself, which uses that logging framework.

**Comment by gep13** [comment]
Yes, this is as @AdmiringWorm said.  Chocolatey, and as a result, the Chocolatey.Lib (which we take a dependency on) uses log4net, and as a result, the dependency is brought in.  I don't think this is going to change in the near future.

**Comment by gep13** [comment]
@punker76 I am going to go ahead and close this out.  Feel free to open again if you want to discuss further.
