### ISSUE TITLE
running Start-ChocolateyProcessAsAdmin works differently in ChocolateyGUI

### ISSUE THREAD

**Issue by two9seven** [chocolatey/ChocolateyGUI#766]
I have created a chocolatey package that includes a portion to run a .bat file. 
I am using Start-ChocolateyProcessAsAdmin to run the .bat file
It works fine when I run choco install from the cli but it does not work correctly when the package is installed with chocolateyGUI. Any ideas why I would get different results?

I'm running a bunch of command like this:

REM On 64-bit systems, eXtreme registers in the 32-bit node in the registry.
SET UNINSTALLKEY64=HKLM\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall

REM ==========================================
REM Bluebeam v19 Base Release 19.0.15 Master
REM ==========================================

REM Uninstall Bluebeam Revu 19.0.15: 
SET GUID={4BB92938-EBC4-45F1-A3AE-E1EB80574DA9}
REG QUERY %UNINSTALLKEY%\%GUID%>nul 2>nul
IF "%ERRORLEVEL%"=="0" msiexec.exe /x %GUID% /qn 

REM Uninstall Bluebeam Revu 19.0.15 x64:
SET GUID={74A435D8-FE24-498A-9809-76541D74182A}
REG QUERY %UNINSTALLKEY%\%GUID%>nul 2>nul
IF "%ERRORLEVEL%"=="0" msiexec.exe /x %GUID% /qn

**Comment by two9seven** [comment]
Here are two lines showing the same command in chocolatey cli and ChocolateyGUI. They are running from two different locations. 

the batch files are using variables. Are variables an issue?

`2020-03-20 12:43:00.203 -07:00 [Information] C:\Program Files (x86)\Chocolatey GUI>SET GUID={4BB92938-EBC4-45F1-A3AE-E1EB80574DA9} 
2020-04-15 16:46:12,632 8996 [INFO ] - VERBOSE: C:\Windows\system32>SET GUID={4BB92938-EBC4-45F1-A3AE-E1EB80574DA9} `

**Comment by gep13** [comment]
@two9seven are you able to provide a small package, that has a minimal reproduction of the issue that you are seeing?  I think that this will help to try to figure out what is going on.

**Comment by two9seven** [comment]
Here is something. Not sure if it helps. I've assumed the issue is realated to environment varables like %ERRORLEVEL%. I've attached the .nuspec package here. I've renamed the extension to zip. 
[batchtest.0.0.1.zip](https://github.com/chocolatey/ChocolateyGUI/files/4512473/batchtest.0.0.1.zip)

**Comment by two9seven** [comment]
I reuploaded the package here. I made a typo.

**Comment by two9seven** [comment]
So after all that I found something else. The orginal batch script runs this command:

`REG QUERY HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\{74A435D8-FE24-498A-9809-76541D74182A}`

I get to different results when running the command from C:\Windows\system32 and C:\Program Files (x86)\Chocolatey GUI.

This is the real issue. Why is this happening?

**Comment by two9seven** [comment]
I'm anwering all my own questions! Looks like

`REG QUERY HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\{74A435D8-FE24-498A-9809-76541D74182A} `

cannot be run from an elevated console

**Comment by two9seven** [comment]
it works when when I escape the {} symbols while in an elevated shell. 

> REG QUERY HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\`{74A435D8-FE24-498A-9809-76541D74182A`}

**Comment by two9seven** [comment]
Here's an updated package. You will need to edit the uninstall path to test on your system. 
[batchtest.0.0.1.zip](https://github.com/chocolatey/ChocolateyGUI/files/4513038/batchtest.0.0.1.zip)

**Comment by two9seven** [comment]
@gep13 Any ideas here?

**Comment by two9seven** [comment]
I think this issue has to do with accessing registry entries. not sure it is related to star-chocolateyProcessAsAdmin.
