### ISSUE TITLE
Provide ability to "see" persisted arguments for installed package

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#770]
This is similar to this issue: https://github.com/chocolatey/ChocolateyGUI/issues/767 but would allow only viewing of the arguments that were used, and not in the context of doing an upgrade.

**Comment by gep13** [comment]
Perhaps related to this issue: https://github.com/chocolatey/choco/issues/1310

**Comment by AdmiringWorm** [comment]
Re-Opening as there is additional minor work needed to complete this issue.
