### ISSUE TITLE
ChocolateyGUI crashes on start

### ISSUE THREAD

**Issue by Atue001** [chocolatey/ChocolateyGUI#773]
![Crash](https://user-images.githubusercontent.com/65370002/81986419-0ede3500-9638-11ea-8c06-27f1c6cd10e9.JPG)

Unhandled Exception on start of ChocolateyGUI. See attached file with Unhandled Exception Message from Windows.

**Comment by Bruno21** [comment]
Crash on start too.

![chocolateyguy](https://user-images.githubusercontent.com/4353024/101377052-a693c100-38b1-11eb-8323-173c9dde3d91.png)

**Comment by punker76** [comment]
@Atue001 @Bruno21 Can you try to delete all the files in this folder `C:\Users\<USER>\AppData\Local\Chocolatey GUI` ?

**Comment by Atue001** [comment]
Some updates later - the error is resolved.

**Comment by gep13** [comment]
Thank you for confirming, I will go ahead and close this issue.
