### ISSUE TITLE
Could not search on remote source after changed from GH-771

### ISSUE THREAD

**Issue by punker76** [chocolatey/ChocolateyGUI#775]
This happens because of the wrong parameters now on LoadPackages. Better changing this to SearchForPackages and CanSearchForPackages to prevent such a mistake in the future.

![image](https://user-images.githubusercontent.com/658431/82499242-a4267100-9af1-11ea-9aae-c1e5a9e166bf.png)

**Comment by gep13** [comment]
This was a bug that was introduced with a feature that is being added to the 0.18.0 release, as such, this bug doesn't need to be assigned to the 0.18.0 milestone.

This is related to this issue: https://github.com/chocolatey/ChocolateyGUI/issues/769 and this PR: https://github.com/chocolatey/ChocolateyGUI/pull/771
