### ISSUE TITLE
Add feature toggle to all read only view for installed packages

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/ChocolateyGUI#780]
NOTE: While this feature toggle will exist within the OSS version of Chocolatey GUI, it will not be used, and this feature will only be acted on by the Chocolatey GUI Licensed Extension.

Related issue was created here: https://github.com/chocolatey/chocolatey-licensed-issues/issues/201

**Comment by felix-kolbe** [comment]
Would it be enough to start Chocolatey GUI _without_ administrator rights?  -- Although I'm not sure how to do that currently. I think it was possible some time ago, but nowadays the GUI itself requests rights elevation.
