### ISSUE TITLE
Ask to confirm Uninstall/Reinstall from Right-Click Menu

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey/ChocolateyGUI#786]
When you open the right-click menu for any installed application, you should get a confirmation prompt if you click on Uninstall or Reinstall. If they are clicked accidentally when the user actually wanted to click on Pin or Details, the user might lose important data.

**Comment by simonhollingshead** [comment]
Agreed.  My brain just looks for a menu item beginning with 'U' when doing updates, and since for some reason the right click menu has 'uninstall' further up than 'update,' I've uninstalled packages I meant to update in excess of ten times this year so far.

**Comment by punker76** [comment]
@opusforlife2 @simonhollingshead Which version are you using? Because we made already some changes to the menu, because of the same reason (pre-release 0.18.x).

![image](https://user-images.githubusercontent.com/658431/101042593-a62bbb00-357d-11eb-8b5d-9b8b10599482.png)

Related to #745 #753 

/cc @gep13

**Comment by simonhollingshead** [comment]
Oh, awesome.  I'm using the latest one the chocolatey package installed, which appears to be 0.17.2.0.  That change in 0.18 looks nice.

**Comment by opusforlife2** [comment]
Same. 0.17.2.

**Comment by gep13** [comment]
There are details on the readme of this repository for how you can try out the latest pre-release version.

Would be good to get some feedback on it.

**Comment by simonhollingshead** [comment]
I've updated to version 0.18.0-alpha.426.  I do like the new order.  I'm not sure if it's quite as safe (not that I've tested) as an actual confirmation dialog would be, but I expect I'll make less misclicks now regardless.

**Comment by opusforlife2** [comment]
I think it would be better to have a confirmation dialogue at least in the case of Uninstall, but preferably for Reinstall as well. Isn't it common practice in OS's and other software that a change which can cause data loss is always accompanied by a confirmation?

**Comment by gep13** [comment]
Similar issues exist for other operations:

- https://github.com/chocolatey/ChocolateyGUI/issues/786
- https://github.com/chocolatey/ChocolateyGUI/issues/828
- https://github.com/chocolatey/ChocolateyGUI/issues/827
