### ISSUE TITLE
Results broken when searching for term "git"

### ISSUE THREAD

**Issue by juventus18** [chocolatey/ChocolateyGUI#794]
When I search packages for the term "git" the GUI says there are 4 pages of results, but does not display the results in the pane.

I'm on a macbook pro bootcamped into windows 10

![image](https://user-images.githubusercontent.com/1124513/97212499-bb8f1780-177d-11eb-8be3-4b1856ef009e.png)

**Comment by mwallner** [comment]
can you still reproduce the behavior? - might have been a temporary issue with the community repository.

**Comment by juventus18** [comment]
@mwallner checked again today, still same behavior.

**Comment by juventus18** [comment]
its working today - maybe two issues with the community repository  :)
