### ISSUE TITLE
Globalisation - Spanish

### ISSUE THREAD

**Issue by tmbsis** [chocolatey/ChocolateyGUI#795]
Can i help? mexican here

**Comment by gep13** [comment]
@tmbsis thanks for your offer to help out, it would be great to have you helping out.

We use a system called Transifex to help with the localisation of the application.  You can find the project here:

https://www.transifex.com/chocolatey/public/

You should be able to request to be added to the team, and from there, you can help out with getting the strings translated.

Let me know if you have any questions.

**Comment by gep13** [comment]
I am going to close this off, let me know if you have any questions.
