### ISSUE TITLE
Crash on Application start - kernelbase.dll error

### ISSUE THREAD

**Issue by sneuweger** [chocolatey/ChocolateyGUI#801]
When i start the app i get a massive long error message which unfortunately i am not able to copy.
I checked the application log in the event viewer and found the following errors:

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-01-13T11:50:18.4393633Z" /> 
  <EventRecordID>4407</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>PixelmachineX64</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>ChocolateyGui.exe</Data> 
  <Data>0.17.2.0</Data> 
  <Data>5f0c751e</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.19041.662</Data> 
  <Data>ec58f015</Data> 
  <Data>e0434352</Data> 
  <Data>000000000002d759</Data> 
  <Data>4394</Data> 
  <Data>01d6e9a22bbd1846</Data> 
  <Data>C:\Program Files (x86)\Chocolatey GUI\ChocolateyGui.exe</Data> 
  <Data>C:\Windows\System32\KERNELBASE.dll</Data> 
  <Data>376c2366-4c62-4211-b932-991783f5afd5</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

And second error

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-01-13T11:50:18.3609698Z" /> 
  <EventRecordID>4406</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>PixelmachineX64</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application: ChocolateyGui.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.Xml.XmlException at System.Xml.XmlTextReaderImpl.Throw(System.Exception) at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef) at System.Xml.XmlTextReaderImpl.ParseText() at System.Xml.XmlTextReaderImpl.ParseElementContent() at System.Configuration.XmlUtil.StrictReadToNextElement(System.Configuration.ExceptionAction) at System.Configuration.BaseConfigurationRecord.ScanFactoriesRecursive(System.Configuration.XmlUtil, System.String, System.Collections.Hashtable) at System.Configuration.BaseConfigurationRecord.ScanFactoriesRecursive(System.Configuration.XmlUtil, System.String, System.Collections.Hashtable) at System.Configuration.BaseConfigurationRecord.ScanFactories(System.Configuration.XmlUtil) at System.Configuration.BaseConfigurationRecord.InitConfigFromFile() Exception Info: System.Configuration.ConfigurationErrorsException at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean) at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors) at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs) Exception Info: System.Configuration.ConfigurationErrorsException at System.Configuration.ConfigurationManager.PrepareConfigSystem() at System.Configuration.ConfigurationManager.GetSection(System.String) at System.Runtime.Caching.MemoryCacheStatistics.InitializeConfiguration(System.Collections.Specialized.NameValueCollection) at System.Runtime.Caching.MemoryCacheStatistics..ctor(System.Runtime.Caching.MemoryCache, System.Collections.Specialized.NameValueCollection) at System.Runtime.Caching.MemoryCache.InitDisposableMembers(System.Collections.Specialized.NameValueCollection) at System.Runtime.Caching.MemoryCache.Init(System.Collections.Specialized.NameValueCollection) at System.Runtime.Caching.MemoryCache.get_Default() at ChocolateyGui.Common.Windows.ViewModels.Items.PackageViewModel..ctor(ChocolateyGui.Common.Services.IChocolateyService, Caliburn.Micro.IEventAggregator, AutoMapper.IMapper, ChocolateyGui.Common.Windows.Services.IProgressService, ChocolateyGui.Common.Services.IChocolateyGuiCacheService, ChocolateyGui.Common.Services.IConfigService) at DynamicClass.lambda_method(System.Runtime.CompilerServices.Closure, System.Object[]) at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() Exception Info: Autofac.Core.DependencyResolutionException at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(Autofac.IComponentContext, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>) at Autofac.Core.Resolving.InstanceLookup.Activate(System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>) Exception Info: Autofac.Core.DependencyResolutionException at Autofac.Core.Resolving.InstanceLookup.Activate(System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>) at Autofac.Core.Resolving.InstanceLookup.Execute() at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(Autofac.Core.ISharingLifetimeScope, Autofac.Core.IComponentRegistration, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>) at Autofac.Core.Resolving.ResolveOperation.Execute(Autofac.Core.IComponentRegistration, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>) at Autofac.ResolutionExtensions.TryResolveService(Autofac.IComponentContext, Autofac.Core.Service, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>, System.Object ByRef) at Autofac.ResolutionExtensions.ResolveService(Autofac.IComponentContext, Autofac.Core.Service, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>) at Autofac.ResolutionExtensions.Resolve[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Autofac.IComponentContext, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>) at ChocolateyGui.Common.Windows.Bootstrapper+<>c.<OnStartup>b__37_2(ChocolateyGui.Common.Models.Package) at DynamicClass.lambda_method(System.Runtime.CompilerServices.Closure, System.Object, System.Object, AutoMapper.ResolutionContext) at AutoMapper.Mapper.AutoMapper.IMapper.Map[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object) at System.Linq.Enumerable+WhereSelectArrayIterator`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext() at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>) at System.Linq.Enumerable.ToList[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>) at ChocolateyGui.Common.Windows.ViewModels.LocalSourceViewModel+<LoadPackages>d__67.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) at ChocolateyGui.Common.Windows.ViewModels.LocalSourceViewModel+<OnInitialize>d__65.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.DispatcherOperation.InvokeImpl() at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object) at System.Windows.Threading.DispatcherOperation.Invoke() at System.Windows.Threading.Dispatcher.ProcessQueue() at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32) at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr) at MS.Win32.UnsafeNativeMethods.MessageBox(System.Runtime.InteropServices.HandleRef, System.String, System.String, Int32) at System.Windows.MessageBox.ShowCore(IntPtr, System.String, System.String, System.Windows.MessageBoxButton, System.Windows.MessageBoxImage, System.Windows.MessageBoxResult, System.Windows.MessageBoxOptions) at System.Windows.MessageBox.Show(System.String) at ChocolateyGui.Common.Windows.Bootstrapper+<OnStartup>d__37.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.DispatcherOperation.InvokeImpl() at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object) at System.Windows.Threading.DispatcherOperation.Invoke() at System.Windows.Threading.Dispatcher.ProcessQueue() at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32) at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr) at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef) at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame) at System.Windows.Application.RunDispatcher(System.Object) at System.Windows.Application.RunInternal(System.Windows.Window) at ChocolateyGui.App.Main(System.String[])</Data> 
  </EventData>
  </Event>

Any idea how this can be solved? .Net Framework 4,8 is installed

**Comment by gep13** [comment]
@sneuweger can you please try the following...

* Close Chocolatey GUI
* Open the following folder in Windows Explorer `C:\Users\<your username>\AppData\Local\Chocolatey GUI`
* Delete all files that are contained within there
* Try opening Chocolatey GUI

Does this help?

**Comment by punker76** [comment]
@sneuweger Any news for your issue? Have you tried the note from @gep13 ?

**Comment by sneuweger** [comment]
> @sneuweger Any news for your issue? Have you tried the note from @gep13 ?

Sorry for answering late.
Yes it did solve my issue.👍

**Comment by danbromberg** [comment]
Deleting all the files in AppData solved my issue as well - thanks!
Dan
