### ISSUE TITLE
Extremely slow load time

### ISSUE THREAD

**Issue by aminya** [chocolatey/ChocolateyGUI#803]
It loads almost a minute for chocolatey GUI to load. This is while my whole Edge browser loads in under a second.

**Comment by gep13** [comment]
@aminya there are a number of things happening with Chocolatey GUI loads up, for example, calculating which packages are outdated, which packages are installed, etc. 

Can you please provide some more information about your setup?

For example, what version of Chocolatey GUI are you using?
How many packages do you have installed?
How many of those packages are outdated?
How many sources do you have configured?

There are a number of new features in the pre-release version of Chocolatey GUI that aim to address some of the loading times.

**Comment by aminya** [comment]
All of the things you are describing can be written so they are async background services and that should run other threads. The number of packages does not justify the slow load time. I have many extensions in my browser, but the browser loads instantly.

I have only one source which is the default choco server, and this is the version:

![image](https://user-images.githubusercontent.com/16418197/107096749-097dd780-67d1-11eb-8437-91eb2f085702.png)

**Comment by mwallner** [comment]
hey @aminya, there are some issues in the current nuget/ODATA provider that Chocolatey uses to communicate with repositories.

If you could answer @gep13 's quesions
* how many packages do you have installed
* how many of them are outdated
* how many source do you've got configured

.. that may give us some idea on why the load performance is so bad at your machine.
how long does a plain `choco outdated` (command line call) take in comparison to starting Chocolatey GUI?

i.e. (start PowerShell.exe as admin)
```
Measure-Command { choco outdated -r }
```

**Comment by aminya** [comment]
I understand that checking for the outdated packages might take a long time, but I don't understand why this checking should happen during the startup in a blocking manner. Usually, the programs do their best to not block the UI by making everything run asynchronously and on other threads. 


Here is more info in case it helps:

```ps1
❯ Measure-Command { choco outdated -r }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 18
Milliseconds      : 715
Ticks             : 187150318
TotalDays         : 0.000216609164351852
TotalHours        : 0.00519861994444444
TotalMinutes      : 0.311917196666667
TotalSeconds      : 18.7150318
TotalMilliseconds : 18715.0318

```

```ps1
❯ choco list -l
131 packages installed.
```
