### ISSUE TITLE
Crash everytime on loading details

### ISSUE THREAD

**Issue by timon89** [chocolatey/ChocolateyGUI#806]
This is a bug:

Chocolatey GUI crash everytime on loading details of any package!

I use: Win10 Pro Build 19042 (Version 20H2)

![ChocolateyGUI](https://user-images.githubusercontent.com/59319696/106385262-b6221880-63cf-11eb-809a-e2c6e9804225.gif)

![image](https://user-images.githubusercontent.com/59319696/106385409-7e67a080-63d0-11eb-9c05-997d0eb042d9.png)

Error on Windows Eventlog:
![image](https://user-images.githubusercontent.com/59319696/106385307-fa151d80-63cf-11eb-9bbd-713cfbcac443.png)

**Comment by gep13** [comment]
@timon89 sorry to hear that you are having issues!

Can you please confirm what graphics card is being used on the machine where Chocolatey GUI is installed?

We have seen an issue similar to this where an integrated Intel Graphics card was being used.  The solution here was to update the driver for the card.

This may not be the same driver that you require, but it is the one that solved the problem in the other instance:

https://downloadcenter.intel.com/download/29616/Intel-Graphics-Windows-10-DCH-Drivers?product=98909

**Comment by BPDunbar** [comment]
I have been having the same issue.

I have tried uninstalling and reinstalling. which hasn't helped.

My graphics card is an NVIDIA GeForce GTX 750 Ti. so it is affecting computers with entirely different graphics drivers.

My windows event log:

Log Name:      Application
Source:        Application Error
Date:          10/02/2021 05:28:07 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Desktop
Description:
Faulting application name: ChocolateyGui.exe, version: 0.17.3.0, time stamp: 0x6017c606
Faulting module name: nvopencl64.dll, version: 27.21.14.6542, time stamp: 0x600c6dcb
Exception code: 0xc0000005
Fault offset: 0x000000000000dfdb
Faulting process ID: 0x7d4
Faulting application start time: 0x01d6ffd16f5aee1f
Faulting application path: C:\Program Files (x86)\Chocolatey GUI\ChocolateyGui.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_80bf37d61ebcc3c3\nvopencl64.dll
Report ID: b6f930ce-4f06-4c42-94e7-04ff769f36e0
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-02-10T17:28:07.1651724Z" />
    <EventRecordID>3691</EventRecordID>
    <Correlation />
    <Execution ProcessID="15720" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Desktop</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ChocolateyGui.exe</Data>
    <Data>0.17.3.0</Data>
    <Data>6017c606</Data>
    <Data>nvopencl64.dll</Data>
    <Data>27.21.14.6542</Data>
    <Data>600c6dcb</Data>
    <Data>c0000005</Data>
    <Data>000000000000dfdb</Data>
    <Data>7d4</Data>
    <Data>01d6ffd16f5aee1f</Data>
    <Data>C:\Program Files (x86)\Chocolatey GUI\ChocolateyGui.exe</Data>
    <Data>C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_80bf37d61ebcc3c3\nvopencl64.dll</Data>
    <Data>b6f930ce-4f06-4c42-94e7-04ff769f36e0</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by BPDunbar** [comment]
Tried a clean install of the graphics driver. It is now working.

**Comment by punker76** [comment]
@timon89 Any news for this? Have you tried to update the graphics driver?

**Comment by pauby** [comment]
I'm going to go ahead and close this, but we can reopen it if necessary.
