### ISSUE TITLE
UX Feedback: Out of Date label feels like a button

### ISSUE THREAD

**Issue by Windos** [chocolatey/ChocolateyGUI#815]
While checking out Choco GUI it picked up that I had two out of date packages and labelled them as such the Latest Version column.

My initial instinct was to click the label and I was expecting to be prompted to confirm my desire to update the packages.

It actually took me a little longer than I'd like to admit to to realise I had to right click on the package(s) to get at the update option (I hadn't yet found the update all button either.)

**Comment by gep13** [comment]
Just to provide some context around this issue, I am assuming that you are talking about the `Out of date` banner which is shown in this mock up of Chocolatey GUI:

![image](https://user-images.githubusercontent.com/1271146/110122181-2fd66900-7db7-11eb-9c50-ec67144879da.png)

This is shown as the following when using the tile view:

![image](https://user-images.githubusercontent.com/1271146/110122299-5a282680-7db7-11eb-990c-58be7c9b414a.png)

Given that the information can be shown in different formats, I am hesitant to make clicking the banner to actually perform an action.

As you have pointed out, right click on the item in the list, provides the option to update the package:

![image](https://user-images.githubusercontent.com/1271146/110122462-9196d300-7db7-11eb-9c37-4c63dbda68fd.png)

Also double clicking on the entry would bring up the details page, where you can also perform the required action:

![image](https://user-images.githubusercontent.com/1271146/110122545-abd0b100-7db7-11eb-8dd2-26fcf10abe59.png)

There is also a button at the top of the application to update all packages:

![image](https://user-images.githubusercontent.com/1271146/110122753-e9353e80-7db7-11eb-804e-a1723f20cae7.png)

If that is the operation that you are really wanting to perform.

Does any of this help?

**Comment by Windos** [comment]
Yeah it does.

Sorry this issue was sort of a stream of consciousness from a first-time user of ChocolateyGUI and the process of trying to figure things out for the first time.
