### ISSUE TITLE
Add confirmation dialog for update all button

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#828]
This operation can potentially take a long time, and we should confirm with the user as to whether they really want to do this right now.

**Comment by gep13** [comment]
Similar issues exist for other operations:

- https://github.com/chocolatey/ChocolateyGUI/issues/786
- https://github.com/chocolatey/ChocolateyGUI/issues/828
- https://github.com/chocolatey/ChocolateyGUI/issues/827

**Comment by opusforlife2** [comment]
Or the ability to cancel the operation?

**Comment by gep13** [comment]
@opusforlife2 that work would be covered as part of a different issue, for example here:

https://github.com/chocolatey/ChocolateyGUI/issues/720

**Comment by opusforlife2** [comment]
@gep13 I know. That's my issue. :P 

What I was suggesting is that this doesn't need to be implemented if the ability to cancel already exists.

**Comment by gep13** [comment]
I understand your point, and I was aware that it was your issue. The main reason that I created this issue, with the links to the other ones, is for consistency.  When starting an operation that is potentially destructive, or which may take a long time to complete, a modal window asking whether the user is sure makes sense.  We already have some modals for the operations that can be performed on the setting screen, so adding them into each of the listed issues, brings consistency to the application.

Then later, for the longer running processes we should introduce the ability to cancel the operation.  This has to be done in such a way that it doesn't "break" anything, as we wouldn't want an installation/upgrade to end abruptly, and leave the package in a broken state.  That is why it is a different scope of work.

**Comment by opusforlife2** [comment]
Ah. Got it.

**Comment by gep13** [comment]
This has been implemented, and looks like the following:

![image](https://user-images.githubusercontent.com/1271146/114052201-bf26de80-9885-11eb-96b3-61d4c89f81ff.png)

**Comment by opusforlife2** [comment]
Awesome! Thank you so much! :D
