### ISSUE TITLE
Chocolatey GUI reverts to List View after making a change in settings

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#830]
Starting with Chocolatey GUI 0.18.0, the default is to show both local and remote sources using the Tile View.  This works on application startup, and persists across closing and opening the application, however, if you modify another settings, i.e. toggling a feature on or off, when you return to the main screen, the Tile View will no longer be being used, and instead, it will have reverted to the List View.

## Steps to reproduce

1. Open Chocolatey GUI
2. Verify that Tile View is shown by default
3. Click on the settings link
4. Toggle on (or off) the Show Console Output feature
5. Click the back button to return to main screen
6. See that the List View is now shown, rather than the default Tile View

**Comment by punker76** [comment]
@gep13 I also noticed this yesterday :-(

**Comment by punker76** [comment]
@gep13 This happens also if I change any of the other settings e.g. like the outdated package duration time.

**Comment by gep13** [comment]
@punker76 yip, I messed up 😢 I know where the issue is, and I have a local fix for it.  Yip, this isn't only on the Show Console Output feature, this was just an example.
