### ISSUE TITLE
Ensure that all transactions are persisted to configuration databases

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#832]
Starting with LiteDB 5.x.x, the ways that transactions are handled in the database has changed.  When a transaction hasn't been persisted to the main data.db file, it exists as a transaction within a data-log.db file.  To ensure that these transactions make their way into the main data.db file, we need to make sure to dispose of the database correctly once everything is completed.

Not doing this leads to transactions not being committed properly to the database, and as a result, inconsistencies in how the application will work.

**Comment by gong86** [comment]
I have a big data-log.db file 1.31GB and my Chocolatey GUI is v0.19.0.0, can I delete this db file? If not, how can I clean it? Thank you.
