### ISSUE TITLE
Tile/List view preferences does not persist

### ISSUE THREAD

**Issue by user8446** [chocolatey/ChocolateyGUI#833]
Startup is always in tile view but after changing to list view and restarting the view defaults back to tile view.
This seems to be a resurface of this before : https://github.com/chocolatey/ChocolateyGUI/issues/524

**Comment by AdmiringWorm** [comment]
This is resolved already, however it is not included in a pushed version yet.
See https://github.com/chocolatey/ChocolateyGUI/issues/830

**Comment by user8446** [comment]
Thank you, I missed that in the search

**Comment by gep13** [comment]
@user8446 I just wanted to make sure that we are talking about the same thing here, as you mentioned:

> after changing to list view and restarting the view defaults back to tile view.

The toggle button in the docs here:

https://docs.chocolatey.org/en-us/chocolatey-gui/user-interface/main-window/actions/tileview

Only changes the selection for the current session of Chocolatey GUI.  If you change this value and restart the application, it will go back to the default setting that has been configured.

If you want to change the default, you will need to use either:

https://docs.chocolatey.org/en-us/chocolatey-gui/setup/configuration/features/default-to-tile-view-for-local-source
https://docs.chocolatey.org/en-us/chocolatey-gui/setup/configuration/features/default-to-tile-view-for-remote-source

As @AdmiringWorm, there was a bug in the 0.18.0 around this, which is shipping in 0.18.1, but I just want to make sure that we are talking about the same thing in this issue.

**Comment by user8446** [comment]
Thank you for the clarification.... I wasn't aware of the change in v0.18 that enables the tile view by default as well as the toggle button only for the current session. Both combined threw me off.
I guess that's what the big bold BREAKING CHANGES in the release notes are for :)

**Comment by gep13** [comment]
@user8446 ha ha, yes, indeed. We try to document everything when things like this happen, but it isn't always clear in the notes.

That is part of the reason that I have been doing short videos on what is going into releases to try to help folks more.  The video for this release is here:

https://www.youtube.com/watch?v=eKXPDmqO-hs
