### ISSUE TITLE
.msi file gone and not reparable

### ISSUE THREAD

**Issue by brian6932** [chocolatey/ChocolateyGUI#835]
There's no ChocolateyGUI.msi in `C:\ProgramData\chocolatey\lib\ChocolateyGUI\tools` anymore. Instead, a `.ignore` was appended to the end, the problem with this is that my .msi in `C:\WINDOWS\Installer\` is missing and I don't know how to repair it, when I run [FixMissingMSI](https://github.com/suyouquan/SQLSetupTools#fixmissingmsi-version-22), I get this error:
![image_107](https://user-images.githubusercontent.com/18603393/112799417-4ed5bd00-903c-11eb-91d1-425a4628119b.png)
![image_106](https://user-images.githubusercontent.com/18603393/112798992-c22aff00-903b-11eb-9f61-695803cc825d.png)

**Comment by gep13** [comment]
@brian6932 as part of the installation of the Chocolatey GUI package (which embeds the msi into the Chocolatey package) we remove the msi once the installation is completed.  This is due to the fact that the MSI is not required once the installation is complete.

I am not familiar with the FixMissingMSI application, and what it is doing, so I am not in a position to comment on what it is reporting.

**Comment by brian6932** [comment]
Hmm I couldn't update because of this bug, and had to migrate a Chocolatey GUI install from another PC, however, even in the other PC `.ignore` was appended, I will mess with this further a later though

**Comment by gep13** [comment]
Can you confirm how you were trying to upgrade or uninstall the package? Were you using the `choco upgrade` or `choco uninstall` commands? There have been no reported issues with either of these commands.

**Comment by brian6932** [comment]
yea I used those commands

**Comment by brian6932** [comment]
Here's the [chocolatey.log](https://github.com/chocolatey/ChocolateyGUI/files/6237132/chocolatey.log) file if you're curious

**Comment by ALERTua** [comment]
same issue for me. cannot install, cannot uninstall

**Comment by gep13** [comment]
@brian6932 the error in the log is the following:

```
Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\ChocolateyGUI_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
```

Have you tried doing what it suggests?

**Comment by gep13** [comment]
@ALERTua can you provide log files for the attempts that you are making?

**Comment by ALERTua** [comment]
[ChocolateyGUI_msi_install.log](https://github.com/chocolatey/ChocolateyGUI/files/6249056/ChocolateyGUI_msi_install.log)

**Comment by brian6932** [comment]
@ALERTua Update: I was cleaning up my packages and decided to take a crack at it again, and I managed to get it.

1. You'll need a spare PC with Chocolatey installed
2. Install the exact version you're having uninstallation difficulty with on the spare PC, in my case: `choco install chocolateygui --version=0.17.3`
3. Once the install is complete, grab the following folders, and copy them to the affected PC in the same paths: `C:\Program Files (x86)\Chocolatey GUI` and `C:\ProgramData\chocolatey\lib\ChocolateyGUI`
4. Make sure that if the affected PC has `C:\ProgramData\chocolatey\lib-bad\ChocolateyGUI` as a path, to delete it
5. Finally on the affected PC, run `choco install chocolateygui --version=0.17.3 --force`, and now you should be able to `upgrade` and `uninstall` again.

**Comment by ALERTua** [comment]
@brian6932, thank you, I have already fixed my ChocolateyGUI using this method earlier in April, just forgot to describe the steps here.
