### ISSUE TITLE
Support per-monitor DPI

### ISSUE THREAD

**Issue by ongun-kanat** [chocolatey/ChocolateyGUI#836]
High-DPI displays are getting common each passing day. However, many users like me still own Low-DPI screens and use them in combination with newer High-DPI monitors. My laptop has a 1080p display and I connect it to a 4K display with 125% scaling. This causes the embedded display to be rendered 96 DPI while the 4K display to be rendered in 120 DPI. 

Windows 10 has an API to support multiple displays with different DPI values (https://github.com/microsoft/WPF-Samples/tree/master/PerMonitorDPI). For applications that doesn't support this API, Windows scales the window by stretching the rendered raster of the window. Currently, Chocolatey GUI is rendered blurry if I move the window to my 4K display. Implementing per-monitor DPI support for Chocolatey GUI would provide a better user experience overall.

**Comment by gep13** [comment]
@ongun-kanat thanks for raising this issue!

@punker76 is this something that MahApps can help with?

**Comment by punker76** [comment]
@gep13 We can do this by targeting the Gui to v4.6.2 .Net Framework.

**Comment by gep13** [comment]
@punker76 ah, gotcha. Ok, let me get back to you on that one 😄

**Comment by gep13** [comment]
@punker76 we have discussed this internally, and we have decided that we can move forward with changing the target .NET Framework version.  Related issue has been created here: https://github.com/chocolatey/ChocolateyGUI/issues/841

Once we change the .NET Framework version, what else is needed from a MahApps perspective to enable high DPI support?

**Comment by punker76** [comment]
@gep13 Just use highest target for MahApps (4.7) and add an `app.manifest` like [this one](https://github.com/MahApps/MahApps.Metro.IconPacks/blob/a24bc41dddd8c896949e6f6d01512ffbb14bed94/src/MahApps.Metro.IconPacks.Browser/app.manifest)

These settings are the relevant ones

https://github.com/MahApps/MahApps.Metro.IconPacks/blob/a24bc41dddd8c896949e6f6d01512ffbb14bed94/src/MahApps.Metro.IconPacks.Browser/app.manifest#L34-L42

**Comment by gep13** [comment]
@ongun-kanat I have just made a commit into the repository that adds in the changes to the app.manifest that @punker76 suggested.  This will result in a new package being pushed to our MyGet feed as a pre-release package.

Would you be willing to take this for a spin to confirm that it is now working as expected?

If so, you should be able to install the pre-release package using the following command:

```
choco upgrade chocolateygui --pre --version 0.19.0-alpha0169 --source https://www.myget.org/F/chocolateygui/
```

Please let us know if you have any problems/questions.

**Comment by punker76** [comment]
@gep13 Works on my machine TM (125 %)

![image](https://user-images.githubusercontent.com/658431/114582281-bd438d80-9c80-11eb-89e0-a89185bf246c.png)

**Comment by gep13** [comment]
@punker76 sweet! Will wait for @ongun-kanat to confirm, and then we can close out this issue.

**Comment by ongun-kanat** [comment]
It works great! Thank you very much!

100% - 1080p

![chocolatey-gui-100](https://user-images.githubusercontent.com/3601965/114584242-bfa6e700-9c82-11eb-9c35-e5772e4dcf41.png)

125% - 4K

![chocolatey-gui-125](https://user-images.githubusercontent.com/3601965/114584253-c33a6e00-9c82-11eb-835f-8a1b604ef852.png)

Install screen in 125%

![install-125](https://user-images.githubusercontent.com/3601965/114584290-ce8d9980-9c82-11eb-8420-015969d9e246.png)

**Comment by gep13** [comment]
That is great! Thanks for confirming!
