### ISSUE TITLE
Add the Wix binaries to the sources

### ISSUE THREAD

**Issue by nils-a** [chocolatey/ChocolateyGUI#845]
As per suggestion on https://wixtoolset.org/documentation/manual/v3/msbuild/daily_builds.html the sources should contain the required Wix binaries.

This would remove the need to have Wix installed on local systems and especially on CI systems.

**Comment by gep13** [comment]
This seems like a sensible approach to me, especially if this is what is recommended by the WiX developers themselves.

Currently, we require that folks wanting to build the application to install wixtoolset package, and lucky it is already installed on AppVeyor build agent, but pulling it into source would mean that we can build elsewhere without needing to jump through hoops to install (as the installation takes quite a long time from what I remember).
