### ISSUE TITLE
[Feature Request] Add a feature to export and import installed apps list

### ISSUE THREAD

**Issue by Cyberavater** [chocolatey/ChocolateyGUI#850]
Say, I currently I've many apps installed via Chocolatey now if I migrate to new OS have to install them one by one, but if I could import the list of apps, I could just load it in the new OS and all will be installed at once.

**Comment by gep13** [comment]
@Cyberavater Thanks for reaching out!

it is already possible to export a list of packages from within Chocolatey GUI, this is documented here:

https://docs.chocolatey.org/en-us/chocolatey-gui/user-interface/main-window/actions/export

And there is already an open issue for allowing to import this file here:

https://github.com/chocolatey/ChocolateyGUI/issues/248

As such, I am going to go ahead and close out this issue as a duplicate.

**Comment by Cyberavater** [comment]
Thanks, will be waiting for the import button.
