### ISSUE TITLE
Some GUI settings do not persist.

### ISSUE THREAD

**Issue by BlueAmulet** [chocolatey/ChocolateyGUI#853]
Every time I run the Chocolatey GUI, the app starts in light mode and in tile view. I have to change it to dark mode and list view every time.

I'm running ChocolateyGUI 0.18.1.0 on Windows 10 64bit 2004

**Comment by gep13** [comment]
@BlueAmulet sorry to hear that you are having problems. Can I ask that you have a read through here and watch the video, to see if that helps with what you are seeing: https://docs.chocolatey.org/en-us/chocolatey-gui/setup/configuration/features/default-to-tile-view-for-local-source

**Comment by BlueAmulet** [comment]
Thanks, I disabled DefaultToTileViewForLocalSource and DefaultToTileViewForRemoteSource and enabled DefaultToDarkMode

Seems a bit silly that there's no settings for this in the gui itself though.
