### ISSUE TITLE
Contributing.md has broken links

### ISSUE THREAD

**Issue by KrisBierma** [chocolatey/ChocolateyGUI#854]
I’d like to contribute to Chocolatey but some of the links in the Contributing.md are dead, so I thought I’d update it first. There's a link to the CLA, but it’s blank. Is the ChocolateyGUI CLA the same one as the Chocolatey CLA? I know they’re different projects.
dead CLA link: https://www.clahub.com/agreements/chocolatey/ChocolateyGUI 
chocolatey CLA link: https://cla-assistant.io/chocolatey/choco

Also, there’s a link for the mailing list, but it says ‘Content unavailable.’ https://groups.google.com/access-error?continue=https://groups.google.com/g/chocolateygui 
When I do a search for ChocolateyGUI I see ‘No groups matched.’

Is it possible that the google groups mailing list isn't the best way to communicate? Perhaps it should be updated to gitter?

**Comment by gep13** [comment]
@KrisBierma yes, Chocolatey GUI uses the same CLA as Chocolatey.  You can see it in action on this PR:

https://github.com/chocolatey/ChocolateyGUI/pull/700

Regarding the Google Group, it does look like it is still working, but you will need to be signed in to see it:

https://groups.google.com/g/chocolateygui

It isn't a particularly well used avenue for asking/answering questions though, so I am ok with pointing people in a different direction. While Gitter is good for quick questions, searching isn't great.  I think I would rather direct folks to ask questions via Discussions on the repository:

https://github.com/chocolatey/ChocolateyGUI/discussions

Thoughts?

**Comment by KrisBierma** [comment]
@gep13 For the groups, I'm signed in with my personal email. I can search and see 'conversations matching query chocolateygui' but no 'groups.' If that's not really used, though, then I don't need to find it and this is just an fyi.

Since you're familiar with the project, I'll defer to you about the communication link. From your answer it sounds like the github discussions link is the best option.

**Comment by AdmiringWorm** [comment]
> Regarding the Google Group, it does look like it is still working, but you will need to be signed in to see it:

I wonder if there is some kind of permission issue (ie, the group is set as invite-only, private, etc).
Just tried the google group myself and seems I can not see it either (I never joined the group before).

I think it makes sense to change the link to direct to the discussion GitHub page instead though, due to the low traction in the google group.

**Comment by gep13** [comment]
@AdmiringWorm it could well be that something changed with regard to the permissions of the Google Group, but I would prefer that we switch to Discussions, rather then invest any time in figuring out what is going on there.

@KrisBierma would you be interested in raising a PR to update both of these URL's?
