### ISSUE TITLE
How to accept the Maintainer access for a package? 

### ISSUE THREAD

**Issue by kirankotari** [chocolatey/ChocolateyGUI#860]
The current maintainer has given access to become maintainer, but where can I view the request to accept it? 
Package Link: https://community.chocolatey.org/packages/pyenv-win
Chocolate ID: kkotari

**Comment by gep13** [comment]
@kirankotari this is not the correct repository to ask this question, this repository is for questions/problems with Chocolatey GUI.

However, to answer you question, you should have received an email to the email address that you registered with, and in there will be a link to accept the invite to become a maintainer of the package.

**Comment by kirankotari** [comment]
@gep13 thanks for the response can you please guide the right one please. 

I haven't received any mails regarding the same, I presume it's a bug? 
You can find the screenshot in the following Issue https://github.com/bazzilic/ChocolateyPackages/issues/14

**Comment by gep13** [comment]
Can you confirm if you have checked the junk mail folder in your email provider? Assuming that the email address on your account is correct, then there is no reason that an email confirmation wouldn't have been sent out.

**Comment by kirankotari** [comment]
@gep13 Yes I did. No mail found and my mail id is correct.

**Comment by kirankotari** [comment]
@gep13 Yes, I have asked the owner to reinitiate the access. Now I got the email to accept, but the initial was never found or received.
