### ISSUE TITLE
ChocolateyGUI doesn't show all packages

### ISSUE THREAD

**Issue by ghost** [chocolatey/ChocolateyGUI#865]
Hey
We have an internal package repository on a file share. We've added the path as source to the Chocolatey GUI. But it doesn't show all packages. It shows only 33 packages, when we "All Versions" is disabled". If we enable "All Versions" the GUI shows 50 packages. We can't switch to an other page, there is only 1 page. But we can find the other packages with the search.

**Comment by alexander-augenstein-nnl** [comment]
My team is experiencing a similar issue

We are a C4B customer, not all packages display via Chocolatey GUI when accessing the source we've configured.

There do not appear to be any configuration settings that force Chocolatey GUI to increase the number of pages, or to increase the results per page (similar to --page-size for the find command in the CLI). As @ghost mentioned above, the CLI returns all packages in our configured source.  Per the CLI docs the default behavior of the CLI is to return all pages. Would be a value add if the GUI could also behave this way.

**Comment by pauby** [comment]
I have a repository in a local folder with approx. 75 packages in it. I confirm that I only get 30 packages shown on the first page with no option to use `Next`. It also shows `Page 1/1` at the bottom.

**Comment by alexander-augenstein-nnl** [comment]
Perhaps related:
https://github.com/chocolatey/ChocolateyGUI/issues/331

**Comment by alexander-augenstein-nnl** [comment]
I see the labels applied above and am keeping tabs on those for updates - not soliciting a direct response, just checking in and reporting this issue persists

**Comment by alexander-augenstein-nnl** [comment]
@pauby this issue seems to be resolved as of chocolatey gui v2.1.
If you can repro my success I think this is fine to close. Thanks!

**Comment by pauby** [comment]
I can confirm this is now working as expected for me. Thanks for checking that out and updating the issue @alexander-augenstein-nnl.

**Comment by pauby** [comment]
It is believed that this was fixed as a result of updating to the latest NuGet client libraries in Chocolatey CLI.

**Comment by Joly0** [comment]
Hey @pauby i am running Chocolatey GUI 2.1.1.0 Business and i experience this issue now. I can only see 50 packages, although i have about twice that much packages. Enabling "Show all versions" doesnt change anything, just the packages that are already visible are shown with more versions, but nothing more.

**Comment by pauby** [comment]
@Joly0 this issue is closed. Can you ensure you are using the latest Chocolatey CLI (note that's CLI) version and determine if you can reproduce the error using Chocolatey CLI? If so, can you please raise a new issue sowe can capture all the information?

**Comment by Joly0** [comment]
> [@Joly0](https://github.com/Joly0) this issue is closed. Can you ensure you are using the latest Chocolatey CLI (note that's CLI) version and determine if you can reproduce the error using Chocolatey CLI? If so, can you please raise a new issue sowe can capture all the information?

Sure, the chocolatey cli version installed is 2.4.0 but i am unsure how to reproduce this with the cli? Is there a cli command to list available packages?

**Comment by Joly0** [comment]
It looks like chocolatey gui runs this query:
https://IP:PORT/repository/ChocolateyInternal/v3/query/beta?q=&skip=0&take=50&prerelease=false&semVerLevel=2.0.0
which only displays 50 packages, not more

**Comment by Joly0** [comment]
@pauby I have looked through documentation for chocolatey cli, but havent found a cli command to test this

**Comment by pauby** [comment]
@Joly0 as you are a Chocolatey for Business customer, can you have your technical contact reach out to Support?

**Comment by pauby** [comment]
> It looks like chocolatey gui runs this query:
> https://IP:PORT/repository/ChocolateyInternal/v3/query/beta?q=&skip=0&take=50&prerelease=false&semVerLevel=2.0.0
> which only displays 50 packages, not more

It will display 50 packages on a single page. There are buttons at the bottom to step through the pages. 

If you aware still having issues, please see the previous message about your technical contact and support.
