### ISSUE TITLE
Chocolatey GUI attempted to access a domain blocked for Malware - Trojan

### ISSUE THREAD

**Issue by robertheadley** [chocolatey/ChocolateyGUI#873]
Malwarebytes
www.malwarebytes.com

-Log Details-
Protection Event Date: 8/10/21
Protection Event Time: 1:11 PM
Log File: 56006d08-fa06-11eb-9862-18c04d83f2d8.json

-Software Information-
Version: 4.4.2.123
Components Version: 1.0.1358
Update Package Version: 1.0.44016
License: Premium

-System Information-
OS: Windows 10 (Build 19043.1110)
CPU: x64
File System: NTFS
User: System

-Blocked Website Details-
Malicious Website: 1
, C:\Program Files (x86)\Chocolatey GUI\ChocolateyGui.exe, Blocked, -1, -1, 0.0.0, , 

-Website Data-
Category: Trojan
Domain: feldkir.ch
IP Address: 141.0.23.194
Port: 80
Type: Outbound
File: C:\Program Files (x86)\Chocolatey GUI\ChocolateyGui.exe

(end)

![ChocolateyGui_vjLYAdFlEn](https://user-images.githubusercontent.com/1780455/128930838-6909721f-2d22-4125-9dbf-b4c08c6db00a.png)

**Comment by corbob** [comment]
Hi @robertheadley,

This appears to be related to the [xCmd](https://community.chocolatey.org/packages/xcmd) package icon. If you hover over the icon on the Chocolatey Community Repository page you can see the icon URL: ![image](https://user-images.githubusercontent.com/30301021/129917227-d2ec8478-10e2-4431-80a5-ca126958f032.png)
 
This should have no impact on ChocolateyGUI functionality except for preventing the icon from displaying and possibly preventing the package installation. To resolve this you would need to reach out to the package maintainer to update the package.
