### ISSUE TITLE
Atom installed, doesn't show up 

### ISSUE THREAD

**Issue by morphogencc** [chocolatey/ChocolateyGUI#879]
I'm running the latest version of chocolatey (installed in two days ago) on Windows 10.

I've installed Atom via choco, but it doesn't show up anywhere on my system.  When I try installing it in an admin powershell:

```
PS C:\Windows\system32> choco install atom
Chocolatey v0.10.15
Installing the following packages:
atom
By installing you accept licenses for the packages.
atom v1.58.0 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

Chocolatey installed 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - atom - atom v1.58.0 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
```

But I don't see an Atom folder in Program Files or similar.  I searched my entire computer for "Atom", and the only files are in `C:\ProgramData\chocolatey`.

**Comment by corbob** [comment]
It looks like this is an issue with the Atom package. You'll want to reach out to the package maintainer either through the comments on the package page: https://community.chocolatey.org/packages/atom or through the package source repository.
