### ISSUE TITLE
ChocolateyGUI - Empty Pages Shown When Having Many multiple Package Versions

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/ChocolateyGUI#887]
### Description

When having multiple versions of packages hosted on your source and now having show all versions clicked the UI shows empty pages.

![BlankPages](https://user-images.githubusercontent.com/57045117/132898514-ad7f71d5-c895-4259-b2dd-39459c3c20de.png)

**Comment by gep13** [comment]
@ryanrichter94 i am not sure if I follow what you are saying here. Can you provide more information with as many steps to reproduce as possible? Thanks!

**Comment by ryanrichter94** [comment]
Closing this. will raise new issue with more detail.

**Comment by gep13** [comment]
Why close? Can you not simply update this issue?
