### ISSUE TITLE
Version mismatch after opening GUI while upgrading a package

### ISSUE THREAD

**Issue by Destroy666x** [chocolatey/ChocolateyGUI#962]
### What You Are Seeing?

Latest versions of the main and `(install)` package don't match after I opened GUI while upgrading the main package. Both should be updateable to the same version, but main version has `Update` option completely missing. Probably something got cached incorrectly.
![image](https://user-images.githubusercontent.com/3606072/200048375-67632f17-45c4-4cea-9813-422b49d35e80.png)

### What is Expected?

The local packages UI should reflect correct version status. 

### How Did You Get This To Happen? (Steps to Reproduce)

1. Run `choco upgrade imagemagick -y --debug --verbose`
2. Open GUI before it finishes, not sure if some weird specific timing is needed.
3. Let local tab load to the end. Latest version will be wrong. It'll also be wrong after restart of GUI or uninstalling the package through CLI (but reinstall in GUI worked).

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): 10.0.19045.0
* Windows PowerShell version (Run: `$PSVersionTable`): 5.1.19041.1682
* Chocolatey version (Run `choco --version`): 1.2.0
* Chocolatey GUI version: 1.1.0

### Output Log
Not quite sure if this log was already running when it happened.
https://gist.github.com/Destroy666x/ab08f6e737d10657213b64b0b018dcc4

**Comment by corbob** [comment]
I believe @gep13 answered this in discord:

> It could be that you were running into a problem with the cached list of packages which are marked as Outdated.  Within Chocolatey GUI, we keep that information around for a while, rather than fetching it each time the application is opened.  In the future you can purge this cache, as described here: https://docs.chocolatey.org/en-us/chocolatey-gui/user-interface/settings/actions/purge-outdated-packages

Does this answer the question and solve the issue being seen?

**Comment by Destroy666x** [comment]
Since you can change the duration of the cache and purge it, I think that's enough.
