### ISSUE TITLE
Unhandled Exception in io.zip

### ISSUE THREAD

**Issue by NeoFax75** [chocolatey/ChocolateyGUI#966]
### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`):
* 10.0.22622.0
* Windows PowerShell version (Run: `$PSVersionTable`):
* Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.22622
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
* Chocolatey version (Run `choco --version`):
* 1.2.0

##Screenshot##
https://i.imgur.com/6zOSWzX.jpeg

**Comment by pauby** [comment]
The error indicates that the package was corrupted and comes from Chocolatey CLI.

@NeoFax75 with updated versions of Chocolatey CLI, Chocolatey GUI and trying again, is this still an issue?
