### ISSUE TITLE
Upgrade to target version 6.4.0 of NuGet.Client and version 2.0.0 of Chocolatey.Lib assemblies

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/ChocolateyGUI#974]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

As Chocolatey CLI will be moving to v2.0.0 at some point, Chocolatey GUI should take a dependency on it.

### Describe The Solution. Why is it needed?

The `chocolatey.lib` dependency needs to be updated, and code needs to be adjusted to account for breaking changes.

### Related Issues

- Similar to #928

**Comment by gep13** [comment]
@TheCakeIsNaOH @AdmiringWorm I have added this issue to a new 2.0.0 milestone, but I am now wondering if this needs to be a 2.0.0 and not just a 1.2.0.  Thoughts?  My thoughts here being that Chocolatey GUI already has a requirement for .NET Framework 4.8.

**Comment by gep13** [comment]
Just spoken with @TheCakeIsNaOH about this, and we agree that this will be a breaking change to Chocolatey GUI, so the next version will be 2.0.0

**Comment by AdmiringWorm** [comment]
If we start taking a minimum dependency on Chocolatey v2.0.0, I agree this will be a breaking change.

**Comment by gep13** [comment]
While the PR associated with this has been merged, we still need to bump the version number in the nuspec, but we can't do that quite yet, unless we take a dependency on the alpha release, in the interim, or we simply hold off and update it to 2.0.0 once we ship.
